window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["1"]=[
  {q:'How many chromosomes does a normal human somatic cell contain?', a:'46 (23 pairs)', exp:'22 autosome pairs plus one sex-chromosome pair make up the normal diploid set.'},
  {q:'What is nondisjunction?', a:'Failure of chromosomes to separate in meiosis', exp:'Homologous chromosomes (meiosis I) or sister chromatids (meiosis II) fail to separate, yielding n+1 or n-1 gametes.'},
  {q:'Why does advanced MATERNAL age raise trisomy risk?', a:'Aging oocytes have degraded meiotic spindles', exp:'Oocytes arrest at prophase I before birth for decades, so older spindles are more error-prone.'},
  {q:'Which parent\'s age is the #1 risk factor for trisomy 21?', a:'Maternal age', exp:'Prolonged oocyte meiotic arrest, not paternal factors, drives increased nondisjunction risk.'},
  {q:'What is the karyotype of Down syndrome?', a:'Trisomy 21 (47,XX +21 or 47,XY +21)', exp:'It is an extra whole chromosome 21, not a single-gene mutation or a deletion.'},
  {q:'Name three classic physical clues of Down syndrome.', a:'Epicanthic folds, protruding tongue, single palmar crease', exp:'Flat facial profile and AV-canal heart defects also point to trisomy 21.'},
  {q:'What is the karyotype of Turner syndrome?', a:'45,X (monosomy X)', exp:'Turner is the only monosomy compatible with life; one sex chromosome is missing.'},
  {q:'A 14-year-old girl has short stature, webbed neck, and delayed puberty. Diagnosis?', a:'Turner syndrome (45,X)', exp:'Streak ovaries cause infertility; coarctation of the aorta is a classic association.'},
  {q:'What is the karyotype of Klinefelter syndrome?', a:'47,XXY', exp:'It is the extra X in a male, giving a tall phenotype with small firm testes and gynecomastia.'},
  {q:'A tall male has gynecomastia, small firm testes, and delayed puberty. Diagnosis?', a:'Klinefelter syndrome (47,XXY)', exp:'The extra X impairs testicular function, causing infertility and learning difficulties.'},
  {q:'What are the ratios for an autosomal recessive cross of two carriers?', a:'25% affected, 50% carrier, 25% unaffected', exp:'This 1:2:1 pattern affects both sexes equally and often skips generations.'},
  {q:'List three autosomal recessive diseases.', a:'Cystic fibrosis, sickle cell, PKU', exp:'Tay-Sachs and albinism are also AR; both parents are usually unaffected carriers.'},
  {q:'Which pattern shows disease in every generation with adult onset?', a:'Autosomal dominant', exp:'Only one affected allele is needed, so each child of an affected parent has a 50% risk.'},
  {q:'What single fact rules OUT X-linked inheritance in a pedigree?', a:'Male-to-male transmission', exp:'Fathers pass the Y (not the X) to sons, so no X-linked disease goes father to son.'},
  {q:'List three X-linked recessive diseases.', a:'Duchenne MD, hemophilia A, G6PD deficiency', exp:'Color blindness and hemophilia B are also X-linked recessive, affecting mostly males.'},
  {q:'A vignette says mom\'s brother died of the same disease. Which pattern?', a:'X-linked recessive', exp:'The disease traveled through the unaffected carrier mother to affected males on her side.'},
  {q:'Put the CFTR cystic fibrosis cascade in order.', a:'CFTR gene to Cl channel to water transport to thick mucus to infection', exp:'A defective CFTR chloride channel disrupts Cl/water transport; ordering questions love this exact chain.'},
  {q:'Why do sickle cells sickle?', a:'Hemoglobin S polymerizes under hypoxia', exp:'A beta-globin defect causes sickling that leads to vaso-occlusion and pain crises.'},
  {q:'What protein is missing in Duchenne muscular dystrophy?', a:'Dystrophin', exp:'Loss of dystrophin causes progressive proximal weakness, the Gower sign, and calf pseudohypertrophy in boys.'},
  {q:'What builds up inside cells in Tay-Sachs and other storage diseases?', a:'Undigested substrate material', exp:'A missing lysosomal enzyme lets substrate accumulate until cells swell and die.'},
  {q:'A father, brother, and sister all develop HTN as adults. Which inheritance?', a:'Multifactorial', exp:'Familial clustering without Mendelian ratios reflects multiple genes plus environment, not AD.'},
  {q:'Name three common multifactorial conditions.', a:'Hypertension, type 2 diabetes, neural tube defects', exp:'Coronary artery disease, cleft lip/palate, and schizophrenia are also multifactorial.'},
  {q:'Define epigenetics.', a:'Heritable changes in gene expression without altering DNA sequence', exp:'The genetic code stays the same; only which genes are turned on or off changes.'},
  {q:'Name the three main epigenetic mechanisms.', a:'DNA methylation, histone modification, non-coding RNA', exp:'These regulate gene accessibility and translation without changing the sequence.'},
  {q:'What does methylation of a gene promoter usually do?', a:'Silences gene expression', exp:'Methyl groups added to promoter cytosines block transcription of that gene.'},
  {q:'Why can identical twins develop different diseases?', a:'Different epigenetic marks from different environments', exp:'Same DNA, different lives produces divergent methylation and expression over time.'},
  {q:'Which parent\'s chromosome 15 is deleted in Prader-Willi syndrome?', a:'Paternal chromosome 15', exp:'The maternal copy is already imprinted-silenced, so losing the paternal copy leaves no working gene.'},
  {q:'Give the hallmark features of Prader-Willi syndrome.', a:'Hyperphagia, obesity, hypotonia, hypogonadism', exp:'Short stature and intellectual disability accompany the insatiable appetite.'},
  {q:'Which parent\'s chromosome 15 is deleted in Angelman syndrome?', a:'Maternal chromosome 15', exp:'The paternal copy is imprinted-silenced, so the happy-puppet phenotype results from losing the maternal copy.'},
  {q:'How does maternal diabetes program lifelong fetal disease risk?', a:'Hyperglycemia reprograms the fetal epigenome', exp:'Altered fetal methylation raises lifelong risk of obesity and type 2 diabetes without any mutation.'},
  {q:'Can air pollution harm a fetus without causing a DNA mutation?', a:'Yes, via epigenetic changes', exp:'Exposures alter fetal DNA methylation and gene expression for life without changing the sequence.'},
  {q:'How do many cancers silence tumor suppressor genes without deleting them?', a:'Promoter hypermethylation', exp:'The intact gene is present but not expressed, letting damaged cells escape apoptosis and proliferate.'},
  {q:'What are the four cellular adaptations to stress?', a:'Atrophy, hypertrophy, hyperplasia, metaplasia', exp:'The axes are size, number, and cell type; dysplasia is a maladaptive drift toward cancer.'},
  {q:'What is hypertrophy?', a:'Cells get bigger (same number)', exp:'Increased functional demand or hormonal stimulation drives it, as in LVH from hypertension.'},
  {q:'What is hyperplasia?', a:'Cells increase in number', exp:'Hormonal or compensatory stimulation drives it, as in endometrial growth, liver regeneration, or BPH.'},
  {q:'What is atrophy?', a:'Cells shrink from disuse or denervation', exp:'Loss of blood supply, hormonal stimulation, or aging also cause it, as in a casted limb.'},
  {q:'What is metaplasia and give the classic example?', a:'One cell type replaced by another; smoker\'s bronchus', exp:'Ciliated columnar epithelium is replaced by tougher squamous cells that cannot clear mucus; it is reversible.'},
  {q:'What is dysplasia and why does it matter?', a:'Disordered abnormal cells; precedes cancer', exp:'Unlike metaplasia it is not a normal adaptation and often drifts toward malignancy.'},
  {q:'What is the #1 cause of cell injury?', a:'Hypoxia', exp:'Reduced oxygen stops ATP production, triggering the whole injury cascade toward necrosis.'},
  {q:'In early hypoxic injury, why does the cell swell?', a:'Na/K pump fails, so Na and water enter', exp:'Falling ATP disables membrane pumps, causing reversible sodium and water influx.'},
  {q:'Order the hypoxic injury cascade.', a:'Low O2 to low ATP to pump failure to lactate to Ca influx to rupture to necrosis', exp:'Calcium influx and membrane rupture mark the irreversible point of no return.'},
  {q:'Why does lactate rise in hypoxic cells?', a:'Anaerobic metabolism produces lactate', exp:'Without O2, pyruvate is converted to lactate so glycolysis can continue; high lactate flags hypoperfusion.'},
  {q:'Contrast necrosis and apoptosis (membrane and inflammation).', a:'Necrosis ruptures and inflames; apoptosis stays intact and quiet', exp:'Necrotic contents spill and inflame, whereas apoptotic bodies are quietly phagocytosed.'},
  {q:'Does apoptosis require ATP?', a:'Yes, it is an active process', exp:'Apoptosis is programmed self-dismantling that needs energy, unlike ATP-depleted necrosis.'},
  {q:'List two triggers of necrosis.', a:'Ischemia and toxins', exp:'Trauma also causes necrosis, seen in MI, stroke infarct, gangrene, and pancreatitis.'},
  {q:'Which Starling force pulls water INTO capillaries?', a:'Capillary oncotic pressure (albumin)', exp:'Low albumin reduces this inward pull, allowing fluid to leak into the interstitium.'},
  {q:'Name the four classic causes of edema.', a:'High hydrostatic, low oncotic, high permeability, lymphatic obstruction', exp:'Each is a Starling force gone wrong, from heart failure to burns to lymphedema.'},
  {q:'Why does liver failure cause edema and ascites?', a:'Low albumin lowers capillary oncotic pressure', exp:'The failing liver cannot make albumin, so fluid leaks into the interstitium.'},
  {q:'What are the normal ranges for Na, K, and Ca?', a:'Na 135-145, K 3.5-5.0, Ca 8.5-10.5', exp:'Sodium controls osmolarity, potassium controls excitability, and calcium controls neuromuscular tone.'},
  {q:'What is the dangerous CNS effect of hyponatremia?', a:'Cerebral edema', exp:'Dilutional low sodium from overhydration or SIADH draws water into brain cells, causing confusion and seizures.'},
  {q:'What is the classic ECG sign of hyperkalemia?', a:'Peaked T waves', exp:'Rising potassium peaks T waves, then widens the QRS toward a sine wave and cardiac arrest.'},
  {q:'What are common causes of hyperkalemia?', a:'Renal failure, K-sparing diuretics, acidosis', exp:'CKD kidneys cannot excrete potassium, and tissue breakdown releases intracellular K.'},
  {q:'What are the classic ECG signs of hypokalemia?', a:'U waves and flattened T waves', exp:'Low potassium also causes ST depression and PVCs; U-waves mean low K.'},
  {q:'What neuromuscular sign is classic for hypocalcemia?', a:'Tetany', exp:'Low calcium raises neuronal excitability, producing Chvostek and Trousseau signs.'},
  {q:'What mnemonic summarizes hypercalcemia symptoms?', a:'Stones, bones, groans, and psychiatric moans', exp:'High calcium sedates: kidney stones, bone pain, abdominal pain, and confusion.'},
  {q:'Does low calcium excite or sedate neurons?', a:'Excites (causes tetany)', exp:'A common trap: low Ca raises excitability while high Ca causes lethargy and confusion.'},
  {q:'Which ABG value is the respiratory component?', a:'PaCO2 (normal 35-45)', exp:'High CO2 means respiratory acidosis and low CO2 means respiratory alkalosis.'},
  {q:'Which ABG value is the metabolic component?', a:'HCO3 (normal 22-26)', exp:'Low HCO3 means metabolic acidosis and high HCO3 means metabolic alkalosis; normal pH is 7.35-7.45.'},
  {q:'What does the ROME mnemonic stand for?', a:'Respiratory Opposite, Metabolic Equal', exp:'pH and CO2 move opposite in respiratory disorders; pH and HCO3 move together in metabolic ones.'},
  {q:'pH low and PaCO2 high. Which primary disorder?', a:'Respiratory acidosis', exp:'By ROME, pH and CO2 moving opposite directions indicate a respiratory problem.'},
  {q:'How do the kidneys compensate for respiratory acidosis?', a:'Retain bicarbonate (slow, over days)', exp:'Renal HCO3 retention pulls pH toward normal but takes days to develop.'},
  {q:'What acid-base disorder does DKA classically cause?', a:'Metabolic acidosis', exp:'Ketoacids lower HCO3 and pH, prompting deep rapid Kussmaul compensation.'},
  {q:'Why does a DKA patient breathe deep and fast?', a:'To blow off CO2 and raise pH', exp:'Kussmaul breathing is respiratory compensation for the metabolic acidosis, not the cause.'},
  {q:'What acid-base disorder does COPD exacerbation cause?', a:'Respiratory acidosis', exp:'Airway obstruction traps CO2, raising PaCO2 and lowering pH.'},
  {q:'What acid-base disorder does prolonged vomiting cause?', a:'Metabolic alkalosis', exp:'Loss of gastric HCl raises HCO3 and pH; pair vomiting with alkalosis.'},
  {q:'What acid-base disorder does severe diarrhea cause?', a:'Metabolic acidosis', exp:'Diarrhea loses bicarbonate in stool, lowering HCO3 and pH.'},
  {q:'What acid-base disorder does a panic attack cause?', a:'Respiratory alkalosis', exp:'Hyperventilation blows off too much CO2, raising pH.'},
  {q:'ABG: pH 7.22, PaCO2 26, HCO3 10. Interpretation?', a:'Metabolic acidosis with respiratory compensation', exp:'Low pH with low HCO3 is metabolic acidosis; the low CO2 is the lungs compensating (classic DKA).'},
  {q:'What is the 3-step method to read any ABG?', a:'Check pH, match to CO2 or HCO3, then check compensation', exp:'Identify acidemia vs alkalemia, find which value moves with pH, then see if the other is correcting.'},
  {q:'Is atrophy always pathologic?', a:'No, some is physiologic', exp:'Thymic atrophy with age and postmenopausal uterine atrophy are normal physiologic examples.'}
];
