window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["10"]=[
  {q:'What are the two main jobs of the respiratory system?', a:'Ventilation (moving air in/out) and gas exchange (O2 in, CO2 out across the alveolar-capillary membrane)', exp:'Both must work and both must be matched to perfusion.'},
  {q:'The alveolar-capillary membrane works best when it is what three things?', a:'Thin, dry, and large (big surface area)', exp:'Any change that thickens, wets, or shrinks it slows diffusion.'},
  {q:'How does pulmonary fibrosis cause hypoxemia?', a:'It thickens and stiffens the membrane, so O2 takes longer to cross', exp:'A classic diffusion defect from a thickened barrier.'},
  {q:'How do pulmonary edema and pneumonia impair oxygenation?', a:'Fluid or exudate in the alveoli increases the diffusion distance for O2', exp:'Longer path means slower O2 transfer into blood.'},
  {q:'Which conditions reduce oxygenation by lost alveolar surface area?', a:'Emphysema, atelectasis, and lung compression', exp:'Fewer working alveoli means less surface for gas exchange.'},
  {q:'Why does high altitude cause hypoxemia despite normal lungs?', a:'Low inspired O2 (low FiO2 and barometric pressure) lowers alveolar O2', exp:'There is simply less oxygen available to load.'},
  {q:'Where is the respiratory center located?', a:'The brainstem', exp:'It sets the rate and depth of breathing.'},
  {q:'What do central chemoreceptors mainly sense?', a:'CO2 and pH', exp:'They are the strongest day-to-day driver of breathing.'},
  {q:'What do peripheral chemoreceptors sense and where are they?', a:'Low O2 (hypoxemia); in the carotid and aortic bodies', exp:'They drive breathing when oxygen falls.'},
  {q:'When arterial O2 drops, what happens to breathing?', a:'Peripheral chemoreceptors fire, increasing rate and depth (hyperventilation/tachypnea)', exp:'A compensation to pull in more oxygen.'},
  {q:'Name three bedside signs of increased work of breathing.', a:'Tachypnea, nasal flaring, and accessory-muscle use', exp:'The body trying to fix a gas-exchange problem.'},
  {q:'Why is a falling respiratory rate ominous in a tiring hypoxemic patient?', a:'It signals the respiratory drive is failing, not improving', exp:'Fatigue can lead to CO2 retention and arrest.'},
  {q:'Why are the lungs a major acid-base organ?', a:'CO2 is an acid; dissolved CO2 plus water forms carbonic acid', exp:'How much you breathe directly sets blood acidity.'},
  {q:'What acid-base disorder results from hypoventilation?', a:'Respiratory acidosis (CO2 retained, more carbonic acid, pH falls)', exp:'Seen in COPD, sedation, and fatigue.'},
  {q:'What acid-base disorder results from hyperventilation?', a:'Respiratory alkalosis (CO2 blown off, less acid, pH rises)', exp:'Seen in anxiety, pain, and early hypoxemia.'},
  {q:'What is the normal arterial pH range?', a:'7.35 to 7.45', exp:'Below 7.35 is acidosis; above 7.45 is alkalosis.'},
  {q:'What is the normal PaCO2 range?', a:'35 to 45 mmHg', exp:'This is the respiratory number because CO2 is an acid.'},
  {q:'What is the normal PaO2 range?', a:'80 to 100 mmHg', exp:'A PaO2 under 80 defines hypoxemia.'},
  {q:'What is the normal HCO3 (bicarbonate) range?', a:'22 to 26 mEq/L', exp:'This is the metabolic (kidney) number.'},
  {q:'In respiratory acidosis, what happens to pH and PaCO2?', a:'pH falls and PaCO2 rises', exp:'Hypoventilation retains acid-forming CO2.'},
  {q:'In respiratory alkalosis, what happens to pH and PaCO2?', a:'pH rises and PaCO2 falls', exp:'Hyperventilation blows off CO2.'},
  {q:'Interpret ABG: pH 7.32, PaCO2 48, PaO2 60.', a:'Respiratory acidosis with hypoxemia from hypoventilation', exp:'Low pH plus high CO2 plus low O2.'},
  {q:'Why does an early hypoxemic patient show respiratory alkalosis?', a:'They hyperventilate, blowing off CO2 and raising pH', exp:'A compensatory response before fatigue sets in.'},
  {q:'Why is a rising CO2 in a hypoxemic patient a danger sign?', a:'It means the patient is tiring or obstructing and failing to ventilate', exp:'Signals a shift from alkalosis toward acidosis.'},
  {q:'What defines obstructive lung disease?', a:'Increased airway resistance, so air cannot be exhaled fully', exp:'The problem is getting air out.'},
  {q:'What defines restrictive lung disease?', a:'Decreased lung compliance, so lungs cannot expand fully', exp:'The problem is getting air in.'},
  {q:'Give three examples of obstructive lung disease.', a:'Asthma, COPD (chronic bronchitis and emphysema), and bronchiolitis', exp:'All share increased airway resistance.'},
  {q:'Give three examples of restrictive lung disease.', a:'Pulmonary fibrosis, ARDS, and atelectasis (also pleural effusion, chest-wall disease)', exp:'All share reduced lung compliance.'},
  {q:'What are the hallmark findings of obstructive disease?', a:'Wheeze, prolonged expiration, air trapping, barrel chest, and pursed-lip breathing', exp:'Air gets in easier than it gets out.'},
  {q:'What are the hallmark findings of restrictive disease?', a:'Rapid, shallow breaths (tachypnea) and decreased lung volumes', exp:'Stiff lungs resist filling.'},
  {q:'What is the obstruction mechanism in asthma?', a:'Reversible bronchial smooth-muscle constriction with inflammation and mucus', exp:'Narrows the lumen, producing wheeze.'},
  {q:'What is the obstruction mechanism in emphysema?', a:'Destruction of alveolar walls with loss of elastic recoil, so airways collapse on exhalation', exp:'Causes air trapping and barrel chest.'},
  {q:'Why does severe obstruction cause hypercapnia?', a:'Trapped air prevents CO2 from being exhaled, so it accumulates', exp:'Retained CO2 drives respiratory acidosis.'},
  {q:'What two diseases make up COPD?', a:'Chronic bronchitis and emphysema', exp:'Often coexist in long-term smokers.'},
  {q:'What characterizes chronic bronchitis?', a:'Chronic productive cough from airway inflammation and excess mucus', exp:'Defined clinically as cough for 3 months over 2 years.'},
  {q:'What is hypoxemia?', a:'Low oxygen level in the arterial blood', exp:'Measured as PaO2 under 80 mmHg.'},
  {q:'What is hypoxia?', a:'Low oxygen delivery to the tissues', exp:'Hypoxemia can cause hypoxia, but they are not the same thing.'},
  {q:'What is V/Q mismatch?', a:'Air (ventilation) and blood (perfusion) not matched in the same lung area', exp:'The most common cause of hypoxemia.'},
  {q:'What is dead space?', a:'Alveoli that are ventilated but not perfused', exp:'The classic example is pulmonary embolism.'},
  {q:'What is a shunt?', a:'Blood that passes unventilated alveoli (perfusion without ventilation)', exp:'Seen with pneumonia, atelectasis, and edema.'},
  {q:'How does a pulmonary embolism cause hypoxemia?', a:'A clot blocks perfusion, so ventilated alveoli get no blood flow (dead space)', exp:'The problem is perfusion, not ventilation.'},
  {q:'What is hypoxic pulmonary vasoconstriction?', a:'Vessels in low-oxygen lung regions clamp down to redirect blood to better-ventilated areas', exp:'Chronic and widespread, it raises pulmonary pressures.'},
  {q:'How does chronic hypoxemia lead to pulmonary hypertension?', a:'Widespread hypoxic vasoconstriction raises pulmonary arterial pressure over time', exp:'Seen across the whole lung in COPD.'},
  {q:'What classic symptoms suggest pulmonary embolism?', a:'Sudden dyspnea, pleuritic chest pain, tachypnea, and tachycardia', exp:'Often from a deep vein thrombosis embolizing to the lung.'},
  {q:'How does pulmonary edema affect the alveoli?', a:'Fluid floods the alveoli, increasing diffusion distance', exp:'Often from left heart failure or capillary injury.'},
  {q:'What is the mechanism of ARDS?', a:'Diffuse alveolar injury with increased capillary permeability floods alveoli with protein-rich fluid', exp:'Causes severe, refractory hypoxemia.'},
  {q:'Name three common triggers of ARDS.', a:'Sepsis, aspiration, and trauma (also toxic gas)', exp:'Any severe insult can injure the alveolar membrane.'},
  {q:'Why is ARDS hypoxemia refractory to oxygen alone?', a:'Fluid-filled, collapsed alveoli create a large shunt that supplemental O2 cannot correct', exp:'Blood bypasses gas exchange entirely.'},
  {q:'What is atelectasis?', a:'Collapse of alveoli from obstruction, compression, or surfactant loss', exp:'Reduces ventilation and creates a shunt.'},
  {q:'How does atelectasis cause hypoxemia?', a:'Collapsed alveoli are perfused but not ventilated, producing a shunt', exp:'Blood passes lung units that receive no air.'},
  {q:'What fills the alveoli in pneumonia?', a:'Inflammatory exudate from infection', exp:'Increases diffusion distance and causes hypoxemia.'},
  {q:'What are typical signs of pneumonia?', a:'Productive cough, fever, hypoxemia, and focal crackles', exp:'Chest imaging shows consolidation.'},
  {q:'What is a pleural effusion?', a:'Fluid collecting in the pleural space that compresses the lung', exp:'Restricts expansion and reduces breath sounds.'},
  {q:'What is an empyema?', a:'Infected, purulent (pus) fluid in the pleural space', exp:'Bacteria seed the space with exudate and fibrin.'},
  {q:'What causes pleuritic chest pain?', a:'Inflammation of the parietal pleura, which contains pain fibers', exp:'The lung tissue itself has no pain fibers.'},
  {q:'Why does pleuritic pain worsen with deep breathing?', a:'Lung expansion stretches the inflamed parietal pleura', exp:'Sharp pain that peaks on inspiration.'},
  {q:'What is a pneumothorax?', a:'Air in the pleural space causing partial or full lung collapse', exp:'Loss of negative pressure lets the lung recoil inward.'},
  {q:'What is a tension pneumothorax?', a:'A one-way air leak that progressively compresses the lung, heart, and great vessels', exp:'A medical emergency causing tracheal deviation and hypotension.'},
  {q:'What are signs of a pneumothorax?', a:'Sudden dyspnea, sharp chest pain, and decreased breath sounds on the affected side', exp:'Air replaces lung on that side.'},
  {q:'What causes cyanosis?', a:'Increased deoxygenated hemoglobin in capillary blood, giving a bluish color', exp:'Depends on the amount of deoxy-Hb, not just saturation.'},
  {q:'What causes digital clubbing?', a:'Chronic hypoxemia drives growth factors that proliferate fingertip tissue', exp:'A sign of long-standing disease.'},
  {q:'What is cor pulmonale?', a:'Right ventricular failure caused by chronic pulmonary hypertension', exp:'Presents with JVD, edema, and hepatomegaly.'},
  {q:'What is the mechanism of neonatal RDS?', a:'Surfactant deficiency raises surface tension, so alveoli collapse on exhalation', exp:'Immature type II cells cannot make enough surfactant.'},
  {q:'What does surfactant do?', a:'Lowers alveolar surface tension to keep alveoli open at the end of each breath', exp:'Prevents collapse and eases the work of breathing.'},
  {q:'Why do children show chest retractions with airway obstruction?', a:'Harder inspiratory effort makes intrathoracic pressure more negative, pulling in the compliant chest wall', exp:'A stiff adult chest wall retracts less.'},
  {q:'What causes croup and how does it present?', a:'Viral subglottic (upper airway) inflammation causing barking cough and inspiratory stridor', exp:'Also produces a hoarse voice.'},
  {q:'What causes bronchiolitis and how does it present?', a:'RSV inflaming lower small airways, causing wheeze and air trapping in infants', exp:'Air gets in more easily than out.'},
  {q:'What airway sound signals upper airway narrowing?', a:'Stridor, a harsh sound heard on inspiration', exp:'Classic for croup.'},
  {q:'What airway sound signals lower airway narrowing?', a:'Wheeze, heard on expiration', exp:'Seen in asthma and bronchiolitis.'},
  {q:'How does complete foreign-body obstruction cause atelectasis?', a:'Trapped distal air is absorbed into the blood, and the unventilated alveoli collapse', exp:'Called resorption atelectasis.'}
];
