window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["11"]=[
  {q:'What is the functional unit of the kidney?', a:'The nephron (glomerulus + tubule)', exp:'Each kidney holds about a million nephrons that filter and fine-tune.'},
  {q:'Which force drives glomerular filtration?', a:'Glomerular capillary hydrostatic (blood) pressure', exp:'Blood pressure pushes fluid across the filtration barrier into the tubule.'},
  {q:'Which nephron segment reabsorbs the MOST filtered water, sodium, and glucose?', a:'The proximal tubule', exp:'It is the bulk-reabsorption workhorse.'},
  {q:'Which structure builds the medullary gradient that lets the kidney concentrate urine?', a:'The loop of Henle (countercurrent multiplier)', exp:'Its countercurrent system creates the osmotic gradient for water reabsorption.'},
  {q:'What final tubular adjustments are made under aldosterone and ADH?', a:'Aldosterone controls Na/K; ADH controls water at the distal tubule/collecting duct', exp:'This is where the body does last-minute fine-tuning.'},
  {q:'What does GFR measure?', a:'How much blood the kidneys filter per minute; the key measure of kidney function', exp:'Glomerular filtration rate is the master gauge of renal function.'},
  {q:'A patient has elevated plasma creatinine. What does this indicate?', a:'GFR has declined, so creatinine accumulates (reduced kidney filtration)', exp:'Creatinine is cleared by filtration, so it mirrors GFR inversely.'},
  {q:'Creatinine rises when GFR does what?', a:'Falls', exp:'Creatinine up = GFR down is the classic relationship.'},
  {q:'Why is creatinine a useful marker of kidney function?', a:'It is a waste product cleared by filtration, so its blood level reflects GFR', exp:'When filtration drops, creatinine builds up in the blood.'},
  {q:'What does autoregulation of the kidney accomplish?', a:'Keeps GFR roughly constant despite changing blood pressure', exp:'The kidney protects its own filtration rate.'},
  {q:'The kidney adjusts which two vessels to autoregulate GFR?', a:'The afferent (incoming) and efferent (outgoing) arterioles', exp:'Tuning these arterioles stabilizes filtration pressure.'},
  {q:'What happens to GFR when sympathetic activation constricts the afferent arteriole?', a:'GFR falls (less blood enters the glomerulus)', exp:'This shunts blood away from the kidney during shock or stress.'},
  {q:'What triggers renin release from the kidney?', a:'Low blood pressure or reduced renal perfusion/flow', exp:'Renin launches the RAAS cascade to restore volume and pressure.'},
  {q:'What does renin ultimately produce through the RAAS cascade?', a:'Angiotensin II (vasoconstriction) and aldosterone (Na and water retention)', exp:'Together they raise blood volume and pressure.'},
  {q:'What is the net effect of RAAS activation on blood volume and pressure?', a:'It raises both by retaining sodium and water and constricting vessels', exp:'RAAS is the body\'s low-pressure rescue axis.'},
  {q:'What does aldosterone do at the distal nephron?', a:'Promotes sodium (and water) retention and potassium excretion', exp:'It is the salt-retaining hormone of RAAS.'},
  {q:'What does ADH do at the collecting duct?', a:'Makes it reabsorb water, producing concentrated urine and higher blood volume', exp:'ADH is the water-conserving hormone.'},
  {q:'A patient\'s blood pressure drops. Why does renin release increase?', a:'Reduced renal perfusion triggers renin to activate RAAS', exp:'The kidney senses low flow and acts to raise pressure.'},
  {q:'Sympathetic activation constricts the afferent arteriole. What is the result?', a:'Reduced blood flow into the glomerulus and a lower GFR', exp:'Useful for redirecting blood during stress or shock.'},
  {q:'What is hydronephrosis?', a:'Dilation of the renal pelvis and calyces from obstructed urine flow', exp:'Back-pressure distends the collecting system.'},
  {q:'What happens to GFR during urinary tract obstruction?', a:'It falls as back-pressure in the tubules opposes filtration', exp:'Prolonged obstruction can cause acute kidney injury.'},
  {q:'Why does obstruction increase infection risk?', a:'Stagnant, retained urine is a breeding ground for bacteria', exp:'Stasis promotes UTIs.'},
  {q:'What is postobstructive diuresis?', a:'A large urine output after relieving an obstruction as retained fluid and solutes are excreted', exp:'Watch for dehydration and electrolyte loss.'},
  {q:'What is the most common type of kidney stone?', a:'Calcium oxalate', exp:'It forms when concentrated urine supersaturates with stone-forming salts.'},
  {q:'What urine condition promotes kidney stone formation?', a:'Concentrated urine (dehydration) causing supersaturation', exp:'Staying hydrated dilutes urine and helps prevent stones.'},
  {q:'Describe the classic pain of renal colic.', a:'Sudden severe flank pain radiating to the groin, in colicky waves, with restlessness and nausea', exp:'A stone lodged in the ureter produces wave-like pain.'},
  {q:'How does staying well hydrated help prevent stones?', a:'Dilute urine lowers the concentration of stone-forming salts', exp:'Less supersaturation means fewer crystals.'},
  {q:'What is a ureteropelvic junction (UPJ) obstruction?', a:'Narrowing where the renal pelvis meets the ureter, causing back-pressure and hydronephrosis', exp:'A classic cause of upper-tract dilation.'},
  {q:'Most UTIs spread by which route?', a:'Ascending (bacteria travel up from the urethra)', exp:'They climb from urethra to bladder and can reach the kidney.'},
  {q:'What is cystitis?', a:'Infection/inflammation of the bladder (lower UTI)', exp:'The lower urinary tract infection.'},
  {q:'What are the classic symptoms of cystitis?', a:'Urgency, frequency, dysuria (burning), and suprapubic discomfort', exp:'The irritated bladder signals the urge to void even when nearly empty.'},
  {q:'What is pyelonephritis?', a:'Infection that has reached the kidney (upper UTI), usually ascending', exp:'The more serious, higher-level UTI.'},
  {q:'What clues suggest pyelonephritis rather than cystitis?', a:'Flank pain, fever, chills, and systemic illness', exp:'Kidney involvement produces systemic symptoms.'},
  {q:'Why does cystitis cause urgency and frequency?', a:'Bladder wall inflammation triggers the urge to void even when the bladder is not full', exp:'Inflammation irritates the bladder and produces dysuria too.'},
  {q:'What structural problems raise UTI risk by trapping urine?', a:'Obstruction, incomplete emptying, and reflux', exp:'Anything causing stasis lets bacteria multiply.'},
  {q:'What is acute kidney injury (AKI)?', a:'A sudden drop in GFR', exp:'It is abrupt and often reversible if the cause is corrected.'},
  {q:'What is the most common category of AKI?', a:'Prerenal (poor blood flow to the kidney)', exp:'Dehydration, hemorrhage, and shock are typical causes.'},
  {q:'A dehydrated patient develops oliguria. What is the mechanism?', a:'Reduced renal blood flow lowers GFR, so less urine forms (prerenal AKI)', exp:'The kidney is starved of blood.'},
  {q:'What is intrarenal AKI?', a:'Direct kidney tissue damage (from toxins, ischemia, or myoglobin)', exp:'The injury is within the kidney itself.'},
  {q:'What is postrenal AKI?', a:'AKI caused by obstruction of urine outflow', exp:'A blockage downstream backs pressure up into the kidney.'},
  {q:'What is oliguria?', a:'Abnormally low urine output', exp:'A hallmark of falling GFR in AKI.'},
  {q:'What happens to creatinine and waste products as GFR falls in AKI?', a:'They rise and accumulate in the blood', exp:'Reduced filtration lets wastes build up.'},
  {q:'What is glomerulonephritis?', a:'Inflammation that damages the glomerulus, letting blood leak into the urine', exp:'The inflamed filter becomes leaky to red blood cells.'},
  {q:'What causes hematuria in glomerular disease?', a:'Inflammation damages the glomerular filter, letting red blood cells leak into urine', exp:'A damaged glomerulus loses its selectivity.'},
  {q:'What is the nephrotic pattern of glomerular injury?', a:'Barrier damage causes massive protein loss (proteinuria), low albumin, and edema', exp:'The filter leaks protein instead of just blood.'},
  {q:'Why does nephrotic syndrome cause edema?', a:'Heavy urinary protein loss lowers blood albumin and oncotic pressure, so fluid leaks into tissues', exp:'Low oncotic pressure lets fluid shift out of vessels.'},
  {q:'Contrast nephritic vs nephrotic in one line.', a:'Nephritic = blood in urine (hematuria); nephrotic = protein in urine leading to edema', exp:'Inflammation leaks blood; barrier breakdown leaks protein.'},
  {q:'What is chronic kidney disease (CKD)?', a:'Progressive, irreversible loss of nephrons over time', exp:'Unlike AKI, the damage is permanent.'},
  {q:'What is the most common cause of CKD?', a:'Diabetes mellitus (then hypertension)', exp:'It damages the small renal vessels over years.'},
  {q:'Why does CKD cause anemia?', a:'Damaged kidneys make less erythropoietin (EPO), so fewer red blood cells are produced', exp:'Low EPO leads to fatigue and pallor.'},
  {q:'What hormone made by the kidney stimulates red blood cell production?', a:'Erythropoietin (EPO)', exp:'Its loss in CKD causes anemia.'},
  {q:'Which electrolyte imbalance is a CKD patient at greatest risk for?', a:'Hyperkalemia (high potassium)', exp:'Failing kidneys cannot excrete potassium, which is dangerous for the heart.'},
  {q:'Why does hyperkalemia develop in CKD?', a:'Failing kidneys cannot excrete potassium, so it accumulates', exp:'Retained potassium threatens cardiac rhythm.'},
  {q:'What acid-base disturbance is typical in CKD?', a:'Metabolic acidosis', exp:'The kidney loses its ability to excrete acid and regulate bicarbonate.'},
  {q:'Why do bone and mineral changes occur in CKD?', a:'Altered calcium, phosphate, and vitamin D handling by the failing kidney', exp:'The kidney normally activates vitamin D and excretes phosphate.'},
  {q:'What fluid problem develops as CKD advances?', a:'Fluid overload with edema from lost excretory capacity', exp:'The kidney can no longer remove excess fluid.'},
  {q:'What is dialysis used for in kidney failure?', a:'To remove wastes, excess fluid, and correct electrolytes when the kidneys can no longer do so', exp:'It substitutes for lost filtration and regulation.'},
  {q:'What is vesicoureteral reflux (VUR)?', a:'A failed valve at the bladder-ureter junction that lets urine flow backward toward the kidney', exp:'Reflux carries bacteria upward and causes recurrent UTIs and scarring.'},
  {q:'What normally prevents urine reflux from bladder into the ureters?', a:'A one-way valve at the ureterovesical (bladder) junction', exp:'When it fails, VUR results.'},
  {q:'Why does VUR cause recurrent infections?', a:'Urine refluxes backward toward the kidney, carrying bacteria upward', exp:'Repeated infections can scar the kidney.'},
  {q:'What is polycystic kidney disease (PKD)?', a:'A disease in which fluid-filled cysts enlarge and replace functional kidney tissue', exp:'It is not a blockage but crowding-out of nephrons.'},
  {q:'How does PKD reduce kidney function?', a:'Growing fluid-filled cysts compress and replace functional nephrons over time', exp:'Function declines as the cysts expand.'},
  {q:'What can congenital bladder outlet obstruction (e.g., posterior urethral valves) cause?', a:'Back-pressure up the tract leading to hydronephrosis and kidney damage if untreated', exp:'Persistent obstruction progressively harms the kidneys.'},
  {q:'What causes poststreptococcal glomerulonephritis?', a:'Immune complexes form after a strep infection and deposit in the glomeruli, causing inflammation', exp:'It appears after the strep infection resolves.'},
  {q:'What are the classic findings of poststreptococcal glomerulonephritis?', a:'Hematuria (tea/cola-colored urine), edema, and hypertension', exp:'The inflamed filter leaks blood.'},
  {q:'When does poststreptococcal glomerulonephritis typically appear?', a:'After the strep infection has resolved (a delayed immune reaction)', exp:'The lag reflects immune-complex formation and deposition.'},
  {q:'What causes childhood nephrotic syndrome?', a:'Glomerular barrier damage causing heavy proteinuria, low albumin, and edema', exp:'Protein leaks out and oncotic pressure falls.'},
  {q:'What is hemolytic uremic syndrome (HUS)?', a:'Endothelial injury and microthrombi in the kidney, often after toxin-producing E. coli', exp:'It comes with hemolytic anemia and low platelets.'},
  {q:'What is nephroblastoma (Wilms tumor)?', a:'A childhood kidney cancer from malignant proliferation of embryonic kidney cells', exp:'It presents as a large, often one-sided abdominal/renal mass.'},
  {q:'Why are infants prone to rapid dehydration and fluid imbalance?', a:'Higher body-water percentage and turnover plus immature kidneys that concentrate urine poorly', exp:'They lose fluid fast and tip into imbalance quickly.'}
];
