window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["12"]=[
  {q:'Which hormone from the hypothalamus triggers the pituitary to release FSH and LH?', a:'GnRH (gonadotropin-releasing hormone)', exp:'GnRH rises at puberty to start reproductive function.'},
  {q:'What is the main job of FSH in the ovarian cycle?', a:'Stimulates ovarian follicles to mature', exp:'FSH = Follicle Stimulating, it grows the egg.'},
  {q:'Which hormone surge directly triggers ovulation?', a:'The LH surge', exp:'Think LH = Launches the egg.'},
  {q:'What does estrogen do to the endometrium during the follicular phase?', a:'Builds up (proliferates) the endometrial lining', exp:'Estrogen is the builder hormone.'},
  {q:'Which structure secretes progesterone after ovulation?', a:'The corpus luteum (the ruptured follicle)', exp:'Corpus luteum = pro-gestation, it holds the lining.'},
  {q:'What is the primary role of progesterone in the cycle?', a:'Maintains and stabilizes the endometrium for possible pregnancy', exp:'Progesterone is the stay hormone.'},
  {q:'What event directly causes menstruation when no pregnancy occurs?', a:'Progesterone withdrawal as the corpus luteum degenerates', exp:'Loss of hormonal support makes the lining break down and shed.'},
  {q:'Where does fertilization most often occur?', a:'The fallopian tube (ampulla)', exp:'The egg meets sperm in the tube, not the uterus.'},
  {q:'The corpus luteum dies and progesterone falls. What mechanism leads to menstruation?', a:'Loss of endometrial support causing tissue breakdown', exp:'Without progesterone the lining loses its scaffold.'},
  {q:'What two-part defect defines the core pathophysiology of PCOS?', a:'Anovulation plus insulin resistance', exp:'High insulin drives androgens and disrupts the LH surge.'},
  {q:'In PCOS, how does high insulin cause anovulation?', a:'It raises ovarian androgens and disrupts the LH surge so eggs do not release', exp:'No LH surge means no ovulation.'},
  {q:'Why is uterine bleeding irregular in PCOS?', a:'No ovulation means no progesterone, so unopposed estrogen overgrows the lining, which sheds erratically', exp:'Skipped cycles then heavy bleeding is the classic pattern.'},
  {q:'A PCOS patient should be monitored for which two long-term risks?', a:'Endometrial cancer and type 2 diabetes', exp:'From unopposed estrogen and insulin resistance respectively.'},
  {q:'Which mediator causes the cramping of primary dysmenorrhea?', a:'Prostaglandins', exp:'They cause uterine contractions and reduced blood flow.'},
  {q:'How do prostaglandins produce pain in primary dysmenorrhea?', a:'They trigger strong uterine contractions and vasoconstriction, reducing uterine blood flow', exp:'Ischemic cramping is the result.'},
  {q:'What is amenorrhea?', a:'Absence of menstrual periods', exp:'Causes include anovulation, hormonal, and structural problems.'},
  {q:'What lab and physical findings support a PCOS diagnosis?', a:'Elevated insulin and testosterone, irregular cycles, obesity, acne, hirsutism, and many small peripheral ovarian follicles', exp:'Olivia is the case example with these features.'},
  {q:'What is endometriosis?', a:'Ectopic endometrial tissue outside the uterus that still responds to cyclic hormones', exp:'It bleeds cyclically wherever it lands.'},
  {q:'Why does endometriosis cause pain and infertility?', a:'The ectopic tissue bleeds cyclically, causing inflammation and pelvic adhesions', exp:'Adhesions distort pelvic anatomy.'},
  {q:'What is a uterine fibroid (leiomyoma)?', a:'A benign smooth-muscle tumor of the uterus', exp:'It causes heavy bleeding and bulk or pressure symptoms.'},
  {q:'How do you distinguish endometriosis from a fibroid?', a:'Endometriosis is endometrial tissue in the wrong place; a fibroid is benign smooth muscle of the uterus itself', exp:'Wrong tissue location versus wrong tissue type.'},
  {q:'What causes endometrial hyperplasia?', a:'Prolonged estrogen exposure without progesterone (unopposed estrogen)', exp:'Estrogen builds, progesterone controls.'},
  {q:'Why can endometrial hyperplasia be dangerous?', a:'It can progress to endometrial cancer', exp:'Unopposed estrogen is the driving risk.'},
  {q:'Why does androgen insensitivity syndrome cause absent menstruation?', a:'No uterus develops, so there is no endometrium to shed', exp:'The person is genetically male but cannot respond to androgens.'},
  {q:'What protects the vagina from infection normally?', a:'Its acidic (low pH) environment maintained by estrogen', exp:'Acidity keeps harmful microbes from overgrowing.'},
  {q:'How does vaginitis develop?', a:'Disrupted normal flora and a raised vaginal pH let microorganisms overgrow', exp:'Losing acidity opens the door to infection.'},
  {q:'Why does douching increase infection risk?', a:'It washes out protective flora and raises vaginal pH', exp:'A higher pH favors microbial overgrowth.'},
  {q:'Why is vaginitis risk increased after menopause?', a:'Low estrogen thins and atrophies the vaginal lining and raises pH', exp:'Atrophic tissue and lost acidity weaken defense.'},
  {q:'How does PID lead to ectopic pregnancy?', a:'Infection scars the fallopian tubes, blocking normal egg transport so implantation occurs in the tube', exp:'Fallopian tube scarring is the mechanism.'},
  {q:'What is an ectopic pregnancy?', a:'Implantation outside the uterus, usually in a scarred fallopian tube', exp:'It cannot proceed safely and can rupture.'},
  {q:'What broad changes define menopause?', a:'Ovarian estrogen declines and cycles stop, causing atrophy, vasomotor symptoms, and bone loss', exp:'Estrogen decline drives the symptoms.'},
  {q:'Which cells produce testosterone in the testes?', a:'The Leydig cells', exp:'Sperm form in the seminiferous tubules.'},
  {q:'Where do sperm mature and gain motility?', a:'The epididymis', exp:'Sperm are not fully functional until they pass through it.'},
  {q:'Which sperm structure provides motility?', a:'The flagellum (tail)', exp:'Tail dysfunction impairs sperm movement.'},
  {q:'Fundamentally, what type of event is an erection?', a:'A vascular event of blood filling the erectile tissue', exp:'Arterial inflow fills while venous outflow is restricted.'},
  {q:'Describe the vascular mechanics of an erection.', a:'Parasympathetic signals dilate arteries, blood fills the sinusoids, and swelling compresses the veins to trap it', exp:'Inflow up, outflow trapped.'},
  {q:'What happens to testosterone with male aging?', a:'It gradually declines', exp:'This reduces libido, muscle mass, and sperm production.'},
  {q:'A patient has impaired sperm motility. Which structure is most likely dysfunctional?', a:'The sperm flagellum (tail)', exp:'The tail propels the sperm forward.'},
  {q:'What is testicular torsion?', a:'The spermatic cord twists and cuts off blood supply, causing ischemia', exp:'It is a surgical emergency.'},
  {q:'What is the classic presentation of testicular torsion?', a:'Sudden severe scrotal pain, often during activity, with nausea and a high-riding testicle', exp:'Minutes matter to save the testicle.'},
  {q:'What is epididymitis and how does it present?', a:'Inflammation of the epididymis, often from an STI, with gradual scrotal pain and burning urination (dysuria)', exp:'Gradual onset plus dysuria separates it from torsion.'},
  {q:'What distinguishes torsion from epididymitis clinically?', a:'Torsion is sudden with a high-riding testis; epididymitis is gradual with dysuria and STI exposure', exp:'Timing and dysuria are the key discriminators.'},
  {q:'What is orchitis and what classically causes it?', a:'Testicular inflammation, classically after a viral illness such as mumps', exp:'Fever plus painful swelling follows the virus.'},
  {q:'What is a varicocele and why does it lower sperm quality?', a:'Dilated scrotal veins pool warm blood and raise testicular temperature', exp:'Sperm production needs a cooler-than-core temperature.'},
  {q:'What is cryptorchidism and its main risks?', a:'An undescended testis that raises later risk of infertility and testicular cancer', exp:'The testis fails to descend into the scrotum.'},
  {q:'What causes gynecomastia?', a:'An estrogen-to-testosterone imbalance (relative estrogen excess)', exp:'Male breast tissue enlarges from the imbalance.'},
  {q:'How does the prostate cause urinary symptoms when enlarged?', a:'It wraps around the urethra, so enlargement compresses the urethra', exp:'This squeezes the urinary stream.'},
  {q:'What is BPH?', a:'Benign prostatic hyperplasia, a non-cancerous prostate enlargement common with aging', exp:'It compresses the urethra without being malignant.'},
  {q:'What are the classic obstructive urinary symptoms of prostate enlargement?', a:'Hesitancy, weak stream, incomplete emptying, and nocturia', exp:'They come from urethral compression.'},
  {q:'How can prostate cancer cause urinary symptoms?', a:'Tumor growth compresses and obstructs the urethra', exp:'The mechanism mirrors BPH.'},
  {q:'What test, besides exam, helps screen for prostate cancer?', a:'PSA (prostate-specific antigen)', exp:'BPH is benign, but cancer must be ruled out.'},
  {q:'Where does prostate cancer classically metastasize?', a:'To bone', exp:'It may be asymptomatic early before spreading.'},
  {q:'Why is most erectile dysfunction a blood-flow problem?', a:'Because erection is a vascular event, so reduced arterial inflow prevents filling', exp:'ED is often the first sign of systemic vascular disease.'},
  {q:'Name three systemic conditions that cause vascular ED.', a:'Atherosclerosis, diabetes, and hypertension', exp:'They all reduce arterial inflow.'},
  {q:'What is priapism?', a:'A prolonged unwanted erection where trapped blood becomes deoxygenated and ischemic', exp:'It is an emergency because ischemia damages tissue.'},
  {q:'Why can priapism lead to later erectile dysfunction?', a:'Trapped blood becomes ischemic and damages the erectile tissue', exp:'Tissue injury impairs future erections.'},
  {q:'Contrast vascular ED with priapism.', a:'Vascular ED is too little inflow; priapism is blood getting stuck and going ischemic', exp:'Opposite extremes of blood flow.'},
  {q:'Why does amenorrhea from anovulation still need follow-up?', a:'The endometrium is unprotected by progesterone and can undergo hyperplasia', exp:'Unopposed estrogen keeps building the lining.'},
  {q:'A patient reports skipped cycles then heavy bleeding. What process explains it?', a:'Anovulation with endometrial overgrowth from unopposed estrogen', exp:'No progesterone means erratic shedding.'},
  {q:'Which cancer risk is raised by PCOS due to unopposed estrogen?', a:'Endometrial cancer', exp:'Chronic anovulation removes progesterone protection.'},
  {q:'A 17-year-old has sudden severe scrotal pain during sports with a high-riding testicle. Diagnosis?', a:'Testicular torsion', exp:'The twisted cord causes ischemia, a surgical emergency.'},
  {q:'A 25-year-old has gradual scrotal pain and dysuria after unprotected sex. Diagnosis?', a:'Epididymitis', exp:'STI-related, gradual onset with burning urination.'},
  {q:'Which reflex is typically absent in testicular torsion?', a:'The cremasteric reflex', exp:'Its absence supports the torsion diagnosis.'},
  {q:'What is the general definition of an STI?', a:'A sexually transmitted infection spread through sexual contact', exp:'Common examples include chlamydia and gonorrhea.'},
  {q:'Which STIs most commonly cause PID?', a:'Chlamydia and gonorrhea', exp:'Untreated they ascend and scar the tubes.'},
  {q:'Which virus is strongly linked to cervical cancer?', a:'Human papillomavirus (HPV)', exp:'Persistent high-risk HPV drives cervical dysplasia.'},
  {q:'What screening test detects early cervical cell changes?', a:'The Pap smear (cervical cytology)', exp:'It catches dysplasia before invasive cancer.'},
  {q:'What hormonal change underlies menopausal hot flashes?', a:'Declining estrogen affecting the vasomotor centers', exp:'Estrogen loss triggers the flushing and sweating.'},
  {q:'Why does menopause increase osteoporosis risk?', a:'Estrogen loss accelerates bone resorption and bone density decline', exp:'Estrogen normally protects bone.'},
  {q:'What is the key structural difference explaining why a fibroid causes bulk symptoms?', a:'It is a solid benign smooth-muscle mass that presses on nearby structures', exp:'Its size creates pressure and heavy bleeding.'}
];
