window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["13"]=[
  {q:'What is peristalsis?', a:'Coordinated waves of smooth-muscle contraction that propel GI contents from mouth to anus', exp:'It is why swallowing works even lying down.'},
  {q:'Which division of the autonomic nervous system stimulates GI motility and secretion?', a:'Parasympathetic (rest and digest)', exp:'Acetylcholine drives salivation and peristalsis.'},
  {q:'Why do anticholinergic drugs cause dry mouth and slowed gut?', a:'They block acetylcholine, the parasympathetic transmitter that drives salivation and motility', exp:'Blocking rest-and-digest signals dries the mouth and slows the bowel.'},
  {q:'How does a high-fat meal affect gastric emptying?', a:'It slows emptying because fat triggers CCK, which delays the stomach', exp:'The delay gives time to digest and absorb the fat.'},
  {q:'What two substances do gastric parietal cells secrete?', a:'Gastric acid and intrinsic factor', exp:'One digests and sterilizes; the other lets you absorb B12.'},
  {q:'Why is intrinsic factor essential?', a:'It is required to absorb vitamin B12 in the ileum', exp:'No intrinsic factor means no B12 absorption.'},
  {q:'What anemia results from loss of intrinsic factor?', a:'Pernicious anemia from B12 malabsorption', exp:'Damaged parietal cells cut both acid and B12 uptake.'},
  {q:'What is the job of pancreatic bicarbonate?', a:'It neutralizes stomach acid entering the duodenum', exp:'Neutral pH protects the lining and lets enzymes work.'},
  {q:'What happens in the duodenum if pancreatic bicarbonate is decreased?', a:'The duodenum stays too acidic, impairing enzymes and injuring the mucosa', exp:'Enzymes need a neutral environment to function.'},
  {q:'What is the role of bile in fat digestion?', a:'It emulsifies fat into smaller droplets so lipase can digest it', exp:'Bile physically breaks up fat; it does not chemically digest it.'},
  {q:'What two things must be intact for nutrient absorption?', a:'Working villi (surface area) and digestive juices (enzymes plus bile)', exp:'Lose either one and nutrients pass through unabsorbed.'},
  {q:'In celiac disease, what does the immune reaction to gluten do to the villi?', a:'It flattens and shortens the villi, reducing absorptive surface area', exp:'Less surface means malabsorption, diarrhea, and weight loss.'},
  {q:'How does cystic fibrosis cause fat malabsorption?', a:'Thick secretions block pancreatic ducts so enzymes cannot reach the gut', exp:'No lipase reaching the duodenum means steatorrhea.'},
  {q:'What is steatorrhea?', a:'Fatty, foul-smelling, floating stools from fat malabsorption', exp:'It signals a lack of fat digestion or absorption.'},
  {q:'What causes steatorrhea in pancreatic insufficiency?', a:'Too few pancreatic enzymes, especially lipase, leaving fat undigested', exp:'Without lipase, fat is neither digested nor absorbed.'},
  {q:'What is the core mechanism of GERD?', a:'A weak or relaxed lower esophageal sphincter lets acid reflux into the esophagus', exp:'GERD equals LES failure.'},
  {q:'Name three risk factors for GERD.', a:'Obesity, hiatal hernia, and fatty or large meals (also lying down after eating)', exp:'These increase reflux across a weak sphincter.'},
  {q:'What are the two main causes of peptic ulcer disease?', a:'H. pylori infection and NSAID use', exp:'Both break down mucosal defense against acid.'},
  {q:'How does H. pylori promote ulcers?', a:'It colonizes the gastric mucosa and disrupts the protective barrier against acid', exp:'A weakened barrier lets acid erode the lining.'},
  {q:'What is gastritis?', a:'Inflammation of the gastric mucosa, often from H. pylori, NSAIDs, or alcohol', exp:'It can precede or accompany peptic ulcer disease.'},
  {q:'What causes esophageal varices?', a:'Portal hypertension swells esophageal veins that can rupture', exp:'Rupture causes massive bright-red hematemesis.'},
  {q:'What is hematemesis and what does bright-red blood indicate?', a:'Vomiting blood; bright red means brisk or upper bleeding such as varices', exp:'Coffee-ground vomit means older, acid-exposed blood.'},
  {q:'What is melena and what does it indicate?', a:'Black, tarry stool indicating an upper GI bleed', exp:'Blood is digested on its way through the tract.'},
  {q:'Why does prolonged vomiting cause metabolic alkalosis?', a:'Loss of stomach acid (hydrogen and chloride) raises blood pH', exp:'Severe vomiting also causes fluid and electrolyte loss.'},
  {q:'Where can Crohn disease occur in the GI tract?', a:'Anywhere from mouth to anus, with skip lesions', exp:'Skip lesions are patchy areas with normal bowel between them.'},
  {q:'How deep is the inflammation in Crohn disease?', a:'Transmural (through the full bowel wall)', exp:'Full-thickness inflammation causes fistulas and strictures.'},
  {q:'Where is ulcerative colitis limited to?', a:'The colon and rectum only, in a continuous pattern', exp:'No skip lesions and no small-bowel involvement.'},
  {q:'How deep is the inflammation in ulcerative colitis?', a:'Mucosa and submucosa only (not transmural)', exp:'Superficial inflammation contrasts with Crohn.'},
  {q:'What is the classic stool in ulcerative colitis?', a:'Bloody diarrhea with urgency', exp:'Mucosal ulceration in the colon bleeds.'},
  {q:'Which IBD carries the higher colorectal cancer risk?', a:'Ulcerative colitis', exp:'It warrants surveillance colonoscopy.'},
  {q:'What is the single best distinguisher between Crohn and UC?', a:'Crohn affects any part of the GI tract with skip lesions; UC is continuous and colon-only', exp:'Location and pattern separate the two.'},
  {q:'What is the classic location of appendicitis pain?', a:'Right lower quadrant (RLQ), with fever and nausea', exp:'Pain often starts periumbilical then localizes to the RLQ.'},
  {q:'What happens if the appendix ruptures?', a:'Contents spill into the peritoneum causing peritonitis', exp:'It is a surgical emergency.'},
  {q:'What are the hallmark signs of peritonitis?', a:'Diffuse pain, a rigid (guarding) abdomen, and rebound tenderness with fever', exp:'These signal peritoneal irritation.'},
  {q:'Where is diverticulitis pain classically located?', a:'Left lower quadrant (LLQ), with fever and nausea', exp:'Inflamed colonic outpouchings (diverticula) cause it.'},
  {q:'What is diverticulosis versus diverticulitis?', a:'Diverticulosis is outpouchings of the colon wall; diverticulitis is inflammation of those pouches', exp:'The -itis means the pouches have become inflamed.'},
  {q:'What distinguishes secretory from osmotic diarrhea?', a:'Secretory diarrhea continues even when fasting; osmotic diarrhea stops with fasting', exp:'The gut actively secretes fluid in secretory diarrhea.'},
  {q:'What is the top complication of persistent large-volume diarrhea?', a:'Dehydration and electrolyte imbalance', exp:'Hypokalemia is a common result.'},
  {q:'What is IBS and how does it differ from IBD?', a:'IBS is a functional disorder with pain and altered bowel habits but no structural or inflammatory damage', exp:'IBD has real inflammation and tissue injury; IBS does not.'},
  {q:'What is the classic picture of bowel obstruction?', a:'Distension, cramping pain, vomiting, and no flatus or stool (obstipation)', exp:'Contents cannot move forward, so they back up.'},
  {q:'Name common causes of mechanical bowel obstruction.', a:'Adhesions, hernia, and tumor', exp:'Any of these can physically block the lumen.'},
  {q:'What is a feared complication of bowel obstruction?', a:'Bowel ischemia and perforation leading to peritonitis', exp:'Cut-off blood flow kills the bowel wall.'},
  {q:'What is intussusception?', a:'One bowel segment telescopes into another, causing obstruction and compromised blood flow', exp:'It classically produces currant-jelly stools in a child.'},
  {q:'What are currant-jelly stools and what condition do they suggest?', a:'Stools of blood and mucus suggesting intussusception', exp:'Ischemia from telescoping bowel produces them.'},
  {q:'What is the defect in Hirschsprung disease?', a:'Absent ganglion (nerve) cells in a distal colon segment', exp:'No nerves means no peristalsis in that segment.'},
  {q:'Why does Hirschsprung disease cause constipation from birth?', a:'The aganglionic segment cannot relax or propel stool, causing functional obstruction', exp:'The bowel is present but cannot move contents.'},
  {q:'What causes pre-hepatic (hemolytic) jaundice?', a:'Excessive RBC breakdown produces more unconjugated bilirubin than the liver can process', exp:'Overproduction overwhelms the liver.'},
  {q:'What causes hepatic jaundice?', a:'Damaged liver cells cannot process or conjugate bilirubin', exp:'The processing step itself fails.'},
  {q:'What causes post-hepatic (obstructive) jaundice?', a:'Blocked bile flow backs up conjugated bilirubin', exp:'A stone or tumor obstructs the bile ducts.'},
  {q:'What is the classic triad of cholestasis (obstructive jaundice)?', a:'Yellow skin, dark urine, and pale stools', exp:'Bilirubin cannot reach the gut, so stools lose color.'},
  {q:'Why does cholestasis cause pruritus (itching)?', a:'Bile salts deposit in the skin', exp:'Backed-up bile components irritate the skin.'},
  {q:'What is cirrhosis?', a:'Fibrosis and scarring that replaces functional liver tissue after chronic injury', exp:'Scar tissue cannot do the liver work.'},
  {q:'Name three causes of cirrhosis.', a:'Alcohol, hepatitis, and fatty liver disease', exp:'All cause repeated inflammation and scarring.'},
  {q:'What is hepatitis?', a:'Inflammation of the liver from viruses (A, B, C), alcohol, drugs, or autoimmune causes', exp:'Chronic hepatitis can progress to cirrhosis.'},
  {q:'How is hepatitis A transmitted versus hepatitis B and C?', a:'Hepatitis A is fecal-oral; hepatitis B and C spread through blood and body fluids', exp:'B and C can become chronic and cause cirrhosis.'},
  {q:'What is portal hypertension?', a:'High pressure in the portal system when scarring blocks blood flow through the liver', exp:'Back-pressure builds in portal vessels.'},
  {q:'What three findings result from portal hypertension?', a:'Esophageal varices, splenomegaly, and ascites', exp:'Back-pressure diverts and pools blood.'},
  {q:'What two factors cause ascites in liver failure?', a:'High portal pressure and low albumin (low oncotic pressure)', exp:'Pressure pushes fluid out and low albumin fails to hold it in.'},
  {q:'Why do patients with cirrhosis bruise and bleed easily?', a:'The damaged liver makes fewer clotting factors', exp:'Most clotting factors are synthesized by the liver.'},
  {q:'What causes cholelithiasis and cholecystitis?', a:'Gallstones block bile flow and inflame the gallbladder', exp:'Fat triggers contraction against the stone.'},
  {q:'What is the classic pain pattern of gallstones/cholecystitis?', a:'RUQ pain after fatty meals, with fever and nausea', exp:'Fat triggers gallbladder contraction via CCK.'},
  {q:'What is the mechanism of pancreatitis?', a:'Pancreatic enzymes activate inside the pancreas and autodigest it', exp:'The organ digests itself, causing intense inflammation.'},
  {q:'What is the classic pain of pancreatitis?', a:'Severe epigastric pain often radiating to the back, with nausea', exp:'The pain reflects autodigestion and inflammation.'},
  {q:'What are the two most common causes of pancreatitis?', a:'Gallstones and alcohol', exp:'Both can trigger premature enzyme activation.'},
  {q:'What is the defect in pyloric stenosis?', a:'Thickened pyloric muscle obstructs the gastric outlet', exp:'It causes projectile vomiting in an infant.'},
  {q:'Why is vomiting in pyloric stenosis non-bilious?', a:'The obstruction is above where bile enters the gut', exp:'No bile reaches the stomach contents.'},
  {q:'What is necrotizing enterocolitis (NEC) and its classic picture?', a:'Bowel inflammation and ischemia in a premature infant with distension, feeding intolerance, and bloody stools', exp:'It is a GI emergency in preemies.'},
  {q:'Why does cleft palate cause feeding difficulty?', a:'The palate opening prevents effective suction during feeding', exp:'Poor intake leads to poor weight gain.'},
  {q:'A patient with damaged parietal cells has decreased acid. What else is impaired?', a:'Vitamin B12 absorption from loss of intrinsic factor', exp:'Parietal cells make both acid and intrinsic factor.'},
  {q:'A patient with celiac disease has iron and B12 deficiency. Why?', a:'Flattened villi reduce the surface area needed to absorb nutrients', exp:'Malabsorption affects iron, B12, and other nutrients.'}
];
