window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["14"]=[
  {q:'What cells break down bone and what cells build bone?', a:'Osteoclasts break down (resorb) bone; osteoblasts build it', exp:'Bone is living tissue in constant remodeling.'},
  {q:'What is the core defect in osteoporosis?', a:'Loss of bone mass/density (resorption exceeds formation)', exp:'Both matrix and mineral are reduced.'},
  {q:'What are typical serum calcium levels in osteoporosis?', a:'Normal', exp:'Osteoporosis is too little bone, not a mineral lab problem.'},
  {q:'Name the classic fragility fracture sites in osteoporosis.', a:'Hip, wrist, and vertebral compression fractures', exp:'Porous bone fails under everyday loads.'},
  {q:'Why does osteoporosis cause height loss and kyphosis?', a:'Weak porous vertebrae collapse under normal load', exp:'Vertebral compression fractures curve the upper spine forward.'},
  {q:'Which patients are at highest risk for osteoporosis?', a:'Postmenopausal and elderly patients', exp:'Estrogen loss accelerates bone resorption.'},
  {q:'What is the defect in osteomalacia?', a:'Inadequate mineralization of newly formed bone', exp:'The matrix forms but does not harden properly.'},
  {q:'What deficiency most often causes osteomalacia?', a:'Vitamin D deficiency', exp:'Vitamin D is needed to mineralize bone matrix.'},
  {q:'How does osteoporosis differ from osteomalacia?', a:'Osteoporosis = too little bone (normal mineralization); osteomalacia = poorly mineralized soft bone', exp:'Scarce vs soft bone.'},
  {q:'What protein is defective in osteogenesis imperfecta?', a:'Type I collagen', exp:'A genetic collagen defect makes bone brittle.'},
  {q:'What eye finding is classic for osteogenesis imperfecta?', a:'Blue sclerae', exp:'Thin collagen lets the underlying choroid show through.'},
  {q:'What is the very first step of indirect fracture healing?', a:'Hematoma (blood clot) formation at the fracture site', exp:'Bleeding forms the scaffold for later callus.'},
  {q:'Put fracture healing in order after the hematoma.', a:'Soft (fibrocartilage) callus, then hard (bony) callus, then remodeling', exp:'Callus bridges the gap before final reshaping.'},
  {q:'What is the mechanism of compartment syndrome?', a:'Swelling/bleeding in a closed fascial compartment raises pressure and limits perfusion, causing ischemia', exp:'Rising pressure cuts off blood flow to tissue.'},
  {q:'What is the red-flag symptom of compartment syndrome?', a:'Pain out of proportion, unrelieved by analgesia', exp:'It signals ischemia before permanent damage.'},
  {q:'What are the classic 6 Ps of compartment syndrome?', a:'Pain, pallor, paresthesia, pulselessness, paralysis, poikilothermia', exp:'Pulselessness is a very late sign.'},
  {q:'What substance released in rhabdomyolysis damages the kidneys?', a:'Myoglobin', exp:'It precipitates in and obstructs renal tubules.'},
  {q:'What urine color and lab elevation suggest rhabdomyolysis?', a:'Dark/tea-colored urine with elevated creatine kinase (CK)', exp:'Damaged muscle leaks CK and myoglobin.'},
  {q:'What dangerous electrolyte abnormality accompanies rhabdomyolysis?', a:'Hyperkalemia', exp:'Broken muscle dumps potassium, risking dysrhythmias.'},
  {q:'What is the mechanism of fat embolism syndrome?', a:'Fat from long-bone marrow enters the circulation', exp:'A complication of long-bone or pelvic fractures.'},
  {q:'What is the mechanism of osteoarthritis (OA)?', a:'Wear-and-tear breakdown/degeneration of articular cartilage over time', exp:'Mechanical, not inflammatory, damage.'},
  {q:'Which joints and symptom pattern typify osteoarthritis?', a:'Weight-bearing joints, worse with use, brief (under 30 min) morning stiffness, asymmetric', exp:'Mechanical stress drives the damage.'},
  {q:'What is the mechanism of rheumatoid arthritis (RA)?', a:'Autoimmune synovial inflammation forming a pannus that destroys the joint', exp:'The immune system attacks the synovium.'},
  {q:'How does RA joint involvement differ from OA?', a:'RA is symmetric, involves small joints, has prolonged morning stiffness, and is systemic', exp:'Autoimmune inflammation vs mechanical wear.'},
  {q:'What causes joint inflammation in gout?', a:'Uric acid (urate) crystal deposition in the joint', exp:'Crystals trigger intense acute inflammation.'},
  {q:'What is the classic joint affected first in gout?', a:'The great toe (first metatarsophalangeal joint)', exp:'Sudden severe pain, redness, and swelling.'},
  {q:'What is the mechanism of septic arthritis?', a:'Bacterial infection in the joint; enzymes and inflammation destroy cartilage', exp:'A hot joint plus fever is an emergency.'},
  {q:'What triad signals septic arthritis?', a:'A hot, swollen, painful joint plus fever', exp:'It requires urgent drainage and antibiotics.'},
  {q:'What protein is absent in Duchenne muscular dystrophy?', a:'Dystrophin', exp:'Its loss leaves muscle membranes fragile.'},
  {q:'What is the inheritance pattern of Duchenne muscular dystrophy?', a:'X-linked recessive', exp:'It almost always affects boys.'},
  {q:'Why does Duchenne weakness progressively worsen?', a:'Fibers break down faster than they can be repaired and are replaced by fat/fibrosis', exp:'Progressive fiber loss steadily reduces strength.'},
  {q:'What is Gowers sign?', a:'Using the hands to walk up the legs to stand, seen in Duchenne', exp:'It reflects proximal muscle weakness.'},
  {q:'What is calf pseudohypertrophy in Duchenne?', a:'Enlarged calves from fat and fibrosis replacing muscle', exp:'The muscle looks big but is weak.'},
  {q:'Why is creatine kinase (CK) elevated in Duchenne?', a:'Damaged muscle fibers leak CK into the blood', exp:'It is a marker of ongoing muscle breakdown.'},
  {q:'What is the mechanism of spinal muscular atrophy (SMA)?', a:'Motor neuron degeneration removes nerve input to muscle', exp:'Muscles lose their signal and atrophy.'},
  {q:'What is the difference between a strain and a sprain?', a:'A strain injures a muscle or tendon; a sprain injures a ligament', exp:'Both are overstretch/tear injuries.'},
  {q:'What does a severe (complete) sprain cause?', a:'Full ligament tear with joint instability', exp:'The joint loses its passive support.'},
  {q:'What is the mechanism of developmental dysplasia of the hip (DDH)?', a:'A shallow acetabulum does not securely hold the femoral head', exp:'The socket is too shallow to stabilize the ball.'},
  {q:'What is the deformity in clubfoot (talipes equinovarus)?', a:'The foot is held in an abnormal inward and downward position', exp:'A congenital positional deformity.'},
  {q:'What is the mechanism of Legg-Calve-Perthes disease?', a:'Loss of blood supply to the femoral head causing avascular necrosis', exp:'A perfusion problem, then re-ossification.'},
  {q:'When does scoliosis tend to progress fastest?', a:'During the rapid adolescent growth spurt', exp:'Uneven skeletal growth accelerates the curve.'},
  {q:'What is the mechanism of Osgood-Schlatter disease?', a:'Repetitive patellar tendon traction on the tibial tubercle growth area', exp:'Causes pain and swelling below the knee.'},
  {q:'What is the mechanism of Sever disease?', a:'Repetitive Achilles tendon traction on the calcaneal (heel) growth area', exp:'Traction apophysitis of the heel.'},
  {q:'What is osteomyelitis?', a:'Infection of the bone, often spread through the blood', exp:'Presents with fever and localized bone pain.'},
  {q:'What signs suggest osteomyelitis or joint infection in a child?', a:'Fever, severe localized pain, swelling, and refusal to bear weight', exp:'These warrant urgent evaluation.'},
  {q:'What is juvenile idiopathic arthritis (JIA)?', a:'Chronic autoimmune joint inflammation in children', exp:'The pediatric counterpart of autoimmune arthritis.'},
  {q:'What is Ewing sarcoma?', a:'A malignant bone tumor of children and adolescents', exp:'A primary pediatric bone cancer.'},
  {q:'What finding raises concern for nonaccidental trauma?', a:'Fractures at multiple stages of healing or injuries inconsistent with the reported story/development', exp:'The pattern does not fit the history.'},
  {q:'Why do burns cause early edema and hypotension?', a:'Increased capillary permeability shifts fluid out of vessels into tissues', exp:'This is burn (hypovolemic) shock.'},
  {q:'How does UV exposure raise skin cancer risk?', a:'UV damages cellular DNA, promoting mutations and cancer', exp:'It also causes sunburn and photoaging.'},
  {q:'Why does skin tan after sun exposure?', a:'Melanocytes make more melanin as a protective response', exp:'Melanin absorbs UV to shield DNA.'},
  {q:'What is the mechanism and appearance of cellulitis?', a:'Bacterial infection of dermis/subcutaneous tissue causing warm, swollen, spreading diffuse redness and tenderness', exp:'It spreads through soft tissue, unlike bordered lesions.'},
  {q:'What characterizes atopic dermatitis (eczema)?', a:'Chronic, relapsing inflammation with redness, swelling, and itching, often from allergy/barrier dysfunction', exp:'Common and recurrent in children.'},
  {q:'What is the mechanism of psoriasis?', a:'Chronic immune-mediated keratinocyte hyperproliferation', exp:'Skin cells overproduce and pile up.'},
  {q:'Where do psoriasis plaques classically appear?', a:'Thick, raised, scaly plaques on elbows, knees, and scalp', exp:'Extensor surfaces are typical.'},
  {q:'What is the mechanism of a pressure injury?', a:'Sustained pressure limits perfusion, causing ischemia and necrosis over bony areas', exp:'Always pressure to ischemia to necrosis.'},
  {q:'Which body sites are highest risk for pressure injuries?', a:'Bony prominences like the sacrum, heels, and hips in immobile patients', exp:'Bone compresses tissue against a surface.'},
  {q:'Why do diabetic wounds heal poorly?', a:'Poor perfusion, neuropathy, and high glucose impair healing', exp:'These combine into chronic non-healing wounds.'},
  {q:'What causes herpes zoster (shingles)?', a:'Reactivation of latent varicella-zoster virus', exp:'The same virus that caused chickenpox.'},
  {q:'What is the classic distribution of shingles?', a:'Painful vesicles in a single dermatome that do not cross the midline', exp:'The virus travels along one sensory nerve.'},
  {q:'What commonly triggers shingles reactivation?', a:'Stress or a drop in immune function', exp:'Latent virus reactivates when immunity dips.'},
  {q:'What is the hallmark of varicella (chickenpox) lesions?', a:'Itchy vesicles in multiple stages at once (papules, vesicles, crusts)', exp:'Different stages appear simultaneously.'},
  {q:'What virus causes fifth disease and what is its hallmark?', a:'Parvovirus B19; a slapped-cheek red face followed by a lacy rash on arms/trunk', exp:'Erythema infectiosum.'},
  {q:'What causes impetigo and what is its hallmark lesion?', a:'Staph/Strep bacteria entering minor skin breaks; honey-colored crusted weeping lesions', exp:'Often around the mouth and nose.'},
  {q:'What causes epidermal peeling in staphylococcal scalded-skin syndrome?', a:'Staph exfoliative toxin that weakens connections between epidermal cells', exp:'The toxin disrupts cell-to-cell adhesion.'},
  {q:'What causes scabies and its key symptom?', a:'A mite burrowing in the skin causing intense itching, worse at night, spreading among close contacts', exp:'Household clustering is a clue.'},
  {q:'What organism causes oral thrush and its appearance?', a:'Candida (fungus); white patches in the mouth', exp:'Seen in infants and immunosuppressed patients.'},
  {q:'What is the mechanism of miliaria (heat rash)?', a:'Blocked sweat ducts trap perspiration', exp:'Produces small bumps in hot, humid conditions.'},
  {q:'What causes tinea (ringworm) and its appearance?', a:'A fungal infection producing ring-shaped scaly patches; scalp hair loss in tinea capitis', exp:'Dermatophytes invade keratin.'},
  {q:'Why does aging skin become dry and thin?', a:'Aging reduces oil/moisture production and thins the skin', exp:'Less sebum and thinner dermis lead to dryness.'}
];
