window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["2"]=[
  {q:'What three features define adaptive immunity compared with innate immunity?', a:'Slow, specific, and has memory.', exp:'Memory is why re-exposure is met within hours instead of days.'},
  {q:'Which arm of adaptive immunity handles extracellular threats like bacteria in the blood and toxins?', a:'Humoral (B-cell) immunity via antibodies.', exp:'Antibodies neutralize pathogens before they get inside cells.'},
  {q:'Which arm of adaptive immunity handles intracellular pathogens and tumor cells?', a:'Cell-mediated (T-cell) immunity.', exp:'CD8 cells kill infected cells directly; CD4 cells coordinate.'},
  {q:'Where do T cells mature and where do B cells mature?', a:'T cells in the Thymus; B cells in the Bone marrow.', exp:'The first letter of each cell matches its maturation site.'},
  {q:'What is the main job of a CD4 T helper cell?', a:'Coordinates the response: secretes cytokines and activates B and CD8 cells.', exp:'CD4 cells are the conductors of the adaptive orchestra.'},
  {q:'How do CD8 cytotoxic T cells kill infected and tumor cells?', a:'By releasing perforin and granzyme.', exp:'Perforin punches holes; granzyme triggers apoptosis.'},
  {q:'What is a plasma cell and what does it do?', a:'A terminally differentiated B cell that mass-produces antibody.', exp:'It is the antibody factory pumping out IgG for days.'},
  {q:'What does the mnemonic MADGE stand for?', a:'The five immunoglobulin classes: IgM, IgA, IgD, IgG, IgE.', exp:'Five classes, one easy word to remember them.'},
  {q:'Which immunoglobulin is the first to appear and the best complement activator?', a:'IgM.', exp:'It is a pentamer, so rising IgM suggests acute or recent infection.'},
  {q:'Which immunoglobulin is most abundant and crosses the placenta?', a:'IgG.', exp:'High IgG signals past exposure or vaccination and gives long-term memory.'},
  {q:'Which immunoglobulin protects mucosal surfaces in saliva, tears, and breast milk?', a:'IgA.', exp:'Recurrent sinus and GI infections point to IgA deficiency.'},
  {q:'Which immunoglobulin binds mast cells and mediates allergy and anaphylaxis?', a:'IgE.', exp:'IgE also fights parasitic infections.'},
  {q:'Which immunoglobulin serves as the B-cell receptor on naive B cells?', a:'IgD.', exp:'Its role is poorly understood and it is rarely tested clinically.'},
  {q:'Define active immunity.', a:'Your own cells mount a response; slow onset but long-lasting with memory.', exp:'Surviving infection and vaccination both produce it.'},
  {q:'Define passive immunity.', a:'Pre-formed antibodies given to you; immediate, short-lived, and no memory.', exp:'Because no memory forms, protection fades in weeks to months.'},
  {q:'A newborn protected by maternal IgG across the placenta has what kind of immunity?', a:'Natural passive immunity.', exp:'The antibody was received, not made, so no memory results.'},
  {q:'IVIG, rabies immunoglobulin, and antivenom are examples of what immunity?', a:'Artificial passive immunity.', exp:'Pre-formed antibody is given for immediate but temporary protection.'},
  {q:'The rule given equals passive means what for immunity type?', a:'If a patient received pre-formed antibody, it is passive with no memory.', exp:'If the patient made the antibody, it is active with memory.'},
  {q:'How does a live attenuated vaccine work and who must avoid it?', a:'Uses a weakened live pathogen; avoid in immunocompromised and pregnant patients.', exp:'Even a weakened live virus can disseminate when T cells are absent.'},
  {q:'Name three live attenuated vaccines.', a:'MMR, varicella, and oral polio (also BCG, yellow fever).', exp:'These are contraindicated in SCID and other immunocompromised states.'},
  {q:'How does an mRNA vaccine work?', a:'A lipid nanoparticle delivers mRNA so the cell makes the antigen.', exp:'It contains no live virus and does NOT integrate into your DNA.'},
  {q:'What defines hypersensitivity?', a:'An immune response that harms the host.', exp:'The four Gell and Coombs types are grouped by mechanism, not symptom.'},
  {q:'What does the mnemonic ACID stand for in hypersensitivity?', a:'Allergic, Cytotoxic, Immune complex, Delayed (types I-IV).', exp:'It maps the four types in order by their driver.'},
  {q:'What drives a Type I hypersensitivity reaction and how fast is it?', a:'IgE on mast cells; onset within minutes.', exp:'Anaphylaxis, allergic rhinitis, and atopic asthma are examples.'},
  {q:'What happens on the second allergen exposure in Type I hypersensitivity?', a:'Allergen cross-links IgE, mast cells degranulate, releasing histamine and leukotrienes.', exp:'This causes bronchoconstriction, vasodilation, and capillary leak.'},
  {q:'What are the three key features of anaphylaxis?', a:'Airway constriction, hypotension from vasodilation, and urticaria/angioedema.', exp:'It is systemic Type I hypersensitivity and is life-threatening.'},
  {q:'What is the first-line treatment for anaphylaxis?', a:'IM epinephrine.', exp:'Alpha causes vasoconstriction, beta-1 boosts output, beta-2 dilates bronchi.'},
  {q:'What drives a Type II hypersensitivity reaction?', a:'IgG or IgM binding an antigen on a cell surface.', exp:'This triggers complement lysis, phagocytosis, NK killing, or altered receptor function.'},
  {q:'Which hypersensitivity type is an ABO transfusion reaction?', a:'Type II cytotoxic.', exp:'Anti-A or anti-B antibodies lyse the wrong-type RBCs within minutes.'},
  {q:'By what mechanism does hemolytic disease of the newborn occur?', a:'Sensitized Rh-negative mom makes IgG anti-Rh that crosses the placenta and attacks fetal RBCs.', exp:'RhoGAM prevents the initial maternal sensitization.'},
  {q:'Graves disease is which hypersensitivity type and mechanism?', a:'Type II by receptor stimulation; IgG activates the TSH receptor.', exp:'The result is hyperthyroidism from a thyroid driven to overproduce hormone.'},
  {q:'Myasthenia gravis is which hypersensitivity type and mechanism?', a:'Type II by receptor blockade; IgG blocks ACh receptors at the NMJ.', exp:'This causes fatigable muscle weakness that worsens with use.'},
  {q:'What causes rheumatic fever after strep infection?', a:'Molecular mimicry; antibodies to strep M protein cross-react with heart, joints, and brain.', exp:'It is a Type II autoimmune reaction triggered by infection.'},
  {q:'Which hypersensitivity type is hyperacute transplant rejection?', a:'Type II from preformed recipient antibodies against donor HLA or ABO.', exp:'The graft turns pale and nonfunctioning within minutes of reperfusion.'},
  {q:'What drives a Type III hypersensitivity reaction?', a:'Soluble antigen-antibody immune complexes that deposit in tissues.', exp:'They lodge in kidneys, joints, and skin, activating complement and neutrophils.'},
  {q:'How long does a Type III hypersensitivity reaction take to develop?', a:'About 1 to 3 weeks.', exp:'Serum sickness and post-strep glomerulonephritis fit this delayed window.'},
  {q:'Which hypersensitivity type is lupus nephritis in SLE?', a:'Type III immune complex.', exp:'Anti-dsDNA complexes deposit in glomeruli causing proteinuria and hematuria.'},
  {q:'On immunofluorescence, what does a granular deposit pattern indicate?', a:'Immune complexes, meaning Type III hypersensitivity.', exp:'A linear pattern instead suggests Type II anti-GBM disease (Goodpasture).'},
  {q:'What drives a Type IV hypersensitivity reaction?', a:'Sensitized T cells releasing cytokines; no antibody is involved.', exp:'It develops slowly over 24-72 hours as T cells migrate and activate.'},
  {q:'A positive PPD (TB skin test) is which hypersensitivity type?', a:'Type IV, delayed T-cell mediated.', exp:'Firm induration appears at 48-72 hours in a TB-sensitized person.'},
  {q:'Poison ivy contact dermatitis is which hypersensitivity type?', a:'Type IV, delayed T-cell mediated.', exp:'Students wrongly guess Type I, but there is no IgE and onset is 48-72 hours.'},
  {q:'What is the timing and mechanism of acute transplant rejection?', a:'Days to months; Type IV, recipient T cells attack donor cells.', exp:'It usually responds to increased immunosuppression.'},
  {q:'What is autoimmunity?', a:'The immune system attacking the body\'s own tissue after failing to distinguish self from non-self.', exp:'Most autoimmune diseases are a hypersensitivity type II, III, or IV against a tissue.'},
  {q:'How does molecular mimicry break immune tolerance?', a:'A pathogen antigen resembles a self-antigen, so cross-reacting antibodies attack self.', exp:'Rheumatic fever after strep is the classic example.'},
  {q:'What antibodies are characteristic of SLE?', a:'Anti-dsDNA and anti-Sm antibodies.', exp:'These form the immune complexes that deposit in glomeruli and skin.'},
  {q:'What happens to complement levels during an active SLE flare?', a:'C3 and C4 fall (low complement).', exp:'Immune complexes consume complement as the cascade is activated.'},
  {q:'Contrast Graves and Hashimoto by mechanism and result.', a:'Graves: IgG stimulates TSH-R (Type II, hyper); Hashimoto: T cells destroy gland (Type IV, hypo).', exp:'Same gland, opposite direction, opposite hypersensitivity type.'},
  {q:'What is the target and mechanism in Goodpasture syndrome?', a:'Anti-GBM antibodies (Type II, linear deposits) attack lung and kidney basement membrane.', exp:'It presents with hemoptysis plus hematuria.'},
  {q:'Which hypersensitivity type is multiple sclerosis?', a:'Type IV; T cells demyelinate CNS myelin.', exp:'It causes relapsing neuro deficits across time and space.'},
  {q:'Difference between primary and secondary immunodeficiency?', a:'Primary is congenital and usually genetic; secondary is acquired from another cause.', exp:'Primary appears in childhood; the top secondary cause worldwide is HIV/AIDS.'},
  {q:'What is the most common primary immunodeficiency and how does it present?', a:'Selective IgA deficiency, with recurrent sinus and GI infections.', exp:'These patients can have anaphylaxis to blood products containing IgA.'},
  {q:'Describe X-linked (Bruton) agammaglobulinemia.', a:'BTK mutation, no mature B cells, low or absent all immunoglobulins.', exp:'Boys get recurrent bacterial infections after 6 months as maternal IgG wanes.'},
  {q:'What does CATCH-22 stand for in DiGeorge syndrome?', a:'Cardiac defects, Abnormal facies, Thymic aplasia, Cleft palate, Hypocalcemia (chr 22q11.2).', exp:'Thymic aplasia causes T-cell deficiency; parathyroid loss causes tetany.'},
  {q:'What is defective in SCID and what is a deadly risk?', a:'Both T and B cells; live vaccines can cause fatal disseminated infection.', exp:'Infants show failure to thrive, chronic diarrhea, and profound lymphopenia.'},
  {q:'Recurrent Neisseria infections with normal antibodies suggest what defect?', a:'Late complement deficiency (C5-C9).', exp:'The membrane attack complex is needed to lyse Neisseria.'},
  {q:'Recurrent pyogenic bacteria versus opportunistic viruses and fungi point to which arms?', a:'Pyogenic bacteria = B-cell/antibody defect; opportunistic = T-cell defect.', exp:'The infection pattern tells you which arm of immunity is broken.'},
  {q:'How does HIV enter and destroy helper T cells?', a:'gp120 binds the CD4 receptor, letting the retrovirus integrate into the host genome.', exp:'Over years the CD4 count drops until AIDS develops.'},
  {q:'What CD4 count or condition defines AIDS?', a:'CD4 below 200/mm3 OR an AIDS-defining illness.', exp:'The 200 cutoff applies regardless of symptoms.'},
  {q:'What actually kills AIDS patients if not the virus itself?', a:'Opportunistic infections such as PCP, cryptococcus, and CMV.', exp:'HIV depletes CD4 cells; the resulting infections cause death.'},
  {q:'Why must splenectomized patients get pneumococcal, meningococcal, and H. flu vaccines?', a:'The spleen defends against encapsulated organisms; without it those infections are deadly.', exp:'Functional asplenia in sickle cell disease carries the same risk.'},
  {q:'List the four stages of clinical infection in order.', a:'Incubation, Prodromal, Illness (acute), Convalescence.', exp:'Patients are often contagious well before the illness stage.'},
  {q:'Why is the prodromal stage a public-health concern?', a:'Patients are highly contagious while having only vague early symptoms.', exp:'They spread disease because they do not yet know they are sick.'},
  {q:'Give the memory split for exotoxin versus endotoxin.', a:'Exo = excreted, Gram-positive, heat-labile, often vaccine-preventable; Endo = inside wall, Gram-negative, LPS, heat-stable.', exp:'Toxoid vaccines exist for exotoxins but not endotoxin.'},
  {q:'In Gram-negative septic shock, which toxin causes the hypotension?', a:'Lipopolysaccharide (LPS) endotoxin.', exp:'LPS drives TNF-alpha and IL-1 release, causing vasodilation and capillary leak.'},
  {q:'How does chronic psychological stress suppress immunity?', a:'HPA axis activation raises cortisol, which suppresses lymphocytes and antibodies.', exp:'The result is more infections, slow healing, and viral reactivation.'},
  {q:'Contrast the immune effect of acute versus chronic stress.', a:'Acute stress is mildly immune-boosting; chronic stress is immunosuppressive.', exp:'Only sustained cortisol elevation impairs host defense.'},
  {q:'Why does wound healing slow under chronic stress?', a:'Cortisol suppresses fibroblasts, reduces collagen synthesis, and dampens inflammation.', exp:'A chronically stressed surgical patient heals more slowly.'},
  {q:'Why does a patient on chronic prednisone develop shingles?', a:'Steroids suppress T-cell surveillance, letting latent VZV reactivate.', exp:'T cells normally hold latent viruses like VZV, HSV, and CMV in check.'},
  {q:'How does poorly controlled diabetes weaken host defense?', a:'Hyperglycemia impairs neutrophil chemotaxis and phagocytosis.', exp:'This raises infection risk and slows healing.'},
  {q:'True or false: an ABO transfusion reaction is a form of anaphylaxis.', a:'False; it is Type II cytotoxic, not IgE-mediated anaphylaxis.', exp:'Antibodies attack RBC surface antigens rather than triggering mast cells.'}
];
