window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["3"]=[
  {q:'What is cancer, in one sentence?', a:'A clone of cells from accumulated mutations that proliferates, evades death and immunity, builds blood supply, invades, and spreads.', exp:'Cancer is a multi-hit failure of growth control.'},
  {q:'Name the three gene categories that matter in cancer.', a:'Proto-oncogenes (become oncogenes), tumor suppressor genes, and DNA repair genes.', exp:'Gas pedal, brake pedal, and the mechanic.'},
  {q:'A proto-oncogene acts like which car pedal?', a:'The gas pedal — it promotes cell growth.', exp:'Oncogenes are stuck-on gas.'},
  {q:'A tumor suppressor gene acts like which car pedal?', a:'The brake pedal — it puts the brakes on cell growth.', exp:'Tumor suppressors are broken brakes in cancer.'},
  {q:'How many hits are needed to activate an oncogene?', a:'Just one allele — gain of function is dominant.', exp:'One stuck gas pedal is enough.'},
  {q:'How many hits must a tumor suppressor gene take to drive cancer?', a:'Both alleles must be lost — Knudson two-hit hypothesis (recessive at the cell level).', exp:'One good brake still stops the car.'},
  {q:'What is Knudson\'s two-hit hypothesis?', a:'Both copies of a tumor suppressor must be inactivated before its protective function is lost.', exp:'Explains why tumor suppressors are recessive at the cellular level.'},
  {q:'Why does an oncogene need one hit but a tumor suppressor needs two?', a:'Oncogene gain of function is dominant; tumor suppressor loss is recessive since one intact copy still works.', exp:'Dominant vs recessive at the cellular level.'},
  {q:'Give three examples of oncogenes.', a:'HER2 (breast), RAS (many), MYC (lymphoma), BCR-ABL (CML).', exp:'Classic gain-of-function drivers.'},
  {q:'Give three examples of tumor suppressor genes.', a:'TP53, RB1, BRCA1/2, APC.', exp:'Loss-of-function brakes.'},
  {q:'TP53 is altered in roughly what fraction of all cancers?', a:'About half of all cancers.', exp:'p53 is the most commonly mutated tumor suppressor.'},
  {q:'List four ways a proto-oncogene can be activated.', a:'Point mutation, gene amplification, chromosomal translocation, and viral insertion.', exp:'Four routes to a stuck gas pedal.'},
  {q:'Which oncogene mechanism causes HER2-positive breast cancer?', a:'Gene amplification — extra copies produce overexpressed HER2 receptor.', exp:'HER2 positive means amplified.'},
  {q:'What targeted drug blocks the HER2 receptor?', a:'Trastuzumab, an anti-HER2 monoclonal antibody.', exp:'Targets the amplified oncogene product.'},
  {q:'Which translocation creates BCR-ABL in chronic myeloid leukemia?', a:'The Philadelphia chromosome, t(9;22).', exp:'A gene moved next to an active promoter.'},
  {q:'Which repair genes are defective in Lynch syndrome?', a:'MLH1 and MSH2 (DNA mismatch repair genes).', exp:'Mismatch repair loss drives colorectal cancer.'},
  {q:'Put the stages of cancer development in order.', a:'Normal → hyperplasia → dysplasia → carcinoma in situ → invasive carcinoma → metastatic carcinoma.', exp:'Basement membrane crossing is the key milestone.'},
  {q:'What is hyperplasia?', a:'An increased number of normal-looking cells in response to a stimulus; reversible if the stimulus is removed.', exp:'More cells, still normal.'},
  {q:'What defines dysplasia?', a:'Disorganized abnormal cells with nuclear pleomorphism and high nuclear-to-cytoplasm ratio, still confined to the tissue.', exp:'Ugly cells, still inside the fence.'},
  {q:'Is dysplasia cancer?', a:'No — it is pre-cancerous and often reversible if the cause is removed.', exp:'A common misstep is calling dysplasia cancer.'},
  {q:'What is carcinoma in situ?', a:'Severely dysplastic cells filling the full epithelial thickness but not through the basement membrane — pre-invasive cancer.', exp:'The immediate precursor to invasion.'},
  {q:'Which event converts pre-invasive disease into true invasive cancer?', a:'Crossing (breaching) the basement membrane.', exp:'The defining gateway to real cancer.'},
  {q:'What enzymes let tumor cells break through the basement membrane?', a:'Matrix metalloproteinases.', exp:'They chew through the barrier.'},
  {q:'What is the difference between benign and malignant tumors?', a:'Benign tumors stay localized and do not invade or metastasize; malignant tumors invade, spread, and can be lethal.', exp:'Malignancy is defined by invasion and spread.'},
  {q:'What is metastasis?', a:'The ability of tumor cells to seed new tumors in distant tissues.', exp:'The property that makes cancer lethal.'},
  {q:'Which characteristic most directly allows a tumor to spread to distant organs?', a:'The ability to invade through the basement membrane and enter blood or lymphatic vessels.', exp:'No invasion means no metastasis.'},
  {q:'Which metastatic route is typical for most carcinomas?', a:'Lymphatic spread — to regional lymph nodes first.', exp:'Carcinomas love the lymphatics.'},
  {q:'Which metastatic route is typical for sarcomas?', a:'Hematogenous (bloodstream) spread, often to the lung.', exp:'Sarcomas take the blood highway.'},
  {q:'Name the big four hematogenous metastasis sites.', a:'Liver, lung, bone, and brain.', exp:'The classic distant-spread destinations.'},
  {q:'What is tumor angiogenesis?', a:'Formation of new blood vessels a tumor needs to grow beyond about 1 to 2 mm.', exp:'Tumors must build their own plumbing.'},
  {q:'Which factor do tumors secrete to drive angiogenesis?', a:'Vascular endothelial growth factor (VEGF).', exp:'VEGF recruits endothelial cells.'},
  {q:'How does bevacizumab fight cancer?', a:'It is an anti-VEGF drug that blocks the new-vessel signal, starving the tumor.', exp:'Cut the plumbing, stall the tumor.'},
  {q:'What is cancer cachexia?', a:'The wasting syndrome of advanced cancer — severe weight loss, muscle loss, and weakness despite adequate intake.', exp:'Wasting the body cannot eat its way out of.'},
  {q:'Which cytokines drive cancer cachexia?', a:'TNF-alpha, IL-1, and IL-6.', exp:'Inflammatory cytokines fuel the catabolic state.'},
  {q:'Why does a cachexia patient lose weight despite eating normally?', a:'Cytokine-driven hypermetabolism causes proteolysis, lipolysis, anorexia, and insulin resistance faster than food can replace.', exp:'The body is catabolic; calories alone cannot fix it.'},
  {q:'What is a paraneoplastic syndrome?', a:'A tumor effect at a distant site not from direct invasion, often via ectopic hormone or antibody production.', exp:'Remote effects, not local invasion.'},
  {q:'Which cancer classically causes SIADH via ectopic ADH?', a:'Small-cell lung cancer.', exp:'Low sodium with concentrated urine.'},
  {q:'What causes paraneoplastic hypercalcemia in squamous cell lung cancer?', a:'PTH-related peptide (PTHrP); bone destruction contributes in other cancers.', exp:'A PTH mimic raises calcium.'},
  {q:'Which cancer causes polycythemia via ectopic erythropoietin?', a:'Renal cell carcinoma.', exp:'Ectopic EPO raises red cell mass.'},
  {q:'What is the difference between a driver and a passenger mutation?', a:'Driver mutations fuel tumor growth; passenger (bystander) mutations are incidental and do not change behavior.', exp:'Only a few of many mutations actually drive cancer.'},
  {q:'What suffix names a malignant tumor of epithelial origin?', a:'-carcinoma (e.g., adenocarcinoma, squamous cell carcinoma).', exp:'Epithelial cancers are carcinomas.'},
  {q:'What suffix names a malignant tumor of connective tissue?', a:'-sarcoma (e.g., osteosarcoma, liposarcoma).', exp:'Bone, muscle, fat, cartilage cancers are sarcomas.'},
  {q:'What term names malignancies of embryonal or blast cells?', a:'-blastoma (e.g., neuroblastoma, retinoblastoma, hepatoblastoma).', exp:'Embryonal cancers of childhood.'},
  {q:'What is the difference between leukemia and lymphoma?', a:'Leukemia is a malignancy in blood/marrow; lymphoma arises in lymph nodes or lymphoid tissue.', exp:'Marrow vs node location.'},
  {q:'Name four malignant tumors that end in -oma.', a:'Lymphoma, melanoma, hepatoma (hepatocellular carcinoma), and seminoma.', exp:'Exceptions to the -oma-equals-benign rule.'},
  {q:'What does tumor grading measure?', a:'How differentiated the cells are — how closely they resemble normal tissue under the microscope.', exp:'Grade equals grossness under the scope.'},
  {q:'What does tumor staging measure?', a:'How far the cancer has spread.', exp:'Stage equals spread.'},
  {q:'What do the letters T, N, and M stand for in staging?', a:'T = tumor size/extent, N = regional node involvement, M = distant metastasis.', exp:'Combined into stages 0 through IV.'},
  {q:'How does a Grade I tumor differ from a Grade IV tumor?', a:'Grade I is well-differentiated (near normal); Grade IV is poorly differentiated/anaplastic.', exp:'Higher grade means uglier, more aggressive cells.'},
  {q:'For most cancers, which predicts prognosis better — stage or grade?', a:'Stage usually predicts prognosis better than grade.', exp:'Extent of spread outweighs microscopic appearance.'},
  {q:'What are the seven CAUTION warning signs of cancer?', a:'Change in bowel/bladder, A sore that won\'t heal, Unusual bleeding, Thickening or lump, Indigestion/swallowing trouble, Obvious change in a wart/mole, Nagging cough or hoarseness.', exp:'CAUTION is the classic ACS warning-sign mnemonic.'},
  {q:'A skin lesion or sore that will not heal is a warning sign of what?', a:'Possible cancer — one of the CAUTION warning signs.', exp:'Non-healing sores warrant evaluation.'},
  {q:'Which tumor marker is used for prostate cancer?', a:'Prostate-specific antigen (PSA).', exp:'PSA screens and monitors prostate cancer.'},
  {q:'Which tumor marker is elevated in hepatoblastoma and hepatocellular and germ cell cancers?', a:'Alpha-fetoprotein (AFP).', exp:'AFP tracks liver and germ cell tumors.'},
  {q:'Which tumor marker is used to monitor colorectal cancer?', a:'Carcinoembryonic antigen (CEA).', exp:'CEA follows colorectal cancer response and recurrence.'},
  {q:'Which tumor marker is associated with ovarian cancer?', a:'CA-125.', exp:'Used to monitor ovarian cancer treatment.'},
  {q:'Are tumor markers used mainly to diagnose or to monitor cancer?', a:'Mainly to monitor treatment response and detect recurrence, not to diagnose alone.', exp:'They lack the specificity to confirm a diagnosis by themselves.'},
  {q:'What are the three main modalities of cancer treatment?', a:'Surgery, radiation therapy, and chemotherapy (plus targeted and immunotherapy).', exp:'Cut, burn, poison — plus modern targeted agents.'},
  {q:'Why does chemotherapy cause hair loss, mouth sores, and low blood counts?', a:'It targets rapidly dividing cells, harming normal fast-dividing tissues like hair follicles, GI lining, and bone marrow.', exp:'Chemo cannot fully spare healthy rapidly-dividing cells.'},
  {q:'What is myelosuppression from chemotherapy?', a:'Bone marrow suppression causing anemia, neutropenia, and thrombocytopenia.', exp:'Low counts raise infection, bleeding, and fatigue risk.'},
  {q:'Why is neutropenic fever a medical emergency in a chemo patient?', a:'Low neutrophils cripple immune defense, so infection can progress rapidly to sepsis.', exp:'Fever plus neutropenia needs urgent antibiotics.'},
  {q:'How does targeted therapy differ from traditional chemotherapy?', a:'Targeted therapy attacks specific molecules (like HER2 or VEGF) driving the tumor, sparing more normal cells.', exp:'Precision drugs vs broad cytotoxicity.'},
  {q:'Which cancer risk factors are linked to tobacco smoking?', a:'Lung plus larynx, oral, esophageal, bladder, kidney, pancreatic, and cervical cancers.', exp:'Smoke carcinogens damage DNA at many sites.'},
  {q:'What toxic metabolite of alcohol is carcinogenic?', a:'Acetaldehyde.', exp:'It damages DNA in the liver, mouth, and esophagus.'},
  {q:'Name three cancers driven by obesity and metabolic syndrome.', a:'Endometrial, postmenopausal breast, colorectal, kidney, esophageal, pancreatic, or liver.', exp:'Inflammation, insulin, and estrogen excess.'},
  {q:'What DNA lesion does UV radiation create in skin?', a:'Pyrimidine dimers, leading to mutations in TP53 and other genes.', exp:'Cumulative UV damage drives skin cancers.'},
  {q:'How do HPV proteins E6 and E7 cause cancer?', a:'E6 inactivates p53 and E7 inactivates Rb — disabling two tumor suppressors.', exp:'Virus knocks out two brakes at once.'},
  {q:'Which infection causes hepatocellular carcinoma via chronic inflammation?', a:'Chronic hepatitis B or C → cirrhosis → cancer.', exp:'Chronic liver inflammation drives HCC.'},
  {q:'What cancer are daughters of DES-exposed mothers at risk for?', a:'Clear cell adenocarcinoma of the vagina or cervix.', exp:'A classic transplacental carcinogen.'},
  {q:'Which genes are mutated in hereditary breast and ovarian cancer syndrome?', a:'BRCA1 and BRCA2.', exp:'Autosomal dominant tumor suppressor loss.'}
];
