window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["4"]=[
  {q:'What are the four physiologic processes of nociception, in order?', a:'Transduction, transmission, perception, modulation', exp:'These four steps carry a noxious stimulus from tissue to the brain and back.'},
  {q:'Which step of nociception converts a noxious stimulus into an electrical action potential?', a:'Transduction', exp:'Tissue injury opens ion channels on nociceptors, turning stimulus into a signal.'},
  {q:'During transmission, the pain signal travels from the periphery to which structures?', a:'Peripheral nerve to dorsal horn of the spinal cord, up the spinothalamic tract to the thalamus and cortex', exp:'Transmission is the relay leg of the pain journey.'},
  {q:'Which step of nociception is the conscious awareness of pain in the cortex?', a:'Perception', exp:'Perception happens when the signal reaches the somatosensory cortex.'},
  {q:'Which step of nociception can dampen or amplify the pain signal via descending pathways?', a:'Modulation', exp:'Descending fibers release endorphins, serotonin, and norepinephrine to inhibit pain.'},
  {q:'What are nociceptors?', a:'Free nerve endings that detect noxious (tissue-damaging) mechanical, thermal, or chemical stimuli', exp:'They are the first responders of the pain system.'},
  {q:'Which two fiber types carry pain, and how do they differ?', a:'A-delta fibers carry fast, sharp, localized first pain; C fibers carry slow, dull, aching second pain', exp:'A-delta are myelinated and fast; C fibers are unmyelinated and slow.'},
  {q:'Why does A-delta fiber pain feel sharp and immediate?', a:'A-delta fibers are myelinated, so they conduct quickly via saltatory conduction', exp:'Myelin lets the fast, sharp first pain arrive almost instantly.'},
  {q:'Why does C-fiber pain feel dull, burning, and delayed?', a:'C fibers are unmyelinated, so they conduct slowly, producing aching second pain', exp:'No myelin means a slow, lingering second wave of pain.'},
  {q:'Which spinal tract carries pain and temperature to the brain?', a:'The spinothalamic tract', exp:'Pain and temperature ride the spinothalamic pathway.'},
  {q:'At what level does the spinothalamic tract decussate (cross)?', a:'Within one to two levels of entering the spinal cord (near entry, low)', exp:'Pain crosses early, so a cord lesion causes pain loss on the opposite side.'},
  {q:'What sensations does the dorsal column / medial lemniscus carry?', a:'Fine touch, vibration, proprioception, and two-point discrimination', exp:'The dorsal columns handle the discriminative touch modalities.'},
  {q:'Where does the dorsal column pathway decussate?', a:'In the medulla (high, at the level of the brainstem)', exp:'Vibration crosses late, so a cord lesion causes same-side loss.'},
  {q:'Complete the mnemonic: pain crosses ___, vibration crosses ___.', a:'Pain crosses early; vibration crosses late', exp:'Spinothalamic decussates near cord entry; dorsal columns cross at the medulla.'},
  {q:'What is the neurotransmitter released by C fibers at the dorsal horn to transmit pain?', a:'Substance P (along with glutamate)', exp:'Substance P is a key excitatory pain transmitter in the dorsal horn.'},
  {q:'What is the central premise of the gate control theory of pain?', a:'Non-painful input can close a spinal gate that blocks painful input from reaching the brain', exp:'Large touch fibers can override small pain fibers at the dorsal horn.'},
  {q:'In gate control theory, which fibers close the gate to reduce pain?', a:'Large-diameter A-beta fibers (touch, pressure, vibration)', exp:'Stimulating touch fibers inhibits pain transmission.'},
  {q:'In gate control theory, which fibers open the gate to allow pain through?', a:'Small-diameter A-delta and C pain fibers', exp:'Pain fibers open the gate; touch fibers close it.'},
  {q:'Why does rubbing an injured area make it hurt less?', a:'Rubbing stimulates large A-beta touch fibers that close the spinal gate to pain (gate control theory)', exp:'Touch input competes with and inhibits pain input at the dorsal horn.'},
  {q:'How does a TENS unit relieve pain according to gate control theory?', a:'It stimulates large touch fibers that close the spinal gate and block pain transmission', exp:'TENS is a clinical application of gate control theory.'},
  {q:'Where is the spinal gate located in gate control theory?', a:'In the dorsal horn of the spinal cord (substantia gelatinosa)', exp:'The dorsal horn is the gate where fibers compete.'},
  {q:'What is nociceptive pain?', a:'Pain from actual or threatened tissue damage detected by normally functioning nociceptors', exp:'It is the normal alarm response to injury.'},
  {q:'What are the two subtypes of nociceptive pain?', a:'Somatic and visceral', exp:'Somatic is from skin/muscle/bone; visceral is from organs.'},
  {q:'Describe somatic nociceptive pain.', a:'Sharp, throbbing, well-localized pain from skin, muscle, bone, or joints', exp:'A cut or fracture produces sharp, localized somatic pain.'},
  {q:'Describe visceral nociceptive pain.', a:'Dull, aching, poorly localized pain from stretch or distension of internal organs; may refer', exp:'Organ pain is vague and hard to pinpoint.'},
  {q:'Give an example of visceral pain.', a:'Appendicitis, bowel obstruction, or myocardial infarction pain', exp:'Distended or ischemic organs generate visceral pain.'},
  {q:'What is neuropathic pain?', a:'Pain caused by damage to or dysfunction of the peripheral or central nervous system itself', exp:'The nerve itself is the source, not tissue injury.'},
  {q:'What words classically describe neuropathic pain?', a:'Burning, shooting, electric, tingling, or numb', exp:'Burning and shooting without a fresh injury flags neuropathic pain.'},
  {q:'Give three examples of neuropathic pain conditions.', a:'Diabetic neuropathy, post-herpetic neuralgia, sciatica, trigeminal neuralgia, or phantom limb pain', exp:'All arise from damaged or sensitized nerves.'},
  {q:'A patient describes burning, shooting foot pain with no new injury. What pain type is this?', a:'Neuropathic pain', exp:'Burning and shooting with no fresh injury is the classic neuropathic stem.'},
  {q:'What is referred pain?', a:'Visceral pain perceived at a distant somatic site that shares the same spinal cord level', exp:'The brain misattributes organ pain to a body-surface location.'},
  {q:'Why does referred pain occur?', a:'Visceral and somatic afferents converge on the same dorsal horn neurons, so the brain cannot tell them apart', exp:'Convergence causes the brain to mislocalize the source.'},
  {q:'Where does myocardial infarction pain classically refer?', a:'To the left arm, jaw, neck, or shoulder', exp:'Cardiac pain refers along shared spinal segments.'},
  {q:'Where does gallbladder pain classically refer?', a:'To the right shoulder or scapula', exp:'Diaphragmatic and phrenic nerve sharing sends it to the shoulder.'},
  {q:'What is acute pain?', a:'Pain of recent onset, usually less than 3 to 6 months, that resolves as the injury heals and serves a protective purpose', exp:'Acute pain is a useful warning signal.'},
  {q:'What is chronic pain?', a:'Pain persisting beyond the expected healing time, generally longer than 3 to 6 months', exp:'Chronic pain outlives its protective usefulness.'},
  {q:'How does the autonomic response differ between acute and chronic pain?', a:'Acute pain causes sympathetic signs (tachycardia, hypertension, diaphoresis); chronic pain patients often have normal vital signs', exp:'Chronic pain adapts, so vitals can look deceptively normal.'},
  {q:'Why can a chronic pain patient have normal vital signs despite severe pain?', a:'The body physiologically adapts to persistent pain, so autonomic signs fade over time', exp:'Absence of tachycardia does not mean absence of pain.'},
  {q:'What does the pain assessment mnemonic PQRST stand for?', a:'Provocation/Palliation, Quality, Region/Radiation, Severity, and Timing', exp:'PQRST structures a thorough pain history.'},
  {q:'What is the most reliable indicator of a patient\'s pain?', a:'The patient\'s own self-report', exp:'Pain is subjective; the patient is the authority on it.'},
  {q:'What pain scale is best for young children or nonverbal patients?', a:'The Wong-Baker FACES scale or the FLACC behavioral scale', exp:'Faces and behaviors substitute when self-report is not possible.'},
  {q:'What behavioral cues suggest pain in a nonverbal or cognitively impaired patient?', a:'Grimacing, guarding, restlessness, moaning, and changes in vital signs', exp:'Watch behavior and physiology when words are unavailable.'},
  {q:'What is pain threshold?', a:'The lowest intensity of a stimulus that is perceived as painful', exp:'Threshold is fairly consistent across people.'},
  {q:'What is pain tolerance?', a:'The maximum level or duration of pain a person is willing to endure', exp:'Tolerance varies widely and is influenced by culture and mood.'},
  {q:'What is hyperalgesia?', a:'An increased pain response to a stimulus that is normally painful', exp:'Sensitized nerves amplify painful input.'},
  {q:'What is allodynia?', a:'Pain caused by a stimulus that does not normally provoke pain, such as light touch', exp:'Allodynia is a hallmark of neuropathic sensitization.'},
  {q:'What are the two main classes of analgesics emphasized in this unit?', a:'Opioids and NSAIDs (nonsteroidal anti-inflammatory drugs)', exp:'They act at different points along the pain pathway.'},
  {q:'What is the mechanism of action of opioids?', a:'They bind mu (and kappa/delta) opioid receptors in the CNS to inhibit pain transmission and perception', exp:'Opioids act centrally at the dorsal horn and brain.'},
  {q:'Which opioid receptor is most responsible for analgesia and respiratory depression?', a:'The mu receptor', exp:'Mu agonism gives both the relief and the danger.'},
  {q:'What is the most dangerous adverse effect of opioids?', a:'Respiratory depression', exp:'Opioids blunt the brainstem response to carbon dioxide.'},
  {q:'What opioid side effect does NOT develop tolerance and must be managed long-term?', a:'Constipation', exp:'Always pair chronic opioids with a bowel regimen.'},
  {q:'What is the antidote (reversal agent) for opioid overdose?', a:'Naloxone (Narcan)', exp:'Naloxone is a competitive opioid antagonist.'},
  {q:'How does naloxone reverse opioid effects?', a:'It competitively antagonizes (blocks) opioid receptors, displacing the opioid', exp:'It knocks the opioid off the mu receptor.'},
  {q:'Name three common signs of opioid toxicity.', a:'Pinpoint (miotic) pupils, respiratory depression, and decreased level of consciousness', exp:'This triad signals dangerous opioid overdose.'},
  {q:'What is the mechanism of action of NSAIDs?', a:'They inhibit cyclooxygenase (COX) enzymes, reducing prostaglandin synthesis', exp:'Less prostaglandin means less inflammation and pain sensitization.'},
  {q:'How do prostaglandins contribute to pain?', a:'They sensitize peripheral nociceptors, lowering the threshold for pain (peripheral sensitization)', exp:'Blocking prostaglandins raises the pain threshold at the injury site.'},
  {q:'At which step of nociception do NSAIDs mainly act?', a:'Transduction (they reduce peripheral nociceptor sensitization)', exp:'NSAIDs work at the tissue where pain begins.'},
  {q:'What is a classic gastrointestinal adverse effect of NSAIDs, and why?', a:'Gastric ulcers/GI bleeding, because COX-1 inhibition reduces the prostaglandins that protect the stomach lining', exp:'Losing protective prostaglandins exposes the gastric mucosa.'},
  {q:'What is the difference between COX-1 and COX-2?', a:'COX-1 is constitutive and protects the stomach and platelets; COX-2 is induced and mediates inflammation and pain', exp:'Selective COX-2 inhibitors spare the stomach but raise cardiovascular risk.'},
  {q:'Why is acetaminophen NOT a true NSAID?', a:'It has little peripheral anti-inflammatory action and works mainly centrally; overdose causes liver toxicity', exp:'Acetaminophen relieves pain and fever without significant anti-inflammatory effect.'},
  {q:'What are endogenous opioids?', a:'Naturally produced pain-inhibiting peptides such as endorphins, enkephalins, and dynorphins', exp:'The body makes its own morphine-like modulators.'},
  {q:'What do endogenous opioids do?', a:'They bind opioid receptors to inhibit pain transmission as part of descending modulation', exp:'They are the body\'s built-in pain brake.'},
  {q:'Name the three families of endogenous opioids.', a:'Endorphins, enkephalins, and dynorphins', exp:'All bind opioid receptors to dampen pain.'},
  {q:'Which neurotransmitters are released by descending pain modulation pathways?', a:'Serotonin, norepinephrine, and endogenous opioids (endorphins/enkephalins)', exp:'These inhibit dorsal horn pain transmission from the top down.'},
  {q:'Why do tricyclic antidepressants and SNRIs help neuropathic pain?', a:'They boost serotonin and norepinephrine, strengthening descending inhibitory (modulation) pathways', exp:'They enhance the body\'s own pain-dampening circuits.'},
  {q:'Why does neuropathic pain respond poorly to opioids?', a:'It arises from abnormally firing damaged nerves, often above the level where opioids act on nociceptive signaling', exp:'Opioids target nociceptive, not neuropathic, mechanisms.'},
  {q:'Which drug classes are first-line for neuropathic pain instead of opioids?', a:'Anticonvulsants (gabapentin, pregabalin) and antidepressants (TCAs, SNRIs)', exp:'They calm hyperexcitable, misfiring nerves.'},
  {q:'How do gabapentin and pregabalin relieve neuropathic pain?', a:'They bind voltage-gated calcium channels to reduce excitatory neurotransmitter release from hyperactive nerves', exp:'They quiet the abnormal firing of damaged neurons.'},
  {q:'What is the WHO analgesic ladder principle?', a:'Step up from non-opioids (NSAIDs/acetaminophen) to weak then strong opioids as pain severity increases', exp:'It matches drug potency to pain intensity in a stepwise way.'},
  {q:'What is multimodal analgesia and why is it used?', a:'Combining drugs with different mechanisms to improve relief while lowering each drug\'s dose and side effects', exp:'Attacking pain at several points beats maxing out one drug.'}
];
