window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["5"]=[
  {q:'What percentage of strokes are ischemic vs hemorrhagic?', a:'~85% ischemic, ~15% hemorrhagic', exp:'Most strokes come from a blocked vessel, not a bleed.'},
  {q:'What is the underlying mechanism of a hemorrhagic stroke?', a:'A vessel ruptures and blood floods brain tissue', exp:'The bleed and rising pressure injure neurons.'},
  {q:'Name the three subtypes of ischemic stroke.', a:'Thrombotic, embolic, and lacunar', exp:'Thrombotic is atherosclerotic, embolic is often from AFib.'},
  {q:'Atrial fibrillation most commonly causes which type of stroke?', a:'Embolic ischemic stroke', exp:'A clot forms in the left atrium and travels to the brain.'},
  {q:'What are the two subtypes of hemorrhagic stroke?', a:'Intracerebral (HTN) and subarachnoid (aneurysm)', exp:'Hypertension and berry aneurysms are the classic causes.'},
  {q:'What does the FAST mnemonic stand for?', a:'Face drooping, Arm weakness, Speech difficulty, Time to call 911', exp:'A quick bedside screen for acute stroke.'},
  {q:'What does the phrase \'time is brain\' mean?', a:'About 2 million neurons die per minute during an ischemic stroke', exp:'Every minute of delay costs salvageable tissue.'},
  {q:'What is the tPA time window for ischemic stroke?', a:'Within 3 to 4.5 hours of last known well', exp:'Outside this window thrombolysis risk outweighs benefit.'},
  {q:'What is the single most important modifiable risk factor for stroke?', a:'Hypertension', exp:'It accelerates atherosclerosis and drives intracerebral bleeds.'},
  {q:'What is the primary reason neurons die during an ischemic stroke?', a:'Energy (ATP) failure causing ion-pump failure and excitotoxicity', exp:'Without ATP the neuron cannot maintain its ion gradients.'},
  {q:'Which ion floods the neuron and activates destructive enzymes in the cascade?', a:'Calcium (Ca2+)', exp:'Calcium overload activates enzymes that break the cell down.'},
  {q:'What is a TIA?', a:'A transient ischemic attack, a stroke-like event that resolves completely', exp:'Same mechanism as ischemic stroke but symptoms clear.'},
  {q:'By definition, how quickly do TIA symptoms resolve?', a:'Typically under 1 hour, and by definition under 24 hours', exp:'Full resolution distinguishes it from a completed stroke.'},
  {q:'Why is a TIA called a warning stroke?', a:'It signals high stroke risk soon, about 10 to 15% within 90 days', exp:'It demands aggressive prevention to avoid the next event.'},
  {q:'What is multiple sclerosis?', a:'A chronic autoimmune demyelinating disease of the CNS', exp:'T cells strip myelin from central axons.'},
  {q:'Which cells are attacked in multiple sclerosis?', a:'Oligodendrocytes, the CNS myelin-producing cells', exp:'Losing them exposes axons and slows conduction.'},
  {q:'What is often the first symptom of MS?', a:'Optic neuritis causing painful monocular vision loss', exp:'Inflammation of the optic nerve is a classic MS onset.'},
  {q:'What is the Uhthoff phenomenon in MS?', a:'Worsening of symptoms with elevated body temperature', exp:'Heat further slows conduction in demyelinated axons.'},
  {q:'Which structure loses dopamine neurons in Parkinson disease?', a:'The substantia nigra of the basal ganglia', exp:'Dopamine loss lets the basal ganglia over-inhibit movement.'},
  {q:'What are the cardinal features of Parkinson disease (TRAP)?', a:'Tremor, Rigidity, Akinesia/bradykinesia, Postural instability', exp:'The resting tremor is the classic pill-rolling type.'},
  {q:'Why is levodopa given instead of dopamine itself?', a:'Dopamine cannot cross the blood-brain barrier, but levodopa can', exp:'Levodopa is converted to dopamine inside the brain.'},
  {q:'What is a seizure?', a:'A sudden, abnormal, excessive and synchronous discharge of cortical neurons', exp:'The clinical picture depends on which cortex is firing.'},
  {q:'Describe a generalized tonic-clonic seizure.', a:'Loss of consciousness, then tonic stiffening, clonic jerking, and postictal confusion', exp:'Tongue biting and incontinence may occur.'},
  {q:'What are the features of an absence seizure?', a:'Brief staring spells of 5 to 10 seconds with no postictal phase, in children', exp:'EEG shows a 3-Hz spike-and-wave pattern.'},
  {q:'What defines status epilepticus?', a:'A seizure over 5 minutes or repeated seizures without recovery between', exp:'It is a medical emergency requiring rapid treatment.'},
  {q:'Name three common triggers of seizures.', a:'Fever, hypoglycemia, hyponatremia, alcohol withdrawal, or missed antiepileptic doses', exp:'Metabolic and withdrawal triggers are frequently tested.'},
  {q:'What is the formula for cerebral perfusion pressure?', a:'CPP = MAP minus ICP', exp:'As ICP climbs toward MAP, perfusion falls toward zero.'},
  {q:'How does rising intracranial pressure injure neurons?', a:'By direct compression and by reducing cerebral perfusion pressure, causing ischemia', exp:'Neurons starve even though large vessels stay patent.'},
  {q:'What is the Cushing triad of late ICP elevation?', a:'Hypertension, bradycardia, and irregular respirations', exp:'It is a late and ominous sign of dangerous ICP.'},
  {q:'What is the difference between primary and secondary spinal cord injury?', a:'Primary is immediate mechanical damage; secondary is a delayed cascade of edema, ischemia, and inflammation', exp:'The secondary phase enlarges the lesion over hours to days.'},
  {q:'Why is recovery from spinal cord injury slow and incomplete?', a:'Adult CNS axons do not regenerate well due to glial scarring and inhibitory molecules', exp:'PNS nerves can regrow, but CNS ones largely cannot.'},
  {q:'At what spinal level or above does neurogenic shock typically occur?', a:'T6 or above', exp:'Injury this high disrupts major sympathetic outflow.'},
  {q:'What is the mechanism of neurogenic shock?', a:'Loss of sympathetic tone below the lesion with unopposed parasympathetic activity', exp:'Vessels dilate and the heart slows.'},
  {q:'What are the classic findings of neurogenic shock?', a:'Hypotension, bradycardia, and warm, dry skin', exp:'It is the only warm shock because vasoconstriction is lost.'},
  {q:'Why is neurogenic shock the only warm shock?', a:'Sympathetic vasoconstriction is lost, so vessels dilate and skin stays warm', exp:'Other shocks show cold skin from compensatory vasoconstriction.'},
  {q:'When does autonomic dysreflexia occur after SCI?', a:'Weeks to years after an SCI at T6 or above', exp:'It is a chronic, recurrent emergency, not an acute event.'},
  {q:'What triggers autonomic dysreflexia?', a:'A noxious stimulus below the lesion, such as a full bladder or fecal impaction', exp:'The stimulus sets off a massive sympathetic surge.'},
  {q:'What are the hallmark findings of autonomic dysreflexia?', a:'Severe hypertension, pounding headache, bradycardia, and flushing above the lesion', exp:'Skin is pale and cool below the lesion.'},
  {q:'What is radiculopathy?', a:'Pain, numbness, and weakness from compression of a spinal nerve root', exp:'A herniated disk pressing a root is a classic cause.'},
  {q:'Which disk levels classically herniate to cause sciatica?', a:'L4-L5 or L5-S1', exp:'Root compression sends pain down the back of the leg.'},
  {q:'Name the red-flag findings of cauda equina syndrome.', a:'Saddle anesthesia, urinary retention, bilateral leg weakness, and loss of anal tone', exp:'They demand surgical decompression within 24 to 48 hours.'},
  {q:'What is meningitis?', a:'Inflammation of the meninges and CSF in the subarachnoid space', exp:'It is most often infectious, especially bacterial or viral.'},
  {q:'What is the classic clinical triad of meningitis?', a:'Fever, headache, and nuchal rigidity', exp:'Photophobia and altered mental status often accompany it.'},
  {q:'Which rash strongly suggests meningococcal meningitis?', a:'A petechial or purpuric rash', exp:'It signals Neisseria meningitidis and requires infection control.'},
  {q:'Describe the CSF profile of bacterial meningitis.', a:'Cloudy fluid, neutrophil predominance, low glucose, and high protein', exp:'Bacteria consume glucose, driving it down.'},
  {q:'How quickly should antibiotics be given in suspected bacterial meningitis?', a:'Within 1 hour, before LP results if suspicion is high', exp:'Give empirical IV antibiotics plus dexamethasone.'},
  {q:'Which pathogens cause meningitis in newborns under 1 month?', a:'Group B Streptococcus, E. coli, and Listeria', exp:'These reflect exposures around birth.'},
  {q:'What neurotransmitter is released at the neuromuscular junction?', a:'Acetylcholine (ACh)', exp:'It binds nicotinic receptors on the muscle membrane.'},
  {q:'What is myasthenia gravis?', a:'An autoimmune disease where antibodies block postsynaptic ACh receptors', exp:'It is a type II hypersensitivity from receptor blockade.'},
  {q:'What is the hallmark weakness pattern of myasthenia gravis?', a:'Fatigable weakness that worsens with use and improves with rest', exp:'Repeated use depletes ACh; rest restores transmission.'},
  {q:'What are often the first symptoms of myasthenia gravis?', a:'Ptosis (drooping eyelids) and diplopia (double vision)', exp:'The eyelid and eye muscles are commonly affected first.'},
  {q:'Which organ is abnormal in about 75% of myasthenia gravis patients?', a:'The thymus (hyperplasia or thymoma)', exp:'Thymectomy can improve symptoms.'},
  {q:'How does pyridostigmine help myasthenia gravis?', a:'It inhibits acetylcholinesterase, leaving more ACh in the cleft', exp:'It treats symptoms but does not fix the autoimmunity.'},
  {q:'Which antibody confirms myasthenia gravis?', a:'Anti-acetylcholine receptor (anti-AChR) antibody', exp:'EMG showing a decremental response also supports it.'},
  {q:'What is botulism and how does the toxin act?', a:'Paralysis from Clostridium botulinum toxin that blocks ACh release', exp:'The toxin cleaves SNARE proteins needed for vesicle fusion.'},
  {q:'What pattern of paralysis does botulism cause?', a:'Descending, symmetric flaccid paralysis', exp:'This is the opposite of the ascending pattern in GBS.'},
  {q:'What are the 4 D\'s of botulism?', a:'Diplopia, Dysphagia, Dysarthria, and Dysphonia', exp:'Cranial nerve signs appear before descending weakness.'},
  {q:'Why is the belief that botulism causes spasms wrong?', a:'Botulism causes flaccid paralysis because no ACh means no muscle activation', exp:'Tetanus, not botulism, causes spasms.'},
  {q:'What is hydrocephalus?', a:'Excess CSF accumulation in the ventricles', exp:'In infants it enlarges the head; in older children it raises ICP.'},
  {q:'What is the difference between communicating and non-communicating hydrocephalus?', a:'Communicating is failed absorption; non-communicating is blocked flow', exp:'Aqueductal stenosis is the top congenital obstructive cause.'},
  {q:'What are classic signs of infant hydrocephalus?', a:'Rapid head growth, bulging fontanelle, and sunset eyes', exp:'Open sutures let the head enlarge before ICP spikes.'},
  {q:'How is hydrocephalus typically treated?', a:'With early placement of a ventriculoperitoneal (VP) shunt', exp:'Early shunting prevents permanent brain injury.'},
  {q:'When does the neural tube normally close?', a:'Between weeks 3 and 4 of embryonic development', exp:'Failure of closure produces neural tube defects.'},
  {q:'What is a myelomeningocele?', a:'Protrusion of both meninges and spinal cord, causing motor and sensory deficits', exp:'It often comes with hydrocephalus and Chiari II malformation.'},
  {q:'What is anencephaly?', a:'Failure of cranial neural tube closure with absent brain development', exp:'It is incompatible with life.'},
  {q:'Why must folic acid be taken before conception?', a:'The neural tube closes at weeks 3 to 4, often before pregnancy is known', exp:'By the time pregnancy is confirmed, the window has passed.'},
  {q:'What is cerebral palsy?', a:'A non-progressive motor disorder from injury to the developing brain', exp:'The brain lesion is fixed, though the picture may evolve.'},
  {q:'What is the most common type of cerebral palsy?', a:'Spastic, with UMN signs like increased tone and scissoring gait', exp:'Hyperreflexia accompanies the spasticity.'},
  {q:'Why is the belief that cerebral palsy is progressive wrong?', a:'The brain injury is static and does not worsen', exp:'Musculoskeletal problems may evolve, but the lesion is fixed.'},
  {q:'How do GBS and botulism differ in direction of weakness?', a:'GBS ascends while botulism descends', exp:'GBS is autoimmune demyelination; botulism blocks ACh release.'}
];
