window.SCI225_CARDS=window.SCI225_CARDS||{};
window.SCI225_CARDS["6"]=[
  {q:'What is the universal rule that keeps hormones within tight ranges?', a:'Negative feedback', exp:'The final hormone shuts off the upstream hypothalamic and pituitary signals.'},
  {q:'In a hormonal axis, what does the hypothalamus release first?', a:'A releasing hormone (e.g., TRH, CRH, GnRH)', exp:'The cascade always starts at the hypothalamus.'},
  {q:'If a final hormone is high because of disease in the target gland itself, what happens to the upstream signals?', a:'They are low (feedback intact)', exp:'This is the lab signature of PRIMARY disease.'},
  {q:'If a final hormone is high because the pituitary makes too much stimulating hormone, what is the stimulating hormone level?', a:'Also high', exp:'This is the signature of SECONDARY (pituitary) disease.'},
  {q:'Name the hypothalamus, pituitary, target gland, and final hormone of the thyroid (HPT) axis.', a:'TRH, TSH, thyroid, T3/T4', exp:'TRH drives TSH drives T3/T4.'},
  {q:'Name the hypothalamus, pituitary, target, and final hormone of the adrenal (HPA) axis.', a:'CRH, ACTH, adrenal cortex, cortisol', exp:'CRH drives ACTH drives cortisol.'},
  {q:'In the gonadal (HPG) axis, which pituitary hormones does GnRH stimulate?', a:'FSH and LH', exp:'They act on the ovary or testis.'},
  {q:'In the growth axis, what does GH stimulate the liver to release?', a:'IGF-1 (somatomedin)', exp:'IGF-1 drives soft-tissue and bone growth.'},
  {q:'What mostly inhibitory hypothalamic factor controls prolactin?', a:'Dopamine', exp:'Loss of dopamine tone raises prolactin.'},
  {q:'What does the mnemonic FLAT PEG stand for?', a:'FSH, LH, ACTH, TSH, Prolactin, Endorphins, GH', exp:'These are the anterior pituitary hormones.'},
  {q:'Which two hormones does the posterior pituitary release but not make?', a:'ADH and oxytocin', exp:'They are made in the hypothalamus and stored in the posterior pituitary.'},
  {q:'What is the first step in thyroid hormone synthesis?', a:'Iodide uptake by follicular cells', exp:'Without iodine the gland cannot make hormone.'},
  {q:'Name the ordered steps of thyroid hormone synthesis after iodide uptake.', a:'Oxidation, organification, coupling, storage, release', exp:'Iodine is attached to thyroglobulin then coupled into T3/T4.'},
  {q:'Why does long-term iodine deficiency cause a goiter?', a:'Low T4 raises TSH, and TSH is a growth signal for the thyroid', exp:'Chronic TSH stimulation enlarges the gland.'},
  {q:'Goiter can occur in both hyper- and hypothyroidism because of what shared mechanism?', a:'Chronic TSH-receptor stimulation growing the gland', exp:'In Graves the auto-antibody activates the same receptor.'},
  {q:'What is the action of ADH (vasopressin) on the kidney?', a:'Acts on the collecting duct to reabsorb water', exp:'Result is concentrated urine and normal serum osmolality.'},
  {q:'What are the two actions of oxytocin?', a:'Uterine contraction at labor and milk let-down', exp:'It drives the milk-ejection reflex.'},
  {q:'Why does pituitary stalk damage cause broad anterior pituitary hormone deficiency?', a:'It interrupts portal delivery of hypothalamic releasing hormones', exp:'The pituitary becomes deaf to upstream signals (panhypopituitarism).'},
  {q:'Where is the pituitary gland located?', a:'In the sella turcica at the base of the brain, below the hypothalamus', exp:'It sits just below the optic chiasm.'},
  {q:'Describe the shape and location of the thyroid gland.', a:'Butterfly-shaped, anterior to the trachea, just below the larynx', exp:'This description is a classic anatomy-question giveaway.'},
  {q:'Besides T3 and T4, what does the thyroid secrete, and what does it do?', a:'Calcitonin, which lowers serum calcium', exp:'It opposes PTH.'},
  {q:'Where are the parathyroid glands located and how many are there?', a:'Four small glands on the posterior surface of the thyroid', exp:'They secrete PTH.'},
  {q:'What does parathyroid hormone (PTH) do to serum calcium?', a:'Raises it', exp:'PTH raises calcium; calcitonin lowers it.'},
  {q:'Where are the adrenal glands located?', a:'On top of each kidney', exp:'Above the kidney plus corticosteroids equals adrenal.'},
  {q:'What are the 3 S\'s made by the adrenal cortex?', a:'Salt (aldosterone), Sugar (cortisol), Sex (androgens)', exp:'Zones from outer to inner: glomerulosa, fasciculata, reticularis.'},
  {q:'What does the adrenal medulla produce?', a:'Epinephrine and norepinephrine', exp:'The inner medulla makes catecholamines.'},
  {q:'What structures within the pancreas contain endocrine cells?', a:'The islets of Langerhans', exp:'They house alpha, beta, and delta cells.'},
  {q:'Which pancreatic islet cells make insulin?', a:'Beta cells', exp:'Alpha cells make glucagon; delta cells make somatostatin.'},
  {q:'A tumor in the cells responsible for insulin secretion involves which structure?', a:'Beta cells of the pancreatic islets', exp:'An insulinoma causes recurrent hypoglycemia.'},
  {q:'What causes acromegaly?', a:'A pituitary adenoma secreting excess GH in adults, after epiphyses close', exp:'It widens rather than lengthens bone.'},
  {q:'What is the classic clinical picture of acromegaly?', a:'Enlarged hands, feet, jaw, and facial bones with coarse features', exp:'Also large tongue, HTN, insulin resistance, and sleep apnea.'},
  {q:'How does gigantism differ from acromegaly?', a:'Gigantism is excess GH in children before epiphyseal closure', exp:'Open growth plates cause excessive linear growth.'},
  {q:'What test result confirms acromegaly on an oral glucose suppression test?', a:'GH fails to suppress', exp:'Normally glucose suppresses GH; in acromegaly it does not.'},
  {q:'What is the classic triad caused by a prolactinoma in women?', a:'Galactorrhea, amenorrhea, and infertility', exp:'Decreased libido also occurs; men get erectile dysfunction.'},
  {q:'Which visual field defect is caused by a pituitary macroadenoma?', a:'Bitemporal hemianopsia', exp:'Upward compression of the optic chiasm loses peripheral fields in both eyes.'},
  {q:'Why does chiasm compression cause bitemporal hemianopsia?', a:'It compresses the crossing fibers carrying temporal visual fields', exp:'These come from the nasal halves of each retina.'},
  {q:'In SIADH, what is the underlying problem?', a:'Too much ADH causing excess water reabsorption', exp:'Water retention dilutes the serum.'},
  {q:'What is the serum sodium in SIADH?', a:'Low (dilutional hyponatremia)', exp:'Retained water dilutes sodium.'},
  {q:'What does the urine look like in SIADH?', a:'Concentrated (high osmolality), low volume', exp:'The kidney is holding water, so urine is concentrated.'},
  {q:'What is the classic paraneoplastic cause of SIADH?', a:'Small-cell lung cancer', exp:'The tumor secretes ectopic ADH.'},
  {q:'What is the treatment of SIADH?', a:'Fluid restriction and treating the cause', exp:'Vaptans are used for severe cases.'},
  {q:'In diabetes insipidus, what is the underlying problem?', a:'Inadequate ADH so kidneys cannot concentrate urine', exp:'Free water is lost.'},
  {q:'What is the serum sodium in diabetes insipidus?', a:'High (from free water loss)', exp:'Losing water concentrates the serum.'},
  {q:'What does the urine look like in diabetes insipidus?', a:'Dilute (low osmolality), large volume (polyuria)', exp:'The kidney cannot reabsorb water.'},
  {q:'What is the treatment for central diabetes insipidus?', a:'Desmopressin (synthetic ADH)', exp:'It replaces the missing hormone.'},
  {q:'A lung-cancer patient has Na 118, low serum osmolality, and concentrated urine. Diagnosis?', a:'SIADH (paraneoplastic from small-cell lung cancer)', exp:'Excess ADH retains water causing dilutional hyponatremia.'},
  {q:'After pituitary surgery, a patient has thirst, polyuria, hypernatremia, and dilute urine. Diagnosis?', a:'Central diabetes insipidus', exp:'Loss of ADH release prevents water reabsorption.'},
  {q:'What is Graves disease?', a:'The most common cause of hyperthyroidism, a type II hypersensitivity', exp:'IgG autoantibodies activate the TSH receptor.'},
  {q:'What is the lab pattern of Graves disease?', a:'High T3/T4, low TSH, positive anti-TSH-receptor antibodies', exp:'Intact feedback suppresses TSH.'},
  {q:'Which eye finding is unique to Graves disease?', a:'Exophthalmos (proptosis, bulging eyes)', exp:'Orbital infiltration causes it.'},
  {q:'Name four classic hyperthyroid symptoms.', a:'Weight loss, heat intolerance, tremor, tachycardia', exp:'Everything speeds up.'},
  {q:'What is thyroid storm?', a:'Life-threatening hyperthyroidism with fever, tachycardia, and delirium', exp:'It is triggered by surgery, infection, or stopping antithyroid drugs.'},
  {q:'What is Hashimoto thyroiditis?', a:'The most common hypothyroidism cause in iodine-replete areas, a type IV hypersensitivity', exp:'T cells gradually destroy thyroid follicles.'},
  {q:'What is the lab pattern of Hashimoto thyroiditis?', a:'Low T4, high TSH, positive anti-TPO antibodies', exp:'The pituitary tries to drive a failing gland.'},
  {q:'Name four classic hypothyroid symptoms.', a:'Weight gain, cold intolerance, bradycardia, constipation', exp:'Everything slows down.'},
  {q:'What is myxedema coma?', a:'Severe untreated hypothyroidism with bradycardia, hypotension, hypothermia, and altered mental status', exp:'It needs prompt IV levothyroxine.'},
  {q:'Why is TSH the best screening test for thyroid disease?', a:'Small T4 changes produce large TSH changes', exp:'The pituitary is very sensitive to feedback.'},
  {q:'What is Cushing syndrome?', a:'Excess cortisol exposure from any source', exp:'The most common cause is exogenous corticosteroid therapy.'},
  {q:'What specifically defines Cushing DISEASE?', a:'A pituitary adenoma secreting excess ACTH', exp:'It is one specific cause of Cushing syndrome.'},
  {q:'Name the classic body-habitus features of Cushing syndrome.', a:'Central obesity, moon face, buffalo hump, purple striae', exp:'Thin extremities contrast with truncal fat.'},
  {q:'What lab result distinguishes Cushing from a normal stress response?', a:'Elevated cortisol that does NOT suppress on the dexamethasone test', exp:'Autonomous cortisol ignores feedback.'},
  {q:'What is Addison disease?', a:'Primary adrenal insufficiency, most often autoimmune destruction of the cortex', exp:'TB is the leading cause worldwide.'},
  {q:'What is the lab pattern of Addison disease?', a:'Low cortisol, high ACTH, hyperkalemia, hyponatremia', exp:'The pituitary drives the failing adrenal.'},
  {q:'Why does hyperpigmentation occur in Addison disease?', a:'High ACTH stimulates melanocytes (POMC precursor includes MSH)', exp:'Pigmentation appears in skin, gums, and palmar creases.'},
  {q:'Why does Addison disease cause hyperkalemia and hyponatremia?', a:'Aldosterone deficiency prevents Na retention and K excretion', exp:'The kidney loses sodium and retains potassium.'},
  {q:'What is an Addisonian crisis?', a:'Acute adrenal insufficiency with hypotension, hyperkalemia, hyponatremia, and hypoglycemia', exp:'It needs immediate IV hydrocortisone.'},
  {q:'Why must chronic exogenous steroids be tapered rather than stopped abruptly?', a:'They suppress the HPA axis and atrophy the adrenal cortex', exp:'Abrupt withdrawal can trigger Addisonian crisis.'},
  {q:'Compare Cushing and Addison on blood pressure and glucose.', a:'Cushing: high BP and high glucose; Addison: low BP and low glucose', exp:'Cortisol direction dictates both.'},
  {q:'A patient has low T4 and low TSH after pituitary surgery. What type of hypothyroidism is this?', a:'Secondary (central) hypothyroidism', exp:'Both values low means the pituitary is not signaling the gland.'},
  {q:'In primary hypothyroidism, what happens to TSH when T4 is low?', a:'TSH is high', exp:'Intact feedback drives the pituitary to push TSH up.'}
];
