/* SCI 225 — Final Exam Suite · drill content (Weeks 8–14)
   Sourced from the Final Exam Study Guide so wording stays consistent.
   dir: "up" | "down" | "n" (normal) */
window.FINAL_DRILLS = {

/* ---------------- LAB SIGNATURES ---------------- */
labs: [
 {week:"8", labs:[["Platelets","down"],["PT / INR","up"],["aPTT","up"],["Fibrinogen","down"],["D-dimer","up"]],
  opts:["Disseminated intravascular coagulation","Hemophilia A","Immune thrombocytopenia","Vitamin K deficiency"], c:0,
  why:"All four numbers deranged with a markedly high D-dimer means clots formed and were broken down. Platelets and factors were consumed — the bleeding is caused by the clotting."},
 {week:"8", labs:[["Platelets","n"],["PT / INR","n"],["aPTT","up"]],
  opts:["Hemophilia A (factor VIII deficiency)","Disseminated intravascular coagulation","Immune thrombocytopenia","Liver failure"], c:0,
  why:"An isolated prolonged aPTT with normal PT and platelets points to an intrinsic-pathway factor. Factor VIII deficiency causes deep bleeding — hemarthrosis and muscle hematomas."},
 {week:"8", labs:[["Platelets","down"],["PT / INR","n"],["aPTT","n"]],
  opts:["Immune thrombocytopenia","Hemophilia A","Disseminated intravascular coagulation","von Willebrand disease"], c:0,
  why:"Low platelets alone, with a normal coagulation cascade, is a primary-hemostasis problem — petechiae, purpura, and mucosal bleeding. In children it often follows a viral illness."},
 {week:"8", labs:[["MCV","down"],["Ferritin","down"],["TIBC","up"],["Serum iron","down"]],
  opts:["Iron-deficiency anemia","Anemia of chronic disease","Thalassemia","Sideroblastic anemia"], c:0,
  why:"Empty stores (low ferritin) with the body raising its grabbing capacity (high TIBC) is the iron-deficiency signature. Chronic disease shows the opposite: high ferritin, low TIBC."},
 {week:"8", labs:[["MCV","down"],["Ferritin","up"],["TIBC","down"],["Serum iron","down"]],
  opts:["Anemia of chronic disease","Iron-deficiency anemia","Thalassemia","Hemolytic anemia"], c:0,
  why:"Iron is present but locked in storage by inflammation — the pantry is full but the cell cannot get in. High ferritin with low TIBC separates this from true iron deficiency."},
 {week:"8", labs:[["MCV","up"],["Reticulocytes","down"],["Neurologic exam","abn"]],
  opts:["Vitamin B12 deficiency","Folate deficiency","Iron-deficiency anemia","Anemia of chronic disease"], c:0,
  why:"Both B12 and folate deficiency make big cells. Only B12 is required for myelin maintenance, so only B12 deficiency adds paresthesias, ataxia, and loss of position sense."},
 {week:"8", labs:[["Reticulocytes","up"],["LDH","up"],["Indirect bilirubin","up"],["Haptoglobin","down"]],
  opts:["Hemolytic anemia","Aplastic anemia","Iron-deficiency anemia","Chronic kidney disease anemia"], c:0,
  why:"That four-item cluster is the hemolysis signature. The high reticulocyte count proves the marrow is healthy and responding — the problem is destruction, not production."},
 {week:"8", labs:[["Hemoglobin","down"],["WBC","down"],["Platelets","down"],["Reticulocytes","down"]],
  opts:["Aplastic anemia","Hemolytic anemia","Polycythemia vera","Iron-deficiency anemia"], c:0,
  why:"Pancytopenia with a low reticulocyte count means the marrow itself has failed. Contrast with leukemia, where blasts crowd the marrow and produce the same three cytopenias."},
 {week:"8", labs:[["Hematocrit","up"],["Erythropoietin","down"]],
  opts:["Polycythemia vera (primary)","Secondary polycythemia from hypoxia","Dehydration","Anemia of chronic disease"], c:0,
  why:"A LOW erythropoietin with a high hematocrit means the marrow is producing without being asked — an autonomous neoplasm. Secondary polycythemia shows a HIGH EPO."},
 {week:"8", labs:[["Hematocrit","up"],["Erythropoietin","up"],["PaO2","down"]],
  opts:["Secondary polycythemia from chronic hypoxia","Polycythemia vera","Acute blood loss","Iron-deficiency anemia"], c:0,
  why:"Chronic hypoxemia (COPD, altitude, heavy smoking, cyanotic heart disease) is an appropriate stimulus for renal EPO release. High EPO is the discriminator from polycythemia vera."},

 {week:"9", labs:[["Troponin","up"],["ECG","abn"],["Chest pain","abn"]],
  opts:["Myocardial infarction","Unstable angina","Stable angina","Pericarditis"], c:0,
  why:"Troponin leaks only when myocytes die. Unstable angina can look identical clinically but keeps a normal troponin — that single value separates them."},
 {week:"9", labs:[["BNP","up"],["Ejection fraction","down"]],
  opts:["Systolic heart failure","Diastolic heart failure","Pulmonary embolism","Acute kidney injury"], c:0,
  why:"BNP is released by stretched ventricular myocardium. Paired with a reduced ejection fraction it indicates systolic (HFrEF) failure — a contraction problem."},

 {week:"11", labs:[["BUN : creatinine","up"],["Urine sodium","down"],["Urine specific gravity","up"]],
  opts:["Prerenal acute kidney injury","Acute tubular necrosis","Postrenal obstruction","Chronic kidney disease"], c:0,
  why:"A thirsty kidney: intact tubules avidly conserving sodium and water. High BUN:Cr (>20:1), low urine sodium, concentrated urine — restoring perfusion reverses it."},
 {week:"11", labs:[["BUN : creatinine","n"],["Urine sodium","up"],["Urine sediment","abn"]],
  opts:["Acute tubular necrosis","Prerenal acute kidney injury","Nephrotic syndrome","Pyelonephritis"], c:0,
  why:"A broken kidney: damaged tubules cannot conserve sodium or concentrate urine, and they shed muddy brown granular casts. The opposite profile from prerenal disease."},
 {week:"11", labs:[["Urine protein","up"],["Serum albumin","down"],["Serum lipids","up"]],
  opts:["Nephrotic syndrome","Nephritic syndrome","Acute tubular necrosis","Cystitis"], c:0,
  why:"Proteinuria over 3.5 g/day, hypoalbuminemia, hyperlipidemia, and severe generalized edema is the nephrotic tetrad — a permeability problem in the glomerulus."},
 {week:"11", labs:[["Urine RBC casts","up"],["Blood pressure","up"],["Urine protein","n"]],
  opts:["Nephritic syndrome","Nephrotic syndrome","Acute tubular necrosis","Kidney stone"], c:0,
  why:"Inflammation lets cells through: hematuria with RBC casts, hypertension, and only mild proteinuria. Post-streptococcal glomerulonephritis is the classic example."},
 {week:"11", labs:[["Urine WBC casts","up"],["Fever","abn"],["CVA tenderness","abn"]],
  opts:["Pyelonephritis","Cystitis","Nephrolithiasis","Glomerulonephritis"], c:0,
  why:"Casts form in renal tubules, so WBC casts can only originate in the kidney. With fever and costovertebral angle tenderness this is upper-tract infection."},
 {week:"11", labs:[["Phosphate","up"],["Calcium","down"],["PTH","up"],["Vitamin D (active)","down"]],
  opts:["Renal osteodystrophy in CKD","Primary hyperparathyroidism","Osteoporosis","Paget disease"], c:0,
  why:"Failing kidneys retain phosphate and cannot activate vitamin D, so calcium falls and PTH rises to pull calcium from bone. That trio is the CKD bone signature."},
 {week:"11", labs:[["Potassium","up"],["Urine output","down"],["Creatinine","up"]],
  opts:["Oliguric phase of acute kidney injury","Diuretic phase of AKI","Nephrotic syndrome","Cystitis"], c:0,
  why:"With excretion halted, potassium accumulates rapidly and destabilizes cardiac conduction. Hyperkalemia is the most immediate threat to life in oliguric AKI."},

 {week:"13", labs:[["Conjugated bilirubin","up"],["Alkaline phosphatase","up"],["Stool colour","down"],["Urine colour","up"]],
  opts:["Posthepatic (obstructive) jaundice","Prehepatic jaundice from hemolysis","Intrahepatic hepatitis","Gilbert syndrome"], c:0,
  why:"Pale stool proves bile is not reaching the gut. The water-soluble conjugated bilirubin backs into blood, spills into urine (dark), and deposits in skin causing itching."},
 {week:"13", labs:[["Albumin","down"],["PT / INR","up"],["Ammonia","up"],["Platelets","down"]],
  opts:["Cirrhosis with portal hypertension","Acute pancreatitis","Nephrotic syndrome","Disseminated intravascular coagulation"], c:0,
  why:"Hepatocellular failure (no albumin, no clotting factors, no detoxification) plus portal hypertension causing splenic sequestration of platelets. One organ, four abnormal numbers."},
 {week:"13", labs:[["Lipase","up"],["Amylase","up"],["Calcium","down"]],
  opts:["Acute pancreatitis","Cholecystitis","Peptic ulcer perforation","Hepatitis"], c:0,
  why:"Enzymes leak from the autodigesting gland. Calcium falls because it is consumed in fat necrosis (saponification) — a low calcium here marks more severe disease."},

 {week:"14", labs:[["Creatine kinase","up"],["Potassium","up"],["Creatinine","up"],["Urine colour","up"]],
  opts:["Rhabdomyolysis with acute kidney injury","Compartment syndrome alone","Osteomyelitis","Gout"], c:0,
  why:"Crushed or ischemic muscle releases myoglobin, which precipitates in renal tubules causing AKI, while released potassium threatens cardiac rhythm."},
 {week:"14", labs:[["Serum calcium","n"],["Phosphate","n"],["Bone density","down"]],
  opts:["Osteoporosis","Osteomalacia","Renal osteodystrophy","Paget disease"], c:0,
  why:"Osteoporosis is too little bone — what remains is normally mineralized, so calcium and phosphate are NORMAL. Normal labs with low density is the giveaway."},
 {week:"14", labs:[["Vitamin D","down"],["Calcium","down"],["Alkaline phosphatase","up"],["Bone","abn"]],
  opts:["Osteomalacia","Osteoporosis","Osteogenesis imperfecta","Septic arthritis"], c:0,
  why:"Osteomalacia is poorly mineralized bone from vitamin D deficiency — the bone is soft, not merely scarce. Contrast with osteoporosis, where calcium studies are normal."},
 {week:"14", labs:[["Uric acid","up"],["Joint fluid crystals","abn"],["Single joint","abn"]],
  opts:["Gout","Rheumatoid arthritis","Osteoarthritis","Septic arthritis"], c:0,
  why:"Needle-shaped, negatively birefringent monosodium urate crystals in an acutely inflamed first MTP joint. Urate is least soluble in the coolest, most distal joint."}
],

/* ---------------- CONFUSION PAIRS ---------------- */
pairs: [
 {week:"8", clue:"Macrocytic anemia WITH paresthesias and an unsteady gait", a:"Vitamin B12 deficiency", b:"Folate deficiency", c:0,
  why:"Both cause macrocytosis. Only B12 is needed for myelin, so only B12 deficiency produces neurologic signs."},
 {week:"8", clue:"Microcytic anemia with a LOW ferritin and HIGH TIBC", a:"Iron deficiency", b:"Anemia of chronic disease", c:0,
  why:"Empty stores plus increased grabbing capacity. Chronic disease shows high ferritin and low TIBC — iron locked away, not absent."},
 {week:"8", clue:"Petechiae, purpura, and immediate oozing from small cuts", a:"Platelet disorder", b:"Clotting factor deficiency", c:0,
  why:"Platelets seal small vessels, so their failure causes superficial, immediate bleeding. Factor deficiencies bleed deep and late — joints and muscle."},
 {week:"8", clue:"High hematocrit with a LOW erythropoietin level", a:"Polycythemia vera", b:"Secondary polycythemia", c:0,
  why:"Low EPO means the marrow is producing autonomously. Secondary polycythemia is an appropriate response to hypoxia, so EPO is high."},
 {week:"8", clue:"Dyspnea during transfusion with hypertension and distended neck veins", a:"TACO (circulatory overload)", b:"TRALI (lung injury)", c:0,
  why:"TACO is a volume problem — hypertension, JVD, responds to diuresis. TRALI causes hypoxemia with normal or low blood pressure and no volume overload."},
 {week:"9", clue:"Crackles, orthopnea, and paroxysmal nocturnal dyspnea", a:"Left-sided heart failure", b:"Right-sided heart failure", c:0,
  why:"Left ventricle fails, blood backs up into the lungs. Right failure backs up into the body — JVD, hepatomegaly, peripheral edema."},
 {week:"9", clue:"Congestive symptoms with an ejection fraction of 58%", a:"Diastolic failure (HFpEF)", b:"Systolic failure (HFrEF)", c:0,
  why:"A normal ejection FRACTION with congestion means a filling problem — a stiff, hypertrophied ventricle ejecting a normal percentage of a too-small volume."},
 {week:"9", clue:"Rest chest pain unrelieved by nitroglycerin, troponin NORMAL", a:"Unstable angina", b:"Myocardial infarction", c:0,
  why:"Both present with rest pain. Only infarction kills myocytes, and only dying myocytes release troponin."},
 {week:"9", clue:"Leg ulcer at the medial malleolus, brown staining, relieved by elevation", a:"Venous insufficiency", b:"Peripheral arterial disease", c:0,
  why:"Venous: elevation helps, hemosiderin staining, medial malleolus. Arterial: dangling helps, cool pale skin, absent pulses, punched-out toe ulcers."},
 {week:"9", clue:"Cyanosis at birth with pulmonary stenosis and an overriding aorta", a:"Tetralogy of Fallot", b:"Ventricular septal defect", c:0,
  why:"Tetralogy shunts right-to-left because pulmonary stenosis obstructs outflow. An isolated VSD shunts left-to-right and is acyanotic."},
 {week:"10", clue:"FEV1/FVC ratio REDUCED with increased residual volume", a:"Obstructive disease", b:"Restrictive disease", c:0,
  why:"Obstruction limits expiratory flow and traps air. Restriction lowers all volumes while the ratio stays normal or rises."},
 {week:"10", clue:"Hypoxemia that does NOT improve with high-flow oxygen", a:"Shunt (pneumonia, ARDS)", b:"Dead space (pulmonary embolism)", c:0,
  why:"In a true shunt, blood perfuses unventilated alveoli and never contacts oxygen. Dead space is ventilation without perfusion."},
 {week:"10", clue:"Absent breath sounds with HYPERRESONANCE to percussion", a:"Pneumothorax", b:"Pleural effusion", c:0,
  why:"Percussion decides air versus fluid. Hyperresonant means air; dull means fluid (or consolidation)."},
 {week:"10", clue:"Bilateral infiltrates, refractory hypoxemia, NORMAL cardiac filling pressures", a:"ARDS", b:"Cardiogenic pulmonary edema", c:0,
  why:"ARDS is a leaky-membrane problem, so filling pressures are normal and diuresis does not fix it. Cardiogenic edema has JVD, S3, and a high BNP."},
 {week:"10", clue:"Barking cough with inspiratory stridor, gradual onset at night", a:"Croup", b:"Epiglottitis", c:0,
  why:"Croup barks; epiglottitis drools. Epiglottitis is abrupt, toxic-appearing, with drooling and no cough."},
 {week:"11", clue:"BUN:creatinine above 20:1 with LOW urine sodium", a:"Prerenal AKI", b:"Acute tubular necrosis", c:0,
  why:"The tubules are working correctly to conserve volume — the kidney is starved, not damaged. ATN shows high urine sodium and muddy brown casts."},
 {week:"11", clue:"Cola-coloured urine, RBC casts, and hypertension", a:"Nephritic syndrome", b:"Nephrotic syndrome", c:0,
  why:"Nephritic is inflammation, so cells leak through. Nephrotic is a permeability problem — massive proteinuria, low albumin, severe edema."},
 {week:"11", clue:"Elevated creatinine WITH anemia and small shrunken kidneys", a:"Chronic kidney disease", b:"Acute kidney injury", c:0,
  why:"Creatinine rises in both. Anemia and kidney atrophy take months to years to develop, so they indicate chronicity."},
 {week:"11", clue:"Fever, chills, costovertebral angle tenderness, WBC casts", a:"Pyelonephritis", b:"Cystitis", c:0,
  why:"Systemic signs plus casts localize infection to the kidney. Simple cystitis is typically afebrile with no casts."},
 {week:"12", clue:"Sudden scrotal pain, high-riding testis, ABSENT cremasteric reflex", a:"Testicular torsion", b:"Epididymitis", c:0,
  why:"Torsion is a surgical emergency with about a six-hour salvage window. Epididymitis is gradual and febrile, and elevation RELIEVES the pain."},
 {week:"12", clue:"Smooth, symmetrically enlarged prostate with early obstructive symptoms", a:"Benign prostatic hyperplasia", b:"Prostate cancer", c:0,
  why:"BPH grows centrally against the urethra so it obstructs early. Cancer grows peripherally — hard irregular nodule, silent until advanced."},
 {week:"12", clue:"Firm painless scrotal mass that does NOT transilluminate", a:"Testicular cancer", b:"Hydrocele", c:0,
  why:"Fluid transmits light; solid tumour does not. In a man aged 15 to 35 this must be evaluated for malignancy."},
 {week:"12", clue:"Thick white cottage-cheese discharge with intense itching after antibiotics", a:"Candidiasis", b:"Bacterial vaginosis", c:0,
  why:"Antibiotics kill protective lactobacilli and yeast overgrows. Bacterial vaginosis is thin, grey, and fishy with mild itching."},
 {week:"13", clue:"Epigastric pain RELIEVED by eating, returning 2 to 3 hours later", a:"Duodenal ulcer", b:"Gastric ulcer", c:0,
  why:"Food buffers acid and relieves duodenal pain temporarily. Gastric ulcer pain characteristically WORSENS with eating."},
 {week:"13", clue:"Skip lesions, transmural inflammation, and fistula formation", a:"Crohn disease", b:"Ulcerative colitis", c:0,
  why:"Transmural depth is what allows tracts to burrow into adjacent structures. UC is continuous, mucosal only, and starts at the rectum."},
 {week:"13", clue:"Bloody diarrhoea with tenesmus, continuous from the rectum upward", a:"Ulcerative colitis", b:"Crohn disease", c:0,
  why:"UC is superficial and continuous, which is why it bleeds and carries a markedly raised colorectal cancer risk."},
 {week:"13", clue:"Weight loss, fever, bloody stool, and raised inflammatory markers", a:"Inflammatory bowel disease", b:"Irritable bowel syndrome", c:0,
  why:"Alarm features mean inflammation and structural disease. IBS is functional — pain relieved by defecation, no bleeding, normal findings."},
 {week:"13", clue:"Black tarry foul-smelling stool", a:"Upper GI bleed", b:"Lower GI bleed", c:0,
  why:"Melena means blood was in the tract long enough to be digested, which localizes the source to the upper tract."},
 {week:"13", clue:"Projectile NON-bilious vomiting in a 6-week-old, still hungry", a:"Pyloric stenosis", b:"Intussusception", c:0,
  why:"Non-bilious places the obstruction at or above the pylorus. Intussusception occurs later (3 months to 3 years) with currant-jelly stool."},
 {week:"14", clue:"Symmetric small-joint pain with morning stiffness over one hour", a:"Rheumatoid arthritis", b:"Osteoarthritis", c:0,
  why:"Inflammatory arthritis is worse after rest and improves with use. OA is asymmetric, under 30 minutes, and worse with use."},
 {week:"14", clue:"Leg pain on walking RELIEVED by leaning forward over a cart", a:"Neurogenic claudication", b:"Vascular claudication", c:0,
  why:"Position-dependent relief means a mechanical canal problem — flexion widens the spinal canal. Vascular claudication is relieved by stopping, whatever the posture."},
 {week:"14", clue:"Burn that is white, leathery, dry, and PAINLESS", a:"Full-thickness burn", b:"Partial-thickness burn", c:0,
  why:"The deepest burn is the least painful because the dermal nerve endings are destroyed. Partial thickness blisters and hurts intensely."},
 {week:"14", clue:"Itchy dry patches in the antecubital and popliteal creases", a:"Atopic dermatitis", b:"Psoriasis", c:0,
  why:"Eczema goes in the bends; psoriasis goes on the points — thick silvery scale on extensor elbows and knees."},
 {week:"14", clue:"High fever for three days, rash appears AS the fever breaks", a:"Roseola", b:"Measles", c:0,
  why:"Roseola's signature is a rash appearing as the fever resolves. In measles the rash appears while the child is still febrile, preceded by Koplik spots."}
],

/* ---------------- RED FLAGS ---------------- */
redflags: [
 {week:"8", s:"Fever, flank pain, and dark urine 15 minutes into a transfusion", act:1,
  why:"Acute hemolytic reaction from ABO incompatibility. Stop the transfusion immediately — it can progress to acute kidney injury and DIC."},
 {week:"8", s:"Mild urticaria and itching during a transfusion, vital signs stable", act:0,
  why:"A minor allergic reaction to donor plasma proteins. It is managed rather than treated as an emergency — but keep watching for progression to anaphylaxis."},
 {week:"8", s:"Fever in a child with sickle cell disease", act:1,
  why:"Repeated splenic infarction leaves the child functionally asplenic. Encapsulated-organism sepsis can become overwhelming within hours."},
 {week:"8", s:"Oozing from every IV site with falling platelets and rising D-dimer", act:1,
  why:"DIC. The trigger (usually sepsis) must be treated — replacing products alone refuels the fire."},
 {week:"9", s:"Chest pain over 20 minutes at rest with a rising troponin", act:1,
  why:"Myocardial infarction. Time is muscle, and dysrhythmia is the leading early cause of death."},
 {week:"9", s:"Predictable chest tightness on climbing stairs, gone after two minutes of rest", act:0,
  why:"Stable angina — a supply-demand mismatch without cell death. It warrants workup, not emergency intervention."},
 {week:"9", s:"Fatigue, nausea, and jaw discomfort in an older woman with diabetes", act:1,
  why:"Atypical presentation of myocardial infarction. Autonomic neuropathy can blunt pain entirely — never rule out MI because the pain does not sound cardiac."},
 {week:"9", s:"Hypotension with distended neck veins and muffled heart sounds", act:1,
  why:"Obstructive shock from cardiac tamponade — volume and pump are intact but filling is physically prevented. Fluids will not fix it."},
 {week:"10", s:"An asthmatic whose wheeze has disappeared, now drowsy, with a normalising CO2", act:1,
  why:"A silent chest. Airflow is so poor no sound is produced and the patient is tiring — impending respiratory arrest."},
 {week:"10", s:"An asthmatic wheezing audibly who improves after a bronchodilator", act:0,
  why:"Wheezing means air is still moving. Improvement after treatment is reassuring — the dangerous sign is the wheeze disappearing while the patient worsens."},
 {week:"10", s:"Tracheal deviation away from absent breath sounds, with hypotension", act:1,
  why:"Tension pneumothorax. Rising pressure shifts the mediastinum and obstructs venous return — needle decompression before imaging."},
 {week:"10", s:"Sudden dyspnoea and pleuritic pain in a postoperative immobile patient", act:1,
  why:"Pulmonary embolism until proven otherwise. Virchow's triad is fully present and a large embolus causes obstructive shock."},
 {week:"10", s:"A 3-year-old with abrupt fever, drooling, and a tripod posture", act:1,
  why:"Epiglottitis. Do not examine the throat or upset the child — laryngospasm can cause complete obstruction."},
 {week:"11", s:"Potassium 6.4 mEq/L with oliguria and peaked T waves", act:1,
  why:"Hyperkalemia in oliguric AKI. Potassium destabilises cardiac conduction and is what kills first."},
 {week:"11", s:"Dysuria and urinary frequency with no fever in an otherwise well adult", act:0,
  why:"Uncomplicated cystitis. It needs treatment but is not an emergency — fever, flank pain, and CVA tenderness would change that."},
 {week:"11", s:"New confusion and falls in an older adult with no fever", act:1,
  why:"In older adults a urinary tract infection may present only as confusion or functional decline. Do not require the textbook triad before acting."},
 {week:"11", s:"A firm unilateral abdominal mass in a 3-year-old", act:1,
  why:"Suspected Wilms tumour — and repeated deep palpation risks seeding tumour cells. The assessment itself can cause harm."},
 {week:"12", s:"Sudden severe scrotal pain with an absent cremasteric reflex", act:1,
  why:"Testicular torsion. The salvage window is roughly six hours — this goes straight to surgery."},
 {week:"12", s:"Gradual scrotal ache with fever, relieved by elevating the scrotum", act:0,
  why:"Epididymitis — treated medically. The relief with elevation and intact cremasteric reflex distinguish it from torsion."},
 {week:"12", s:"Any vaginal bleeding in a postmenopausal woman", act:1,
  why:"Abnormal until proven otherwise — it must be evaluated for endometrial carcinoma."},
 {week:"12", s:"Unilateral pelvic pain with a missed period and dizziness", act:1,
  why:"Possible ruptured ectopic pregnancy causing rapid intra-abdominal haemorrhage and hypovolaemic shock."},
 {week:"13", s:"Sudden severe abdominal pain with a rigid board-like abdomen", act:1,
  why:"Perforation with peritonitis — a surgical emergency."},
 {week:"13", s:"Appendicitis pain that suddenly resolves completely", act:1,
  why:"Rupture decompresses the appendix and briefly relieves pain, then contents spill into the peritoneum. Sudden relief is a danger sign, not improvement."},
 {week:"13", s:"Haematemesis in a patient with known cirrhosis", act:1,
  why:"Variceal haemorrhage — a high-pressure bleeding source in a patient with no clotting factors and too few platelets."},
 {week:"13", s:"Mild heartburn after a large meal, relieved by sitting up", act:0,
  why:"Ordinary reflux. It warrants lifestyle advice and follow-up for Barrett risk, not emergency care."},
 {week:"14", s:"Severe pain unrelieved by opioids with a tense swollen limb after a fracture", act:1,
  why:"Compartment syndrome. Pain out of proportion is the earliest reliable sign — waiting for pulselessness is waiting too long."},
 {week:"14", s:"Aching and stiffness in both knees at the end of a long day", act:0,
  why:"Osteoarthritis — degenerative, worse with use, better with rest. Not an emergency."},
 {week:"14", s:"A single hot, swollen, exquisitely painful joint with fever", act:1,
  why:"Septic arthritis until arthrocentesis proves otherwise — bacterial infection destroys cartilage within days."},
 {week:"14", s:"Facial burns with singed nasal hair and a hoarse voice", act:1,
  why:"Inhalation injury. Progressive airway oedema can obstruct the airway, so airway assessment precedes fluid calculations."}
],

/* ---------------- MECHANISM CHAINS ---------------- */
chains: [
 {week:"11", title:"CKD causes anemia", start:"Progressive nephron loss in chronic kidney disease",
  steps:["Peritubular cells lose the ability to sense hypoxia","Erythropoietin production falls","Red marrow is never stimulated to produce","Normocytic normochromic anemia develops"],
  why:"The kidney is the EPO source. Cells that are produced are normal in size — there are simply too few, which is why the anemia is normocytic."},
 {week:"11", title:"CKD weakens bone", start:"Failing kidneys cannot activate vitamin D and retain phosphate",
  steps:["Intestinal calcium absorption falls","Serum calcium drops","Parathyroid glands increase PTH secretion","PTH resorbs calcium from bone → renal osteodystrophy"],
  why:"High phosphate, low calcium, high PTH is the CKD bone signature. The compensation (PTH) is what actually destroys the bone."},
 {week:"9", title:"Compensation becomes the disease", start:"Cardiac output falls in heart failure",
  steps:["Kidneys sense reduced perfusion and activate RAAS","Aldosterone retains sodium and water; angiotensin II vasoconstricts","Preload AND afterload both rise","The failing ventricle is loaded from both ends and decompensates"],
  why:"RAAS is designed for hemorrhage. In heart failure it is exactly wrong — which is why ACE inhibitors and diuretics work by switching the compensation off."},
 {week:"9", title:"Plaque to infarction", start:"Endothelial injury from hypertension, smoking, or diabetes",
  steps:["LDL enters the intima and oxidises","Macrophages engulf it forming foam cells and a fatty streak","A fibrous plaque narrows the lumen → stable angina","Plaque ruptures, thrombus forms, vessel occludes → infarction"],
  why:"Stable plaques narrow gradually; rupture is what converts stable disease into an acute coronary syndrome, often without warning."},
 {week:"8", title:"Virchow's triad to pulmonary embolism", start:"Postoperative immobility, vessel trauma, and hypercoagulability",
  steps:["Stasis, endothelial injury, and hypercoagulability coincide","A thrombus forms in a deep leg vein","The clot dislodges and travels through the right heart","It lodges in the pulmonary artery → dead-space ventilation and hypoxemia"],
  why:"One Week 8 concept produces a Week 9 problem and a Week 10 emergency. A large embolus causes obstructive shock."},
 {week:"14", title:"Crush injury to kidney failure", start:"Compartment pressure rises after a fracture",
  steps:["Perfusion is cut off and muscle becomes ischemic","Necrotic muscle releases myoglobin and potassium","Myoglobin precipitates in renal tubules","Intrarenal AKI develops while hyperkalemia threatens cardiac rhythm"],
  why:"One limb injury, three systems: musculoskeletal, renal, and cardiac. This is why compartment syndrome is time-critical."},
 {week:"13", title:"Cirrhosis to bleeding", start:"Chronic liver injury causes fibrosis and regenerative nodules",
  steps:["Portal blood flow is obstructed → portal hypertension","Collateral veins engorge, forming esophageal varices","The spleen congests and sequesters platelets","Hepatocytes also fail to make clotting factors → catastrophic variceal bleed"],
  why:"The cirrhotic patient has a high-pressure bleeding source, no clotting factors, and too few platelets simultaneously."},
 {week:"10", title:"COPD to right heart failure", start:"Chronic hypoxemia from advanced COPD",
  steps:["Hypoxia causes pulmonary vasoconstriction","Pulmonary vascular resistance rises → pulmonary hypertension","Right ventricular afterload increases and the ventricle hypertrophies","The right ventricle fails → cor pulmonale"],
  why:"The same hypoxemia also drives renal EPO release, producing secondary polycythemia. One lung disease, three chapters."},
 {week:"13", title:"Fat malabsorption to bleeding risk", start:"Pancreatic insufficiency or biliary obstruction",
  steps:["Fat cannot be digested or emulsified → steatorrhea","Fat-soluble vitamins A, D, E and K are lost in stool","Vitamin K deficiency impairs clotting factor synthesis","PT/INR prolongs and the patient bruises and bleeds"],
  why:"Low vitamin D from the same mechanism causes osteomalacia — a Week 13 lesion producing a Week 8 and a Week 14 problem."},
 {week:"12", title:"Menopause to fracture", start:"Ovarian follicles are depleted at menopause",
  steps:["Estrogen production falls sharply","Estrogen's restraint on osteoclasts is lost","Bone resorption outpaces formation","Bone density falls → fragility and vertebral compression fractures"],
  why:"Estrogen is a brake on bone resorption. Removing the brake accelerates loss most rapidly in the first years after menopause."}
]
};
