/* SCI 225 — Midterm Suite · drill content (Weeks 1–6)
   Weeks per the study guides and the Chase bank:
   1 Foundations (cell, genetics, ABGs) · 2 Immunity & Inflammation · 3 Oncology
   4 Neurologic structure & disorders · 5 Neuro assessment, NMJ & trauma · 6 Endocrine
   dir: "up" | "down" | "n" (normal) | "abn" */
window.FINAL_DRILLS = {

/* ---------------- LAB SIGNATURES ---------------- */
labs: [
 {week:"1", labs:[["pH","down"],["PaCO₂","up"],["HCO₃","n"]],
  opts:["Uncompensated respiratory acidosis","Metabolic acidosis","Respiratory alkalosis","Metabolic alkalosis"], c:0,
  why:"pH is low and CO₂ moves opposite to it, so the problem is respiratory. Bicarbonate is still normal, so the kidneys have not compensated — this is acute."},
 {week:"1", labs:[["pH","down"],["PaCO₂","n"],["HCO₃","down"]],
  opts:["Metabolic acidosis","Respiratory acidosis","Metabolic alkalosis","Respiratory alkalosis"], c:0,
  why:"pH and bicarbonate move together (Metabolic Equal), so the disorder is metabolic. Causes include DKA, lactic acidosis, renal failure, and severe diarrhoea."},
 {week:"1", labs:[["pH","up"],["PaCO₂","n"],["HCO₃","up"]],
  opts:["Metabolic alkalosis","Respiratory alkalosis","Metabolic acidosis","Respiratory acidosis"], c:0,
  why:"High pH with high bicarbonate is metabolic alkalosis — classically from vomiting or nasogastric suction, which lose gastric acid."},
 {week:"1", labs:[["Serum sodium","down"],["Serum osmolality","down"],["Urine osmolality","up"]],
  opts:["SIADH","Diabetes insipidus","Dehydration","Hyperaldosteronism"], c:0,
  why:"Too much ADH means water is retained: dilute blood (low sodium and osmolality) with inappropriately concentrated urine. Diabetes insipidus is the mirror image."},
 {week:"1", labs:[["Serum sodium","up"],["Serum osmolality","up"],["Urine osmolality","down"]],
  opts:["Diabetes insipidus","SIADH","Fluid overload","Metabolic alkalosis"], c:0,
  why:"Too little ADH means water is lost: concentrated blood with large volumes of dilute urine. Thirst and polyuria dominate."},
 {week:"1", labs:[["Serum potassium","up"],["ECG T waves","abn"],["Serum pH","down"]],
  opts:["Hyperkalemia, often with acidosis","Hypokalemia","Hypercalcemia","Hypernatremia"], c:0,
  why:"Acidosis drives potassium out of cells in exchange for hydrogen ions, raising serum potassium. Peaked T waves are the warning sign of cardiac instability."},

 {week:"2", labs:[["WBC","up"],["Neutrophils","up"],["Bands","up"],["Fever","abn"]],
  opts:["Acute bacterial infection","Viral infection","Allergic reaction","Parasitic infection"], c:0,
  why:"Neutrophilia with a left shift (immature bands released early) is the classic acute bacterial pattern. Viral infections tend to raise lymphocytes instead."},
 {week:"2", labs:[["WBC","n"],["Lymphocytes","up"],["Neutrophils","down"]],
  opts:["Viral infection","Acute bacterial infection","Allergic reaction","Bone marrow failure"], c:0,
  why:"Lymphocytosis with relative neutropenia points to a viral process — lymphocytes are the adaptive cells that handle intracellular pathogens."},
 {week:"2", labs:[["Eosinophils","up"],["IgE","up"]],
  opts:["Type I hypersensitivity or parasitic infection","Bacterial sepsis","Autoimmune disease","Immunodeficiency"], c:0,
  why:"IgE and eosinophils are the allergy and antiparasite arm. Elevated together they point to atopy, asthma, or a helminth infection."},
 {week:"2", labs:[["ESR","up"],["CRP","up"],["Fever","abn"]],
  opts:["Acute inflammation (non-specific)","Anemia","Dehydration","Hypothyroidism"], c:0,
  why:"ESR and CRP are acute-phase reactants. They confirm inflammation is present but say nothing about its cause or location."},
 {week:"2", labs:[["CD4 count","down"],["Opportunistic infection","abn"]],
  opts:["Advanced HIV infection","Type I hypersensitivity","Autoimmune disease","Acute bacterial infection"], c:0,
  why:"HIV destroys CD4 helper T cells, the coordinators of adaptive immunity. When the count falls far enough, organisms that are normally harmless cause disease."},

 {week:"3", labs:[["Tumour markers","up"],["Weight","down"],["Night sweats","abn"]],
  opts:["Malignancy with systemic (B) symptoms","Benign tumour","Acute infection","Allergic reaction"], c:0,
  why:"Unexplained weight loss, night sweats, and fever are the systemic symptoms of malignancy. Benign tumours are local and do not consume the host this way."},
 {week:"3", labs:[["Serum calcium","up"],["PTH","down"],["Known malignancy","abn"]],
  opts:["Paraneoplastic hypercalcemia of malignancy","Primary hyperparathyroidism","Vitamin D deficiency","Renal failure"], c:0,
  why:"Tumours can secrete PTH-related peptide, raising calcium while true PTH is suppressed. In primary hyperparathyroidism both calcium AND PTH are high."},
 {week:"3", labs:[["Uric acid","up"],["Potassium","up"],["Phosphate","up"],["Calcium","down"]],
  opts:["Tumour lysis syndrome","Hypercalcemia of malignancy","Dehydration","Addison disease"], c:0,
  why:"Rapid tumour cell death after starting chemotherapy dumps intracellular contents into blood. The released phosphate binds calcium, so calcium falls while everything else rises."},

 {week:"4", labs:[["Level of consciousness","down"],["Blood pressure","up"],["Pulse","down"],["Respirations","abn"]],
  opts:["Increased intracranial pressure (Cushing triad)","Hypovolemic shock","Neurogenic shock","Septic shock"], c:0,
  why:"Cushing triad — rising blood pressure, falling pulse, and irregular respirations — is a LATE sign of raised intracranial pressure and signals impending herniation."},
 {week:"4", labs:[["CSF pressure","up"],["Pupil (one side)","abn"],["Motor response","down"]],
  opts:["Expanding intracranial mass with early herniation","Meningitis","Ischemic stroke","Seizure disorder"], c:0,
  why:"A unilateral blown pupil with rising pressure and falling motor response indicates the third cranial nerve is being compressed by a shifting brain — a neurosurgical emergency."},
 {week:"4", labs:[["Blood glucose","down"],["Level of consciousness","down"]],
  opts:["Hypoglycemia — check glucose before assuming stroke","Ischemic stroke","Increased ICP","Meningitis"], c:0,
  why:"Hypoglycemia mimics stroke and other neurologic emergencies and is instantly reversible. Glucose is checked first in any patient with sudden altered mental status."},

 {week:"5", labs:[["CSF WBC","up"],["CSF glucose","down"],["CSF protein","up"],["CSF appearance","abn"]],
  opts:["Bacterial meningitis","Viral meningitis","Subarachnoid haemorrhage","Normal CSF"], c:0,
  why:"Bacteria consume glucose, so CSF glucose falls while neutrophils and protein rise and the fluid turns cloudy. Viral meningitis leaves glucose normal."},
 {week:"5", labs:[["CSF WBC","up"],["CSF glucose","n"],["CSF protein","up"]],
  opts:["Viral meningitis","Bacterial meningitis","Multiple sclerosis","Normal CSF"], c:0,
  why:"A lymphocytic picture with NORMAL glucose distinguishes viral from bacterial meningitis — the single most useful discriminator on the CSF panel."},
 {week:"5", labs:[["Muscle strength with repetition","down"],["Strength after rest","up"],["Ptosis","abn"]],
  opts:["Myasthenia gravis","Guillain-Barré syndrome","Multiple sclerosis","Muscular dystrophy"], c:0,
  why:"Weakness that worsens with use and recovers with rest localises to the neuromuscular junction, where acetylcholine receptor antibodies reduce transmission."},
 {week:"5", labs:[["Blood pressure","down"],["Heart rate","down"],["Skin","abn"]],
  opts:["Neurogenic shock","Hypovolemic shock","Septic shock","Cardiogenic shock"], c:0,
  why:"Neurogenic shock is the exception: loss of sympathetic tone gives hypotension with BRADYCARDIA and warm dry skin. Every other shock state drives tachycardia."},

 {week:"6", labs:[["TSH","down"],["Free T4","up"]],
  opts:["Primary hyperthyroidism (Graves disease)","Primary hypothyroidism","Secondary hypothyroidism","Hashimoto thyroiditis"], c:0,
  why:"The gland is overproducing, so negative feedback suppresses TSH. Low TSH with high T4 is the primary hyperthyroid signature."},
 {week:"6", labs:[["TSH","up"],["Free T4","down"]],
  opts:["Primary hypothyroidism (Hashimoto)","Graves disease","Secondary hypothyroidism","Thyroid storm"], c:0,
  why:"The gland is failing, so the pituitary shouts louder — TSH rises while T4 stays low. If BOTH were low the problem would be pituitary (secondary)."},
 {week:"6", labs:[["Cortisol","up"],["ACTH","down"],["Blood glucose","up"],["Potassium","down"]],
  opts:["Cushing syndrome from an adrenal source or steroids","Addison disease","Primary hyperaldosteronism","Pheochromocytoma"], c:0,
  why:"High cortisol with SUPPRESSED ACTH means the drive is not pituitary — an adrenal tumour or exogenous steroids. Cortisol raises glucose and wastes potassium."},
 {week:"6", labs:[["Cortisol","down"],["ACTH","up"],["Sodium","down"],["Potassium","up"]],
  opts:["Addison disease (primary adrenal insufficiency)","Cushing syndrome","SIADH","Hyperaldosteronism"], c:0,
  why:"The adrenal cannot respond, so ACTH climbs. Loss of aldosterone gives the classic low sodium with high potassium, plus hyperpigmentation from the high ACTH."},
 {week:"6", labs:[["Blood glucose","up"],["Ketones","up"],["pH","down"],["HCO₃","down"]],
  opts:["Diabetic ketoacidosis","Hyperosmolar hyperglycemic state","Hypoglycemia","Metabolic alkalosis"], c:0,
  why:"Absolute insulin deficiency forces fat breakdown, generating ketoacids that consume bicarbonate. Kussmaul respirations blow off CO₂ to compensate."},
 {week:"6", labs:[["Blood glucose","up"],["Ketones","n"],["Serum osmolality","up"],["pH","n"]],
  opts:["Hyperosmolar hyperglycemic state","Diabetic ketoacidosis","SIADH","Diabetes insipidus"], c:0,
  why:"In type 2 diabetes there is enough insulin to prevent ketosis but not enough to control glucose. Extreme hyperglycemia drives osmotic diuresis and profound dehydration WITHOUT acidosis."}
],

/* ---------------- CONFUSION PAIRS ---------------- */
pairs: [
 {week:"1", clue:"Cell death from injury, with swelling, rupture, and surrounding inflammation", a:"Necrosis", b:"Apoptosis", c:0,
  why:"Necrosis is uncontrolled: cells swell, burst, and spill contents, provoking inflammation. Apoptosis is programmed and tidy — the cell shrinks and is cleared without inflammation."},
 {week:"1", clue:"An increase in the SIZE of existing cells", a:"Hypertrophy", b:"Hyperplasia", c:0,
  why:"Hypertrophy is bigger cells; hyperplasia is more cells. Cardiac muscle can only hypertrophy because mature cardiac myocytes do not divide."},
 {week:"1", clue:"One mature cell type replaced by another better suited to stress", a:"Metaplasia", b:"Dysplasia", c:0,
  why:"Metaplasia is an adaptive substitution and is reversible. Dysplasia is disordered, atypical growth and is the step that precedes malignancy."},
 {week:"1", clue:"pH 7.30, PaCO₂ 55, HCO₃ 24", a:"Respiratory acidosis", b:"Metabolic acidosis", c:0,
  why:"CO₂ moves opposite to pH, so the problem is respiratory (ROME). A normal bicarbonate means the kidneys have not yet compensated."},
 {week:"1", clue:"Low sodium with concentrated urine and fluid retention", a:"SIADH", b:"Diabetes insipidus", c:0,
  why:"SIADH is too much ADH — water retained, blood diluted. Diabetes insipidus is too little ADH — water lost, blood concentrated, huge volumes of dilute urine."},
 {week:"1", clue:"An affected child born to two unaffected carrier parents", a:"Autosomal recessive", b:"Autosomal dominant", c:0,
  why:"Recessive conditions need two copies, so carriers are silent and disease can skip generations. Dominant conditions usually show an affected parent in every generation."},
 {week:"2", clue:"Fast, non-specific defence with no memory — neutrophils, complement, barriers", a:"Innate immunity", b:"Adaptive immunity", c:0,
  why:"Innate is immediate and identical every exposure. Adaptive is slower on first contact but specific and builds memory, which is why vaccines work."},
 {week:"2", clue:"IgE-mediated, immediate — anaphylaxis, hay fever, allergic asthma", a:"Type I hypersensitivity", b:"Type IV hypersensitivity", c:0,
  why:"Type I is IgE and mast cells, within minutes. Type IV is T-cell mediated and DELAYED 24 to 72 hours — poison ivy, TB skin test, contact dermatitis."},
 {week:"2", clue:"Delayed 24 to 72 hours, T-cell mediated, no antibody involved", a:"Type IV hypersensitivity", b:"Type II hypersensitivity", c:0,
  why:"Type IV is the only cell-mediated hypersensitivity. Type II is antibody directed against a specific tissue, as in transfusion reactions."},
 {week:"2", clue:"The body makes antibodies against its own tissue", a:"Autoimmunity", b:"Immunodeficiency", c:0,
  why:"Autoimmunity is the immune system attacking self. Immunodeficiency is the immune system failing to attack anything — infection risk rather than self-injury."},
 {week:"2", clue:"Redness, heat, swelling, pain, and loss of function at an injury site", a:"Acute inflammation", b:"Chronic inflammation", c:0,
  why:"Acute inflammation is neutrophil-driven, rapid, and resolves. Chronic inflammation is macrophage and lymphocyte driven, causing fibrosis and granulomas."},
 {week:"3", clue:"Well differentiated, encapsulated, slow growing, does not spread", a:"Benign tumour", b:"Malignant tumour", c:0,
  why:"Benign tumours stay local and resemble their tissue of origin. Malignancy is defined by invasion and metastasis, with poor differentiation and rapid growth."},
 {week:"3", clue:"A gene whose LOSS removes the brake on cell division", a:"Tumour suppressor gene", b:"Oncogene", c:0,
  why:"Tumour suppressors (p53, BRCA, RB) normally restrain growth — losing both copies removes the brake. An oncogene is a mutated accelerator that is gained."},
 {week:"3", clue:"How far the cancer has SPREAD through the body", a:"Staging", b:"Grading", c:0,
  why:"Staging measures spread (TNM: tumour, nodes, metastasis) and drives prognosis and treatment. Grading measures how abnormal the cells look down a microscope."},
 {week:"3", clue:"Spread through lymphatic channels to regional nodes first", a:"Lymphatic spread", b:"Haematogenous spread", c:0,
  why:"Carcinomas typically travel via lymphatics to regional nodes first, which is why nodes are sampled. Sarcomas favour the bloodstream, seeding lung and bone."},
 {week:"4", clue:"Sudden focal deficit from a blocked cerebral artery", a:"Ischemic stroke", b:"Hemorrhagic stroke", c:0,
  why:"Ischemic stroke is an occlusion (thrombus or embolus) and is the majority. Hemorrhagic stroke is a rupture, typically with severe headache and rapid deterioration."},
 {week:"4", clue:"Deficits that resolve completely within 24 hours with no infarction", a:"Transient ischemic attack", b:"Completed stroke", c:0,
  why:"A TIA is a warning: temporary ischemia without tissue death. It carries a high short-term risk of a completed stroke, so it is worked up urgently."},
 {week:"4", clue:"Rising blood pressure with a FALLING pulse and irregular breathing", a:"Increased intracranial pressure", b:"Hypovolemic shock", c:0,
  why:"Cushing triad is a late sign of raised intracranial pressure. Hypovolemia gives the opposite: falling pressure with a RISING pulse."},
 {week:"4", clue:"Resting tremor, rigidity, bradykinesia, from loss of dopamine neurons", a:"Parkinson disease", b:"Multiple sclerosis", c:0,
  why:"Parkinson is a dopamine deficit in the basal ganglia. MS is demyelination of white matter, giving relapsing sensory, visual, and motor deficits."},
 {week:"5", clue:"Cloudy CSF with LOW glucose and high neutrophils", a:"Bacterial meningitis", b:"Viral meningitis", c:0,
  why:"Bacteria consume CSF glucose; viruses do not. Low CSF glucose is the single most useful discriminator and mandates urgent antibiotics."},
 {week:"5", clue:"Ascending weakness after a recent infection, with loss of reflexes", a:"Guillain-Barré syndrome", b:"Myasthenia gravis", c:0,
  why:"Guillain-Barré is post-infectious demyelination ascending from the legs, threatening the respiratory muscles. Myasthenia is fatigable weakness starting in the eyes."},
 {week:"5", clue:"Hypotension with BRADYCARDIA and warm dry skin after spinal injury", a:"Neurogenic shock", b:"Hypovolemic shock", c:0,
  why:"Loss of sympathetic tone means the heart cannot speed up and vessels cannot constrict. Every other shock type produces tachycardia and cool clammy skin."},
 {week:"5", clue:"Weakness that gets WORSE the more the muscle is used", a:"Myasthenia gravis", b:"Muscular dystrophy", c:0,
  why:"Fatigability localises to the neuromuscular junction. Dystrophy is a structural defect in the muscle fibre itself — constant and progressive."},
 {week:"6", clue:"Low TSH with a high free T4", a:"Graves disease (primary hyperthyroid)", b:"Hashimoto thyroiditis", c:0,
  why:"An overactive gland suppresses TSH by negative feedback. Hashimoto is the opposite: a failing gland with HIGH TSH and low T4."},
 {week:"6", clue:"High TSH with a low free T4, plus fatigue, cold intolerance, weight gain", a:"Primary hypothyroidism", b:"Secondary hypothyroidism", c:0,
  why:"High TSH means the pituitary is working and the gland is not. If BOTH TSH and T4 were low, the failure would be at the pituitary."},
 {week:"6", clue:"Moon face, truncal obesity, striae, high glucose, low potassium", a:"Cushing syndrome", b:"Addison disease", c:0,
  why:"Cushing is cortisol excess. Addison is cortisol deficiency — weight LOSS, low sodium, high potassium, hypotension, and hyperpigmentation."},
 {week:"6", clue:"Hyperpigmentation, hypotension, low sodium and HIGH potassium", a:"Addison disease", b:"Cushing syndrome", c:0,
  why:"Loss of aldosterone wastes sodium and retains potassium, and the high ACTH driving the failing gland also darkens the skin."},
 {week:"6", clue:"Very high glucose with ketones and a low pH", a:"Diabetic ketoacidosis", b:"Hyperosmolar hyperglycemic state", c:0,
  why:"DKA needs an absolute insulin deficiency to permit ketogenesis — typically type 1. HHS occurs in type 2, where residual insulin prevents ketosis."},
 {week:"6", clue:"Very high glucose and osmolality with NO ketones and a normal pH", a:"Hyperosmolar hyperglycemic state", b:"Diabetic ketoacidosis", c:0,
  why:"Enough insulin remains to block ketone formation but not to control glucose. The danger is extreme dehydration rather than acidosis."},
 {week:"6", clue:"Excessive thirst and huge volumes of DILUTE urine", a:"Diabetes insipidus", b:"SIADH", c:0,
  why:"Too little ADH means water runs straight through. SIADH is the opposite — water retained, urine concentrated, blood diluted."}
],

/* ---------------- RED FLAGS ---------------- */
redflags: [
 {week:"1", s:"Serum potassium 6.8 mEq/L with peaked T waves on the monitor", act:1,
  why:"Severe hyperkalemia destabilises cardiac conduction and can progress to ventricular fibrillation and arrest."},
 {week:"1", s:"Serum potassium 3.6 mEq/L in a patient eating and drinking normally", act:0,
  why:"That is at the low end of normal. It warrants attention to intake and any diuretic use, but it is not an emergency."},
 {week:"1", s:"Serum sodium 118 mEq/L with new confusion and a seizure", act:1,
  why:"Severe acute hyponatremia causes cerebral oedema. Seizures signal the brain is already swelling — this needs immediate correction."},
 {week:"2", s:"Facial swelling, stridor, and hypotension minutes after a bee sting", act:1,
  why:"Anaphylaxis — a type I hypersensitivity reaction causing airway oedema and distributive shock. Epinephrine is needed immediately."},
 {week:"2", s:"An itchy raised rash after starting a new detergent, no breathing difficulty", act:0,
  why:"Localised contact dermatitis. Uncomfortable and worth identifying the trigger, but the airway and circulation are not threatened."},
 {week:"2", s:"Fever of 38.5°C in a chemotherapy patient with a neutrophil count of 0.4", act:1,
  why:"Neutropenic fever. Without neutrophils there is no pus and few localising signs, so fever may be the ONLY indication of overwhelming infection."},
 {week:"2", s:"Mild fatigue and a low-grade temperature in an otherwise well adult with a normal WBC", act:0,
  why:"A common self-limiting viral picture. Monitor, hydrate, and reassess if it persists or localises."},
 {week:"3", s:"New back pain with leg weakness and urinary retention in a cancer patient", act:1,
  why:"Spinal cord compression from metastasis. Delay risks permanent paralysis — this is an oncologic emergency."},
 {week:"3", s:"Rising potassium, phosphate, and uric acid two days after starting chemotherapy", act:1,
  why:"Tumour lysis syndrome. Massive cell breakdown floods the blood with intracellular contents, threatening dysrhythmias and acute kidney injury."},
 {week:"3", s:"A small, soft, mobile, well-defined lump that has not changed in two years", act:0,
  why:"Those are benign features — mobile, well circumscribed, stable. It should still be documented and followed, but it is not urgent."},
 {week:"4", s:"Rising blood pressure, falling pulse, and irregular respirations after a head injury", act:1,
  why:"Cushing triad — a LATE sign of dangerously raised intracranial pressure and impending brain herniation."},
 {week:"4", s:"A new one-sided dilated pupil that does not react to light", act:1,
  why:"Compression of the third cranial nerve by shifting brain tissue. This is herniation until proven otherwise."},
 {week:"4", s:"Sudden facial droop, arm weakness, and slurred speech that began 40 minutes ago", act:1,
  why:"Acute stroke inside the treatment window. Time lost is brain lost — imaging and reperfusion decisions are time-critical."},
 {week:"4", s:"A long-standing mild hand tremor that is worse when reaching for a cup", act:0,
  why:"An action tremor, typically essential tremor — chronic and non-urgent. A Parkinsonian tremor is present at REST."},
 {week:"4", s:"A patient with sudden altered mental status and a glucose of 38 mg/dL", act:1,
  why:"Hypoglycemia mimics stroke and is instantly reversible. Glucose is checked and corrected before anything else."},
 {week:"5", s:"Fever, neck stiffness, photophobia, and a new petechial rash", act:1,
  why:"Bacterial meningitis, possibly meningococcal. It can kill within hours, so antibiotics are given without waiting for confirmation."},
 {week:"5", s:"Ascending weakness now involving the chest, with a weakening cough", act:1,
  why:"Guillain-Barré ascending to the respiratory muscles. Ventilatory failure is the thing that kills in this condition."},
 {week:"5", s:"A myasthenia patient with worsening weakness and difficulty swallowing secretions", act:1,
  why:"Myasthenic crisis. Involvement of swallowing and breathing muscles threatens the airway and requires ventilatory support."},
 {week:"5", s:"Mild ptosis at the end of a long day that resolves after resting", act:0,
  why:"Typical fatigable weakness of stable myasthenia. It should be tracked, but it is not a crisis while swallowing and breathing are intact."},
 {week:"5", s:"Hypotension with bradycardia and warm dry skin after a cervical spine injury", act:1,
  why:"Neurogenic shock. Loss of sympathetic tone means the usual compensations fail, and perfusion falls quickly."},
 {week:"6", s:"Fever, severe tachycardia, agitation, and confusion in a hyperthyroid patient", act:1,
  why:"Thyroid storm. Uncontrolled hypermetabolism causes high-output cardiac failure and hyperthermia, and it is frequently fatal untreated."},
 {week:"6", s:"Hypothermia, bradycardia, and a falling level of consciousness in a hypothyroid patient", act:1,
  why:"Myxedema coma — the opposite emergency. Metabolism slows to the point of respiratory depression and cardiovascular collapse."},
 {week:"6", s:"Hypotension, vomiting, low sodium, and high potassium in a patient who stopped steroids", act:1,
  why:"Addisonian crisis. Abrupt steroid withdrawal leaves no cortisol for the stress response, producing shock that needs immediate replacement."},
 {week:"6", s:"Glucose 480 mg/dL with ketones, deep rapid breathing, and drowsiness", act:1,
  why:"Diabetic ketoacidosis. Acidosis, dehydration, and electrolyte shifts are all life-threatening and need urgent fluids and insulin."},
 {week:"6", s:"A fasting glucose of 118 mg/dL at a routine check in a well patient", act:0,
  why:"Impaired fasting glucose — an important warning that warrants lifestyle advice and follow-up testing, but not urgent care."},
 {week:"6", s:"A patient on insulin who is sweaty, shaky, and confused before lunch", act:1,
  why:"Hypoglycemia. The brain depends on a continuous glucose supply, and untreated it progresses to seizure and coma within minutes."}
],

/* ---------------- MECHANISM CHAINS ---------------- */
chains: [
 {week:"1", title:"Ischemia to cell death", start:"Blood supply to a tissue is interrupted",
  steps:["Oxygen falls, so the cell switches to anaerobic metabolism","ATP production collapses and lactic acid accumulates","The sodium-potassium pump fails, so sodium and water enter the cell","The cell and its organelles swell, membranes rupture, and necrosis follows"],
  why:"Loss of ATP is the pivot: without it the pump fails and the cell cannot control its own volume. Necrosis spills contents and triggers inflammation."},
 {week:"1", title:"Vomiting to metabolic alkalosis", start:"Persistent vomiting of gastric contents",
  steps:["Hydrogen and chloride ions are lost from the stomach","Serum bicarbonate rises relative to acid","Blood pH climbs above 7.45","The lungs hypoventilate to retain CO₂ and compensate"],
  why:"Vomiting loses acid so alkalosis follows; diarrhoea loses bicarbonate so acidosis follows. Which end the fluid leaves from decides the disorder."},
 {week:"2", title:"The acute inflammatory response", start:"Tissue injury or invasion by a pathogen",
  steps:["Mast cells degranulate, releasing histamine","Arterioles dilate, bringing more blood — redness and heat","Capillary permeability rises, so fluid and protein leak out — swelling","Neutrophils marginate, migrate to the site, and phagocytose the invader"],
  why:"The four cardinal signs are simply the visible result of vasodilation and increased permeability. Pain comes from the pressure and the mediators."},
 {week:"2", title:"Anaphylaxis", start:"Re-exposure to an allergen in a sensitised person",
  steps:["Allergen cross-links IgE bound to mast cells","Mast cells release histamine and other mediators massively","Widespread vasodilation and capillary leak cause hypotension; airway smooth muscle constricts","Distributive shock with airway compromise develops within minutes"],
  why:"Sensitisation must happen first, which is why the FIRST exposure is usually uneventful and the second is catastrophic."},
 {week:"3", title:"How a carcinoma metastasises", start:"A malignant tumour outgrows its local tissue",
  steps:["Cells lose adhesion and invade through the basement membrane","The tumour secretes factors that grow new blood vessels (angiogenesis)","Cells enter lymphatic or blood vessels and travel","They lodge, extravasate, and establish a secondary tumour at a distant site"],
  why:"Invasion through the basement membrane is the defining step that separates malignant from benign, and angiogenesis is what lets the tumour keep growing."},
 {week:"3", title:"Tumour lysis syndrome", start:"Chemotherapy kills a large tumour burden rapidly",
  steps:["Dying cells release their intracellular contents into the blood","Potassium, phosphate, and uric acid all rise sharply","The released phosphate binds serum calcium, so calcium falls","Uric acid crystals and electrolyte shifts cause acute kidney injury and dysrhythmias"],
  why:"Everything intracellular goes up and calcium goes down. It is a complication of successful treatment, which is why at-risk patients are pre-hydrated."},
 {week:"4", title:"The intracranial pressure cascade", start:"An expanding mass or bleed inside the rigid skull",
  steps:["CSF and venous blood are displaced to compensate (Monro-Kellie)","Compensation is exhausted and intracranial pressure climbs","Cerebral perfusion pressure falls, so the body raises systemic blood pressure","Cushing triad appears and brain tissue herniates"],
  why:"The skull cannot expand, so any added volume must displace something else. Once compensation runs out, pressure rises steeply and fast."},
 {week:"4", title:"Ischemic stroke", start:"A thrombus or embolus occludes a cerebral artery",
  steps:["Blood flow to the supplied territory stops","Neurons switch to anaerobic metabolism and ATP fails within minutes","The ischemic core dies while the surrounding penumbra is stunned but salvageable","Untreated, the penumbra is recruited into the infarct and the deficit becomes permanent"],
  why:"The penumbra is why time matters — restoring flow early saves tissue that is not yet dead. That is the whole basis of the treatment window."},
 {week:"5", title:"Bacterial meningitis", start:"Bacteria reach the subarachnoid space",
  steps:["Organisms multiply in CSF, which has few local defences","Neutrophils flood in and consume CSF glucose","Inflammation makes the meninges irritable — neck stiffness, photophobia, headache","Cerebral oedema and rising intracranial pressure threaten perfusion"],
  why:"Low CSF glucose with high neutrophils is the diagnostic fingerprint, and it is exactly what this cascade predicts."},
 {week:"6", title:"Diabetic ketoacidosis", start:"Absolute insulin deficiency in type 1 diabetes",
  steps:["Glucose cannot enter cells, so blood glucose climbs and cells starve","The body breaks down fat for fuel, producing ketoacids","Ketoacids consume bicarbonate and blood pH falls","Kussmaul respirations blow off CO₂ while osmotic diuresis causes profound dehydration"],
  why:"The cells are starving in a sea of glucose. Fat breakdown is the compensation, and the ketoacids it produces are what causes the acidosis."},
 {week:"6", title:"Addisonian crisis", start:"Abrupt withdrawal of long-term steroid therapy",
  steps:["The suppressed adrenal glands cannot resume cortisol production","Without cortisol there is no stress response and vascular tone falls","Aldosterone deficiency wastes sodium and retains potassium","Hypotension, hyponatremia, and hyperkalemia produce shock"],
  why:"Chronic exogenous steroids suppress the axis by negative feedback, so stopping abruptly leaves the patient unable to mount any cortisol response."}
]
};
